import { Inject, Injectable, OnModuleInit, OnModuleDestroy } from '@nestjs/common';
import { Pool, PoolClient } from 'pg';
import { randomUUID } from 'node:crypto';
import { PG_POOL } from '../database/database.constants';
import { AppError } from '../common/app-error';
import type { AuthUser } from '../auth/auth.types';

type Input = Record<string, unknown>;
const current = "r.valid_from<=now() AND (r.valid_to IS NULL OR r.valid_to>now())";
const itemSelect = `SELECT i.*, p.first_name||' '||p.last_name AS creator_name,
 CASE WHEN i.completed_at IS NOT NULL THEN 'COMPLETED'
 WHEN i.deadline<now() AND i.lifecycle='ACTIVE' THEN 'OVERDUE'
 WHEN EXISTS(SELECT 1 FROM guidance.recipients r WHERE r.item_id=i.id) AND NOT EXISTS(SELECT 1 FROM guidance.recipients r WHERE r.item_id=i.id AND r.seen_at IS NULL) THEN 'SEEN' ELSE 'SENT' END AS status
 FROM guidance.items i JOIN identity.accounts a ON a.id=i.created_by JOIN identity.people p ON p.id=a.person_id`;
export const input = (value: unknown): Input => {
 if (!value || typeof value!=='object' || Array.isArray(value)) throw new AppError(400,'INVALID','اطلاعات معتبر وارد کنید.');
 return value as Input;
};
export function str(value: unknown, max=200, optional=false): string {
 if (optional && (value===undefined || value===null || value==='')) return '';
 if(typeof value!=='string'||!value.trim()||value.trim().length>max) throw new AppError(400,'INVALID','مقدار فیلد الزامی یا طول آن معتبر نیست.');
 return value.trim();
}
export function id(value: unknown): string {
 const v=str(value,36); if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v)) throw new AppError(400,'INVALID_ID','شناسه معتبر نیست.'); return v;
}
function choice(value:unknown, values:string[]) { const v=str(value); if(!values.includes(v)) throw new AppError(400,'INVALID','گزینه معتبر نیست.'); return v; }
function flag(value: unknown) { if(value!==undefined && typeof value!=='boolean') throw new AppError(400,'INVALID','مقدار بله/خیر معتبر نیست.'); return value===true; }
@Injectable()
export class GuidanceService implements OnModuleInit, OnModuleDestroy {
 private timer?: ReturnType<typeof setInterval>;
 private running=false;
 constructor(@Inject(PG_POOL) private readonly pool: Pool) {}
 onModuleInit() { this.timer=setInterval(()=>{void this.automation().catch(()=>console.error('Guidance automation failed'));},30000); this.timer.unref(); }
 onModuleDestroy() { if(this.timer) clearInterval(this.timer); }
 isGuide(user:AuthUser) { return user.roles.some(r=>r.roleCode==='SUPREME_GUIDE'&&r.scopeType==='ORGANIZATION'&&r.scopeId===null); }
 async tx<T>(user:AuthUser|null, fn:(c:PoolClient)=>Promise<T>, guide=true):Promise<T> {
 const c=await this.pool.connect();
 try { await c.query('BEGIN'); await c.query("SELECT pg_advisory_xact_lock(1405,5)");
 if(user){const ok=await c.query(`SELECT 1 FROM identity.accounts a JOIN identity.role_assignments r ON r.account_id=a.id WHERE a.id=$1 AND a.status='ACTIVE' AND ${current} ${guide?"AND r.role_code='SUPREME_GUIDE' AND r.scope_type='ORGANIZATION' AND r.scope_id IS NULL":''}`, [user.accountId]); if(!ok.rowCount)throw new AppError(403,'FORBIDDEN','دسترسی به این عملیات مجاز نیست.');}
 const result=await fn(c);await c.query('COMMIT');return result;
 }catch(e){await c.query('ROLLBACK'); const code=(e as {code?:string}).code; if(['23505','23P01','23503','23514'].includes(code??''))throw new AppError(409,'CONFLICT','این تغییر با وضعیت فعلی سازگار نیست. صفحه را تازه کنید.');throw e;}finally{c.release();}
 }
 async history(c:PoolClient,user:AuthUser|null,type:string,entity:string,action:string,previous:unknown,next:unknown,reason=''){
 const data={previous:previous??null,next:next??null,reason:reason||null};
 await c.query(`INSERT INTO guidance.history(entity_type,entity_id,actor_id,action,previous_state,new_state,reason) VALUES($1,$2,$3,$4,$5,$6,$7)`,[type,entity,user?.accountId??null,action,JSON.stringify(previous??null),JSON.stringify(next??null),reason||null]);
 await c.query(`INSERT INTO admin.audit_events(event_type,actor_account_id,entity_type,entity_id,metadata) VALUES($1,$2,$3,$4,$5)`,['GUIDE_'+action,user?.accountId??null,type,entity,JSON.stringify(data)]);
 }
 async notify(c:PoolClient,recipients:string[],message:string,category:string,key:string,item:string|null=null,visibility='PRIVATE'){
 for(const recipient of new Set(recipients))await c.query(`INSERT INTO guidance.notifications(recipient_id,item_id,category,message,visibility,dedupe_key) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(recipient_id,dedupe_key) DO NOTHING`,[recipient,item,category,message,visibility,key]);
 }
 async guides(c:PoolClient){return (await c.query(`SELECT DISTINCT a.id FROM identity.accounts a JOIN identity.role_assignments r ON r.account_id=a.id WHERE a.status='ACTIVE' AND r.role_code='SUPREME_GUIDE' AND ${current}`)).rows.map(r=>r.id as string);}
 async metadata(){return {roles:(await this.pool.query("SELECT * FROM identity.roles WHERE code<>'SUPREME_GUIDE' ORDER BY label_fa")).rows,groups:(await this.pool.query("SELECT id,COALESCE(NULLIF(name,''),'گروه '||group_number) AS name FROM organization.groups WHERE status='ACTIVE' ORDER BY name")).rows};}
 async people(q:Record<string,string>){
 const term=q.q??''; if(term.length>200)throw new AppError(400,'INVALID','عبارت جستجو طولانی است.');
 return {people:(await this.pool.query(`SELECT p.id,p.first_name,p.last_name,p.mobile,p.national_id,a.id AS account_id,a.status AS account_status,
 COALESCE((SELECT jsonb_agg(jsonb_build_object('id',r.id,'role_code',r.role_code,'label',ro.label_fa,'scope_type',r.scope_type,'scope_id',r.scope_id,'group_name',COALESCE(NULLIF(g.name,''),'گروه '||g.group_number))) FROM identity.role_assignments r JOIN identity.roles ro ON ro.code=r.role_code LEFT JOIN organization.groups g ON g.id=r.scope_id WHERE r.account_id=a.id AND ${current}),'[]') AS roles
 FROM identity.people p LEFT JOIN identity.accounts a ON a.person_id=p.id
 WHERE EXISTS(SELECT 1 FROM identity.role_assignments org WHERE org.account_id=a.id AND org.role_code IN ('GROUP_LEADER','HELPER','COUNCIL_MEMBER','EXECUTIVE_MANAGER','TECH_ADMIN')) AND NOT EXISTS(SELECT 1 FROM identity.role_assignments rg WHERE rg.account_id=a.id AND rg.role_code='SUPREME_GUIDE' AND (rg.valid_to IS NULL OR rg.valid_to>now())) AND ($1='' OR concat_ws(' ',p.first_name,p.last_name,p.mobile,p.national_id) ILIKE '%'||$1||'%')
 AND ($2='' OR a.status=$2 OR ($2='NO_ACCOUNT' AND a.id IS NULL))
 AND ($3='' OR EXISTS(SELECT 1 FROM identity.role_assignments r WHERE r.account_id=a.id AND r.role_code=$3 AND ${current}))
 AND ($4='' OR EXISTS(SELECT 1 FROM identity.role_assignments r WHERE r.account_id=a.id AND r.scope_id::text=$4 AND ${current}))
 AND ($5<>'NONE' OR NOT EXISTS(SELECT 1 FROM identity.role_assignments r WHERE r.account_id=a.id AND ${current}))
 AND ($5<>'MULTIPLE' OR (SELECT count(*) FROM identity.role_assignments r WHERE r.account_id=a.id AND ${current})>1)
 ORDER BY p.last_name,p.first_name,p.id`,[term,q.status??'',q.role??'',q.group??'',q.responsibility??''])).rows};
 }
 async person(personId:string){id(personId);const data=(await this.people({})).people.filter(p=>p.id===personId);if(!data.length)throw new AppError(404,'NOT_FOUND','فرد پیدا نشد.');return {person:data[0],history:(await this.pool.query(`SELECT h.*,p.first_name||' '||p.last_name AS actor_name FROM guidance.history h LEFT JOIN identity.accounts a ON a.id=h.actor_id LEFT JOIN identity.people p ON p.id=a.person_id WHERE h.entity_type='PERSON' AND h.entity_id=$1 ORDER BY h.occurred_at,h.id`,[personId])).rows};}
 async appointments(){return {history:(await this.pool.query(`SELECT h.*,p.first_name||' '||p.last_name AS person_name FROM guidance.history h JOIN identity.people p ON p.id=h.entity_id WHERE h.entity_type='PERSON' ORDER BY h.occurred_at DESC,h.id`)).rows};}
 async refreshAlertOwners(c:PoolClient,user:AuthUser,group:string){const owner=(await c.query(`SELECT r.account_id FROM identity.role_assignments r WHERE r.scope_id=$1 AND r.role_code='GROUP_LEADER' AND ${current} LIMIT 1`,[group])).rows[0]?.account_id??null;const alerts=(await c.query("SELECT * FROM oversight.alerts WHERE state<>'RESOLVED' AND (group_id=$1 OR family_id IN(SELECT id FROM family.families WHERE current_group_id=$1)) AND owner_id IS DISTINCT FROM $2::uuid FOR UPDATE",[group,owner])).rows;for(const a of alerts){await c.query('UPDATE oversight.alerts SET owner_id=$2,escalated=escalated OR ($2::uuid IS NULL),updated_at=now() WHERE id=$1',[a.id,owner]);await this.history(c,user,'ALERT',a.id,'ALERT_OWNER_CHANGED',a,{owner_id:owner});}}
 async assignment(c:PoolClient,user:AuthUser,account:string,role:string,scope:string|null,reason:string,oldId?:string){
 const accountRow=(await c.query("SELECT id,person_id FROM identity.accounts WHERE id=$1 AND status='ACTIVE' FOR UPDATE",[account])).rows[0];if((await c.query("SELECT 1 FROM identity.role_assignments WHERE account_id=$1 AND role_code='SUPREME_GUIDE' AND (valid_to IS NULL OR valid_to>now())",[account])).rowCount)throw new AppError(409,'GUIDE_FIXED','راهبر در ابزار مسئولیت‌های عمومی مدیریت نمی‌شود.');if(!accountRow)throw new AppError(409,'ACCOUNT_REQUIRED','این فرد باید حساب فعال داشته باشد؛ ساخت حساب از مسیر تأمین حساب انجام می‌شود.');
 if(!(await c.query('SELECT 1 FROM identity.roles WHERE code=$1',[role])).rowCount)throw new AppError(400,'INVALID_ROLE','نقش معتبر نیست.');
 if(role==='SUPREME_GUIDE')throw new AppError(400,'INVALID_SCOPE','Scope راهبر باید سازمانی باشد.');
 if(['EXECUTIVE_MANAGER','COUNCIL_MEMBER','TECH_ADMIN'].includes(role)&&scope)throw new AppError(400,'INVALID_SCOPE','این مسئولیت در سطح کانون تعریف می‌شود.');
 if(['GROUP_LEADER','HELPER'].includes(role)&&!scope)throw new AppError(400,'INVALID_SCOPE','گروه را انتخاب کنید.');
 if(scope&&!(await c.query("SELECT 1 FROM organization.groups WHERE id=$1 AND status='ACTIVE' FOR UPDATE",[scope])).rowCount)throw new AppError(409,'GROUP_INACTIVE','گروه فعال نیست.');
 let previous=null;
 if(oldId){previous=(await c.query(`SELECT * FROM identity.role_assignments r WHERE id=$1 AND account_id=$2 AND ${current} FOR UPDATE`,[oldId,account])).rows[0];if(!previous)throw new AppError(409,'STALE','مسئولیت قبلاً خاتمه یافته است.');if(previous.role_code==='SUPREME_GUIDE')throw new AppError(409,'GUIDE_FIXED','انتقال یا خاتمه نقش یگانه راهبر در این مرحله مجاز نیست.');if(previous.scope_id&&previous.scope_id!==scope)await this.history(c,user,'GROUP',previous.scope_id,'ROLE_ENDED',previous,null,reason);await c.query('UPDATE identity.role_assignments SET valid_to=now() WHERE id=$1',[oldId]);}
 if((await c.query(`SELECT 1 FROM identity.role_assignments r WHERE account_id=$1 AND role_code=$2 AND scope_id IS NOT DISTINCT FROM $3::uuid AND ${current}`,[account,role,scope])).rowCount)throw new AppError(409,'DUPLICATE','این مسئولیت هم‌اکنون فعال است.');
 if(role==='GROUP_LEADER'){
 const olds=(await c.query(`SELECT r.*,a.person_id FROM identity.role_assignments r JOIN identity.accounts a ON a.id=r.account_id WHERE r.role_code='GROUP_LEADER' AND r.scope_id=$1 AND ${current} FOR UPDATE OF r`,[scope])).rows;
 if(!previous)previous=olds.map(old=>({account_id:old.account_id,role_code:old.role_code,scope_id:old.scope_id}));
 for(const old of olds){await c.query('UPDATE identity.role_assignments SET valid_to=now() WHERE id=$1',[old.id]);await this.history(c,user,'PERSON',old.person_id,'ROLE_ENDED',old,null,reason);}
 }
 const next=(await c.query('INSERT INTO identity.role_assignments(account_id,role_code,scope_type,scope_id) VALUES($1,$2,$3,$4) RETURNING *',[account,role,scope?'GROUP':'ORGANIZATION',scope])).rows[0];
 if(role==='GROUP_LEADER'&&scope)await this.refreshAlertOwners(c,user,scope);if(oldId&&previous?.role_code==='GROUP_LEADER'&&previous.scope_id!==scope)await this.refreshAlertOwners(c,user,previous.scope_id);
 next.person_name=(await c.query("SELECT first_name||' '||last_name AS name FROM identity.people WHERE id=$1",[accountRow.person_id])).rows[0].name;
 await this.history(c,user,'PERSON',accountRow.person_id,oldId?'ROLE_CHANGED':'ROLE_ASSIGNED',previous,next,reason);
 if(scope)await this.history(c,user,'GROUP',scope,role==='GROUP_LEADER'?'LEADER_CHANGED':'ROLE_ASSIGNED',previous,next,reason);
 const targets=(await c.query("SELECT id FROM identity.accounts WHERE status='ACTIVE'")).rows.map(r=>r.id);
 const label=(await c.query('SELECT label_fa FROM identity.roles WHERE code=$1',[role])).rows[0].label_fa;
 const person=(await c.query("SELECT first_name||' '||last_name AS name FROM identity.people WHERE id=$1",[accountRow.person_id])).rows[0].name;
 const groupName=scope?(await c.query('SELECT name FROM organization.groups WHERE id=$1',[scope])).rows[0].name:'';
 await this.notify(c,targets,`مسئولیت ${label}${groupName?' در گروه '+groupName:''} به ${person} واگذار شد.`,'RESPONSIBILITY',next.id,null,'PUBLIC');return next;
 }
 async assign(personId:string,value:unknown,user:AuthUser){id(personId);const b=input(value), role=str(b.role),scope=b.scopeId?id(b.scopeId):null,reason=str(b.reason,2000,true),old=b.assignmentId?id(b.assignmentId):undefined;
 return this.tx(user,async c=>{const a=(await c.query('SELECT id FROM identity.accounts WHERE person_id=$1',[personId])).rows;if(a.length!==1)throw new AppError(409,'ACCOUNT_REQUIRED','حساب یکتای فعال برای این فرد لازم است.');return this.assignment(c,user,a[0].id,role,scope,reason,old);});}
 async endRole(personId:string,value:unknown,user:AuthUser){id(personId);const b=input(value),assignment=id(b.assignmentId),reason=str(b.reason,2000,true);return this.tx(user,async c=>{const old=(await c.query(`SELECT r.* FROM identity.role_assignments r JOIN identity.accounts a ON a.id=r.account_id WHERE r.id=$1 AND a.person_id=$2 AND ${current} FOR UPDATE OF r`,[assignment,personId])).rows[0];if(!old)throw new AppError(409,'STALE','مسئولیت فعال پیدا نشد.');if(old.role_code==='SUPREME_GUIDE')throw new AppError(409,'GUIDE_FIXED','نقش یگانه راهبر باید حفظ شود.');await c.query('UPDATE identity.role_assignments SET valid_to=now() WHERE id=$1',[assignment]);if(old.role_code==='GROUP_LEADER'&&old.scope_id)await this.refreshAlertOwners(c,user,old.scope_id);await this.history(c,user,'PERSON',personId,'ROLE_ENDED',old,null,reason);if(old.scope_id)await this.history(c,user,'GROUP',old.scope_id,'ROLE_ENDED',old,null,reason);await this.notify(c,(await c.query("SELECT id FROM identity.accounts WHERE status='ACTIVE'")).rows.map(r=>r.id),'پایان یک مسئولیت سازمانی ثبت شد.','RESPONSIBILITY',randomUUID(),null,'PUBLIC');return {ok:true};});}
 async groups(){return {groups:(await this.pool.query(`SELECT g.*,
 (SELECT p.first_name||' '||p.last_name FROM identity.role_assignments r JOIN identity.accounts a ON a.id=r.account_id JOIN identity.people p ON p.id=a.person_id WHERE r.scope_id=g.id AND r.role_code='GROUP_LEADER' AND ${current} LIMIT 1) AS leader_name,
 (SELECT count(DISTINCT r.account_id)::int FROM identity.role_assignments r WHERE r.scope_id=g.id AND r.role_code='HELPER' AND ${current}) AS helpers,
 (SELECT count(*)::int FROM family.families f WHERE f.current_group_id=g.id) AS families
 FROM organization.groups g ORDER BY g.name`)).rows};}
 async group(groupId:string){id(groupId);const group=(await this.groups()).groups.find(g=>g.id===groupId);if(!group)throw new AppError(404,'NOT_FOUND','گروه پیدا نشد.');return {group,members:(await this.people({group:groupId})).people,families:(await this.pool.query('SELECT id,family_code,status FROM family.families WHERE current_group_id=$1 ORDER BY family_code',[groupId])).rows,history:(await this.pool.query("SELECT h.*,p.first_name||' '||p.last_name AS actor_name FROM guidance.history h LEFT JOIN identity.accounts a ON a.id=h.actor_id LEFT JOIN identity.people p ON p.id=a.person_id WHERE entity_type='GROUP' AND entity_id=$1 ORDER BY occurred_at,h.id",[groupId])).rows};}
 async createGroup(value:unknown,user:AuthUser){const b=input(value),name=str(b.name,150,true),account=id(b.accountId);return this.tx(user,async c=>{const group=(await c.query('INSERT INTO organization.groups(code,name) VALUES($1,$2) RETURNING *',['G-'+randomUUID().slice(0,16),name])).rows[0];await this.history(c,user,'GROUP',group.id,'GROUP_CREATED',null,group);await this.assignment(c,user,account,'GROUP_LEADER',group.id,'');return group;});}
 async changeLeader(groupId:string,value:unknown,user:AuthUser){id(groupId);const b=input(value),account=id(b.accountId);return this.tx(user,c=>this.assignment(c,user,account,'GROUP_LEADER',groupId,str(b.reason,2000,true)));}
 async dissolve(groupId:string,value:unknown,user:AuthUser){id(groupId);const b=input(value);return this.tx(user,async c=>{const old=(await c.query("SELECT * FROM organization.groups WHERE id=$1 AND status='ACTIVE' FOR UPDATE",[groupId])).rows[0];if(!old)throw new AppError(409,'STALE','گروه فعال پیدا نشد.');const roles=(await c.query(`SELECT r.*,a.person_id FROM identity.role_assignments r JOIN identity.accounts a ON a.id=r.account_id WHERE scope_id=$1 AND ${current}`,[groupId])).rows;for(const r of roles){await c.query('UPDATE identity.role_assignments SET valid_to=now() WHERE id=$1',[r.id]);await this.history(c,user,'PERSON',r.person_id,'ROLE_ENDED',r,null,str(b.reason,2000,true));}await c.query("UPDATE organization.groups SET status='DISSOLVED' WHERE id=$1",[groupId]);await this.history(c,user,'GROUP',groupId,'GROUP_DISSOLVED',old,{...old,status:'DISSOLVED'},str(b.reason,2000,true));await this.notify(c,(await c.query("SELECT id FROM identity.accounts WHERE status='ACTIVE'")).rows.map(r=>r.id),'انحلال گروه '+old.name+' ثبت شد؛ سوابق و خانواده‌ها محفوظ است.','RESPONSIBILITY',randomUUID(),null,'PUBLIC');return {ok:true};});}
 private async audience(c:PoolClient,b:Input,user:AuthUser,kind:string){
 const type=kind==='COORDINATION'?'GUIDE':choice(b.audienceType,['PEOPLE','ROLE','GROUP','ALL','GUIDE']);
 const specs=Array.isArray(b.audience)?b.audience:[]; if(specs.length>200)throw new AppError(400,'INVALID','تعداد مخاطبان بیش از حد است.');
 let rows;
 if(type==='GUIDE')rows=await this.guides(c);
 else if(type==='ALL')rows=(await c.query("SELECT id FROM identity.accounts WHERE status='ACTIVE'")).rows.map(r=>r.id);
 else if(type==='PEOPLE'){if(!specs.length)throw new AppError(400,'AUDIENCE','مخاطب را انتخاب کنید.');const ids=specs.map(id);rows=(await c.query("SELECT id FROM identity.accounts WHERE status='ACTIVE' AND id=ANY($1::uuid[])",[ids])).rows.map(r=>r.id);if(rows.length!==new Set(ids).size)throw new AppError(400,'AUDIENCE','مخاطب فعال پیدا نشد.');}
 else {if(specs.length!==1)throw new AppError(400,'AUDIENCE','یک نقش یا گروه انتخاب کنید.');const v=type==='GROUP'?id(specs[0]):str(specs[0]);if(type==='GROUP'&&!(await c.query("SELECT 1 FROM organization.groups WHERE id=$1 AND status='ACTIVE'",[v])).rowCount)throw new AppError(409,'GROUP_INACTIVE','گروه فعال نیست.');rows=(await c.query(`SELECT DISTINCT a.id FROM identity.accounts a JOIN identity.role_assignments r ON r.account_id=a.id WHERE a.status='ACTIVE' AND ${current} AND ${type==='GROUP'?'r.scope_id=$1::uuid':'r.role_code=$1'}`,[v])).rows.map(r=>r.id);}
 if(!rows.length)throw new AppError(400,'AUDIENCE','مخاطب فعالی پیدا نشد.');return {type,specs,accounts:rows as string[]};
 }
 async createItem(value:unknown,user:AuthUser,coordination=false){const b=input(value);return this.tx(user,c=>this.insertItem(c,b,user,coordination),!coordination);}
 private async insertItem(c:PoolClient,b:Input,user:AuthUser,coordination=false){
 const kind=coordination?'COORDINATION':choice(b.kind,['DECISION','PERMISSION','MISSION','URGENT']);const subject=str(b.subject),body=str(b.body,10000,coordination);const confidential=coordination?true:flag(b.confidential);const discuss=flag(b.discussInCouncil);
 let deadline:string|null=null;if(b.deadline){const raw=str(b.deadline,40);if(!/^\d{4}-\d\d-\d\dT/.test(raw)||!Number.isFinite(Date.parse(raw)))throw new AppError(400,'DEADLINE','مهلت معتبر نیست.');deadline=new Date(raw).toISOString();}if(coordination&&deadline)throw new AppError(400,'DEADLINE','هماهنگی مهلت اجرایی ندارد.');
 const audience=await this.audience(c,b,user,kind);
 let followUp:string|null=null;if(b.followUpFor){if(coordination)throw new AppError(400,'INVALID','هماهنگی مأموریت پیگیری نیست.');followUp=id(b.followUpFor);await this.accessible(c,followUp,user);if(!(await c.query('SELECT 1 FROM guidance.alerts WHERE item_id=$1 AND closed_at IS NULL',[followUp])).rowCount)throw new AppError(409,'STALE','هشدار باز پیدا نشد.');}
 const item=(await c.query(`INSERT INTO guidance.items(kind,subject,body,created_by,deadline,confidential,audience_type,audience_spec,discuss_in_council,follow_up_for) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[kind,subject,body,user.accountId,deadline,confidential,audience.type,JSON.stringify(audience.specs),discuss,followUp])).rows[0];
 for(const account of audience.accounts)await c.query('INSERT INTO guidance.recipients(item_id,account_id) VALUES($1,$2)',[item.id,account]);
 await this.history(c,user,'ITEM',item.id,'CREATED',null,item);
 await this.notify(c,audience.accounts,subject,coordination?'COORDINATION':'DECISION','item:'+item.id,item.id,confidential?'PRIVATE':'PUBLIC');
 if(kind==='URGENT') {await c.query("INSERT INTO guidance.alerts(item_id,category) VALUES($1,'IMPORTANT')",[item.id]);await this.notify(c,await this.guides(c),subject,'IMPORTANT','important:'+item.id,item.id);}
 return item;
 }
 async items(user:AuthUser,q:Record<string,string>){return {items:(await this.pool.query(`${itemSelect} WHERE ($1 OR i.created_by=$2 OR (NOT i.confidential) OR EXISTS(SELECT 1 FROM guidance.recipients r WHERE r.item_id=i.id AND r.account_id=$2)) AND ($3='' OR i.kind=$3) AND ($4='' OR concat_ws(' ',i.subject,i.body) ILIKE '%'||$4||'%') ORDER BY i.created_at DESC,i.id`,[this.isGuide(user),user.accountId,q.kind??'',q.q??''])).rows};}
 private async accessible(c:PoolClient,itemId:string,user:AuthUser,lock=false){const i=(await c.query(`SELECT * FROM guidance.items WHERE id=$1 ${lock?'FOR UPDATE':''}`,[itemId])).rows[0];if(!i)throw new AppError(404,'NOT_FOUND','مورد پیدا نشد.');if(!this.isGuide(user)&&i.confidential&&i.created_by!==user.accountId&&!(await c.query('SELECT 1 FROM guidance.recipients WHERE item_id=$1 AND account_id=$2',[itemId,user.accountId])).rowCount)throw new AppError(404,'NOT_FOUND','مورد پیدا نشد.');return i;}
 async detail(itemId:string,user:AuthUser){id(itemId);const c=await this.pool.connect();try{await this.accessible(c,itemId,user);const item=(await c.query(`${itemSelect} WHERE i.id=$1`,[itemId])).rows[0];const receipts=(await c.query(`SELECT r.*,p.first_name||' '||p.last_name AS name FROM guidance.recipients r JOIN identity.accounts a ON a.id=r.account_id JOIN identity.people p ON p.id=a.person_id WHERE item_id=$1 AND ($2 OR account_id=$3) ORDER BY name`,[itemId,this.isGuide(user),user.accountId])).rows;return {item,receipts,alerts:(await c.query('SELECT id,closed_at FROM guidance.alerts WHERE item_id=$1',[itemId])).rows,history:(await c.query(`SELECT h.*,p.first_name||' '||p.last_name AS actor_name FROM guidance.history h LEFT JOIN identity.accounts a ON a.id=h.actor_id LEFT JOIN identity.people p ON p.id=a.person_id WHERE entity_type='ITEM' AND entity_id=$1 AND ($2 OR action IN ('CREATED','CANCELLED','REPLACED','REVISED','REVIEW_APPROVED','REVIEW_RECONSIDER','REVIEW_CANCELLED')) ORDER BY occurred_at,h.id`,[itemId,this.isGuide(user)])).rows};}finally{c.release();}}
 async seen(itemId:string,user:AuthUser){id(itemId);return this.tx(user,async c=>{await this.accessible(c,itemId,user);const r=(await c.query('UPDATE guidance.recipients SET seen_at=now() WHERE item_id=$1 AND account_id=$2 AND seen_at IS NULL RETURNING *',[itemId,user.accountId])).rows[0];if(r)await this.history(c,user,'ITEM',itemId,'SEEN',null,{accountId:user.accountId,seen_at:r.seen_at});await c.query('UPDATE guidance.notifications SET seen_at=COALESCE(seen_at,now()) WHERE item_id=$1 AND recipient_id=$2',[itemId,user.accountId]);return {ok:true};},false);}
 async complete(itemId:string,value:unknown,user:AuthUser){if(this.isGuide(user))throw new AppError(403,'OBSERVER','راهبر ناظر است و نتیجه عملیاتی ثبت نمی‌کند.');id(itemId);const b=input(value),result=str(b.result,5000);return this.tx(user,async c=>{const item=await this.accessible(c,itemId,user,true);if(item.lifecycle!=='ACTIVE'||item.completed_at||['COUNCIL','COORDINATION'].includes(item.kind))throw new AppError(409,'STALE','این مورد قابل ثبت نتیجه نیست.');const r=(await c.query('SELECT * FROM guidance.recipients WHERE item_id=$1 AND account_id=$2 FOR UPDATE',[itemId,user.accountId])).rows[0];if(!r)throw new AppError(403,'FORBIDDEN','فقط مخاطب می‌تواند نتیجه خود را ثبت کند.');if(r.completed_at)throw new AppError(409,'STALE','نتیجه قبلاً ثبت شده است.');await c.query('UPDATE guidance.recipients SET seen_at=COALESCE(seen_at,now()),completed_at=now(),result=$3 WHERE item_id=$1 AND account_id=$2',[itemId,user.accountId,result]);await this.history(c,user,'ITEM',itemId,'RESULT',r,{accountId:user.accountId,result});const pending=await c.query('SELECT 1 FROM guidance.recipients WHERE item_id=$1 AND completed_at IS NULL',[itemId]);if(!pending.rowCount){await c.query('UPDATE guidance.items SET completed_at=now(),result=$2,version=version+1 WHERE id=$1',[itemId,result]);const closed=(await c.query('UPDATE guidance.alerts SET closed_at=now() WHERE item_id=$1 AND closed_at IS NULL RETURNING id',[itemId])).rows;if(closed.length)await this.history(c,user,'ITEM',itemId,'ALERT_RESOLVED',null,{alerts:closed});if(item.follow_up_for){const related=(await c.query('UPDATE guidance.alerts SET closed_at=now() WHERE item_id=$1 AND closed_at IS NULL RETURNING id',[item.follow_up_for])).rows;if(related.length){await c.query('UPDATE guidance.items SET completed_at=COALESCE(completed_at,now()),result=COALESCE(result,$2),version=version+1 WHERE id=$1',[item.follow_up_for,result]);await this.history(c,user,'ITEM',item.follow_up_for,'ALERT_RESOLVED',null,{followUp:itemId,result,alerts:related});}}}
 await this.notify(c,await this.guides(c),'نتیجه اقدام ثبت شد: '+item.subject,'RESULT','result:'+itemId+':'+user.accountId,itemId);return {ok:true};},false);}
 async action(itemId:string,value:unknown,user:AuthUser){id(itemId);const b=input(value),action=choice(b.action,['CANCEL','REVISE','REPLACE','APPROVE','RECONSIDER']),reason=str(b.reason,2000,true);return this.tx(user,async c=>{const old=await this.accessible(c,itemId,user,true);if(!Number.isInteger(b.version)||b.version!==old.version)throw new AppError(409,'STALE','اطلاعات تغییر کرده است؛ صفحه را تازه کنید.');if(old.kind==='COORDINATION')throw new AppError(400,'NO_APPROVAL','هماهنگی نیاز به تأیید یا رد ندارد.');if(old.lifecycle==='REPLACED')throw new AppError(409,'STALE','این مورد جایگزین شده است.');let replacement=null;
 if(action==='REPLACE'){replacement=await this.insertItem(c,input(b.replacement),user);await c.query('UPDATE guidance.items SET supersedes=$2 WHERE id=$1',[replacement.id,itemId]);await c.query("UPDATE guidance.items SET lifecycle='REPLACED',review_state='REPLACED',version=version+1 WHERE id=$1",[itemId]);}
 else if(action==='CANCEL')await c.query("UPDATE guidance.items SET lifecycle='CANCELLED',review_state='CANCELLED',version=version+1 WHERE id=$1",[itemId]);
 else if(action==='REVISE'){if(old.lifecycle!=='ACTIVE'||old.completed_at)throw new AppError(409,'STALE','مورد پایان‌یافته را با تصمیم جدید جایگزین کنید.');await c.query('UPDATE guidance.items SET subject=$2,body=$3,version=version+1 WHERE id=$1',[itemId,str(b.subject),str(b.body,10000)]);}
 else {if(old.kind!=='COUNCIL'||old.lifecycle!=='ACTIVE')throw new AppError(400,'INVALID','این اقدام فقط برای مصوبه فعال است.');await c.query('UPDATE guidance.items SET review_state=$2,version=version+1 WHERE id=$1',[itemId,action==='APPROVE'?'APPROVED':'RECONSIDER']);}
 const next=(await c.query('SELECT * FROM guidance.items WHERE id=$1',[itemId])).rows[0];await this.history(c,user,'ITEM',itemId,action==='REPLACE'?'REPLACED':action==='CANCEL'?'CANCELLED':action==='REVISE'?'REVISED':'REVIEW_'+(action==='APPROVE'?'APPROVED':'RECONSIDER'),old,next,reason);
 await this.notify(c,(await c.query('SELECT account_id FROM guidance.recipients WHERE item_id=$1',[itemId])).rows.map(r=>r.account_id),'بازنگری مورد: '+next.subject,'DECISION',randomUUID(),itemId);return {item:next,replacementId:replacement?.id};});}
 async notifications(user:AuthUser){return {notifications:(await this.pool.query(`SELECT n.* FROM guidance.notifications n LEFT JOIN guidance.items i ON i.id=n.item_id WHERE n.recipient_id=$1 AND (i.id IS NULL OR NOT i.confidential OR $2 OR i.created_by=$1 OR EXISTS(SELECT 1 FROM guidance.recipients r WHERE r.item_id=i.id AND r.account_id=$1)) ORDER BY n.created_at DESC,n.id`,[user.accountId,this.isGuide(user)])).rows};}
 async notificationSeen(notificationId:string,user:AuthUser){id(notificationId);return this.tx(user,async c=>{const r=await c.query('UPDATE guidance.notifications SET seen_at=COALESCE(seen_at,now()) WHERE id=$1 AND recipient_id=$2 RETURNING id',[notificationId,user.accountId]);if(!r.rowCount)throw new AppError(404,'NOT_FOUND','اعلان پیدا نشد.');return {ok:true};},false);}
 async automation(){if(this.running)return;this.running=true;try{await this.tx(null,async c=>{const due=(await c.query("SELECT * FROM guidance.items WHERE deadline<now() AND completed_at IS NULL AND lifecycle='ACTIVE' AND kind NOT IN ('COORDINATION','COUNCIL')")).rows;for(const item of due){const created=await c.query("INSERT INTO guidance.alerts(item_id,category) VALUES($1,'OVERDUE') ON CONFLICT DO NOTHING RETURNING id",[item.id]);if(created.rowCount){await this.history(c,null,'ITEM',item.id,'OVERDUE',null,{deadline:item.deadline});await this.notify(c,[...await this.guides(c),...(await c.query('SELECT account_id FROM guidance.recipients WHERE item_id=$1 AND completed_at IS NULL',[item.id])).rows.map(r=>r.account_id)],'مهلت گذشته است: '+item.subject,'OVERDUE','overdue:'+item.id,item.id);}}
 const near=(await c.query("SELECT id,subject FROM guidance.items WHERE deadline>now() AND deadline<=now()+interval '24 hours' AND completed_at IS NULL AND lifecycle='ACTIVE'")).rows;for(const item of near)await this.notify(c,(await c.query('SELECT account_id FROM guidance.recipients WHERE item_id=$1 AND completed_at IS NULL',[item.id])).rows.map(r=>r.account_id),'مهلت نزدیک است: '+item.subject,'DEADLINE','deadline:'+item.id,item.id);
 });}finally{this.running=false;}}
 async dashboard(){await this.automation();return (await this.pool.query(`SELECT
 (SELECT count(*)::int FROM identity.access_requests WHERE status='PENDING_GUIDE_APPROVAL') AS pending_access,
 (SELECT count(*)::int FROM guidance.alerts WHERE closed_at IS NULL) AS alerts,
 (SELECT count(*)::int FROM guidance.items WHERE deadline<now() AND completed_at IS NULL AND lifecycle='ACTIVE' AND kind NOT IN ('COORDINATION','COUNCIL')) AS overdue,
 (SELECT count(DISTINCT i.id)::int FROM guidance.items i JOIN guidance.recipients r ON r.item_id=i.id WHERE i.kind='COORDINATION' AND r.seen_at IS NULL) AS coordination,
 (SELECT count(*)::int FROM guidance.items WHERE kind='COUNCIL' AND review_state='PENDING') AS council`)).rows[0];}
 async alerts(){await this.automation();return {alerts:(await this.pool.query(`SELECT a.*,i.subject,i.lifecycle,i.result FROM guidance.alerts a JOIN guidance.items i ON i.id=a.item_id ORDER BY a.closed_at NULLS FIRST,a.created_at DESC`)).rows};}
 async reports(q:Record<string,string>){
 const from=q.from?str(q.from,10):null,to=q.to?str(q.to,10):null;for(const d of [from,to])if(d&&(!/^\d{4}-\d{2}-\d{2}$/.test(d)||(!Number.isFinite(Date.parse(d))||new Date(d).toISOString().slice(0,10)!==d)))throw new AppError(400,'DATE','تاریخ معتبر نیست.');if(from&&to&&from>to)throw new AppError(400,'DATE','بازه تاریخ معتبر نیست.');
 const person=q.person?id(q.person):null,group=q.group?id(q.group):null,family=q.family?id(q.family):null;
 const params=[q.q??'',from,to,group,person,family,q.status??'',q.kind??''];
 const families=(await this.pool.query(`SELECT f.id,f.family_code,f.status,f.created_at,g.name AS group_name, f.current_group_id,
 (SELECT count(*)::int FROM family.family_memberships m WHERE m.family_id=f.id AND m.valid_to IS NULL) AS members
 FROM family.families f JOIN organization.groups g ON g.id=f.current_group_id WHERE ($1='' OR concat_ws(' ',f.family_code,g.name) ILIKE '%'||$1||'%') AND ($2::date IS NULL OR f.created_at >= $2::date) AND ($3::date IS NULL OR f.created_at < $3::date+interval '1 day') AND ($4::uuid IS NULL OR f.current_group_id=$4) AND ($5::uuid IS NULL OR EXISTS(SELECT 1 FROM family.family_memberships m WHERE m.family_id=f.id AND m.person_id=$5)) AND ($6::uuid IS NULL OR f.id=$6) AND ($7='' OR f.status=$7) AND ($8='' OR $8='FAMILY') ORDER BY f.family_code`,params)).rows;
 const decisions=(await this.pool.query(`${itemSelect} WHERE ($1='' OR concat_ws(' ',i.subject,i.body) ILIKE '%'||$1||'%') AND ($2::date IS NULL OR i.created_at >= $2::date) AND ($3::date IS NULL OR i.created_at < $3::date+interval '1 day') AND ($4::uuid IS NULL OR (i.audience_type='GROUP' AND i.audience_spec @> to_jsonb(ARRAY[$4::text]))) AND ($5::uuid IS NULL OR a.person_id=$5 OR EXISTS(SELECT 1 FROM guidance.recipients r JOIN identity.accounts ac ON ac.id=r.account_id WHERE r.item_id=i.id AND ac.person_id=$5)) AND $6::uuid IS NULL AND ($7='' OR i.review_state=$7 OR i.lifecycle=$7) AND ($8='' OR i.kind=$8) ORDER BY i.created_at DESC`,params)).rows;
 const people=(await this.pool.query(`SELECT p.id,p.first_name,p.last_name,p.mobile,p.created_at FROM identity.people p WHERE ($1='' OR concat_ws(' ',p.first_name,p.last_name,p.mobile,p.national_id) ILIKE '%'||$1||'%') AND ($2::date IS NULL OR p.created_at>=$2::date) AND ($3::date IS NULL OR p.created_at<$3::date+interval '1 day') AND ($4::uuid IS NULL OR EXISTS(SELECT 1 FROM identity.accounts a JOIN identity.role_assignments r ON r.account_id=a.id WHERE a.person_id=p.id AND r.scope_id=$4 AND ${current})) AND ($5::uuid IS NULL OR p.id=$5) AND ($6::uuid IS NULL OR EXISTS(SELECT 1 FROM family.family_memberships m WHERE m.person_id=p.id AND m.family_id=$6)) AND ($7='' OR EXISTS(SELECT 1 FROM identity.accounts a WHERE a.person_id=p.id AND a.status=$7)) AND ($8='' OR $8='PERSON') ORDER BY p.last_name,p.id`,params)).rows;
 return {families,decisions,people,summary:{families:families.length,decisions:decisions.length,people:people.length},availableFilters:['q','from','to','group','person','family','status','kind']};
 }
 async family(familyId:string){id(familyId);const f=(await this.pool.query('SELECT * FROM family.families WHERE id=$1',[familyId])).rows[0];if(!f)throw new AppError(404,'NOT_FOUND','پرونده پیدا نشد.');return {family:f,members:(await this.pool.query('SELECT p.*,m.relationship_code,m.valid_from,m.valid_to FROM family.family_memberships m JOIN identity.people p ON p.id=m.person_id WHERE m.family_id=$1',[familyId])).rows};}
 async sponsor(value:unknown,user:AuthUser){const b=input(value);const title=str(b.title),filters=input(b.filters??{});const q:Record<string,string>={};for(const [k,v] of Object.entries(filters))q[k]=str(v,200,true);const data=await this.reports(q);const showCodes=flag(b.showCodes),showGroups=flag(b.showGroups);const report={title,generatedAt:new Date().toISOString(),families:data.families.map((f,i)=>({row:i+1,...(showCodes?{code:f.family_code}:{}),...(showGroups?{group:f.group_name}:{}),status:f.status,members:f.members})),totals:data.summary.families};await this.tx(user,async c=>this.history(c,user,'REPORT',randomUUID(),'REPORT_EXPORTED',null,{title,filters:q,showCodes,showGroups,count:report.totals}));return report;}
}
