import {useEffect,useRef,useState} from 'react';
import {api,ApiError} from '../api/client';
import {PersianDate} from './PersianDate';
import {digits} from '../pages/vocabulary';
import './Documents.css';
type Row=Record<string,any>;
const uuid=()=>{const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;return [...b].map((v,i)=>([4,6,8,10].includes(i)?'-':'')+v.toString(16).padStart(2,'0')).join('');};
const encode=(file:File)=>new Promise<Row>((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(Error('خواندن فایل ممکن نشد.'));r.onload=()=>resolve({name:file.name,mediaType:file.type||'text/plain',content:String(r.result).split(',')[1]});r.readAsDataURL(file);});
const size=(n:number)=>digits(Math.ceil(Number(n)/1024))+' کیلوبایت';
export function DocumentLink({familyId,document:doc}:{familyId:string;document:Row}){const [open,setOpen]=useState(false);return <><button type="button" className="secondary" onClick={()=>setOpen(true)}>مشاهده {doc.name}</button>{open&&<DocumentViewer familyId={familyId} document={doc} onClose={()=>setOpen(false)}/>}</>;}
export function DocumentTitle({value,options,onChange}:{value:string;options:Row;onChange:(v:string)=>void}){
 const [open,setOpen]=useState(false),[above,setAbove]=useState(false),root=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!open)return;const close=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[open]);
 return <div className="document-title" ref={root} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);root.current?.querySelector('button')?.focus();}else if(open&&['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const options=Array.from(root.current?.querySelectorAll<HTMLButtonElement>('[role=option]')??[]),index=options.indexOf(window.document.activeElement as HTMLButtonElement);options[e.key==='Home'?0:e.key==='End'?options.length-1:(index+(e.key==='ArrowDown'?1:-1)+options.length)%options.length]?.focus();}}}><span id="document-title-label">عنوان مدرک</span><button type="button" className="secondary" aria-labelledby="document-title-label" aria-haspopup="listbox" aria-expanded={open} onClick={()=>{setAbove((root.current?.getBoundingClientRect().bottom??0)>innerHeight-300);setOpen(!open);}}>{options[value]} ▾</button>{open&&<div className={'document-options'+(above?' above':'')} role="listbox" aria-label="عنوان مدرک">{Object.entries(options).map(([key,label])=><button type="button" role="option" aria-selected={key===value} key={key} onClick={()=>{onChange(key);setOpen(false);root.current?.querySelector('button')?.focus();}}>{String(label)}</button>)}</div>}</div>;
}
export function DocumentViewer({familyId,document:doc,onClose}:{familyId:string;document:Row;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[manifest,setManifest]=useState<Row|null>(null),[error,setError]=useState(''),[index,setIndex]=useState(0),[zoom,setZoom]=useState(1);
 useEffect(()=>{dialog.current?.showModal();const focus=window.document.activeElement;return()=>{dialog.current?.close();if(focus instanceof HTMLElement)focus.focus();};},[]);
 useEffect(()=>{let live=true;api('/livelihood/families/'+familyId+'/documents/'+doc.id+'/manifest').then(v=>{if(live)setManifest(v as Row);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[doc.id,familyId]);
 const file=manifest?.files[index],url='/api/v1/livelihood/families/'+familyId+'/documents/'+doc.id+(file?'/files/'+file.id:''),media=file?.media_type??manifest?.media_type;
 return <dialog ref={dialog} className="document-dialog" onCancel={onClose}><header><h2>{doc.name}</h2><button type="button" className="secondary" onClick={onClose}>بستن</button></header>{error&&<p role="alert">{error}</p>}{manifest&&<><div className="document-toolbar">{manifest.files.length>1&&<><button className="secondary" disabled={!index} onClick={()=>{setIndex(index-1);setZoom(1);}}>قبلی</button><span>{digits(index+1)} از {digits(manifest.files.length)}</span><button className="secondary" disabled={index===manifest.files.length-1} onClick={()=>{setIndex(index+1);setZoom(1);}}>بعدی</button></>}{media?.startsWith('image/')&&<><button className="secondary" onClick={()=>setZoom(Math.min(3,zoom+.25))}>بزرگ‌نمایی</button><button className="secondary" onClick={()=>setZoom(Math.max(1,zoom-.25))}>کوچک‌نمایی</button></>}<a href={url} target="_blank" rel="noreferrer">باز کردن فایل</a></div><div className="document-view">{media?.startsWith('image/')?<img alt={file?.original_name??doc.name} src={url} style={{width:zoom*100+'%',maxWidth:'none'}}/>:<iframe title={doc.name} src={url} />}</div></>}</dialog>;
}
export function DocumentPanel({familyId,documents,kinds,editable,onChange}:{familyId:string;documents:Row[];kinds:Row;editable:boolean;onChange:()=>void|Promise<void>}){
 const [rows,setRows]=useState(documents),[category,setCategory]=useState(Object.keys(kinds)[0]??'OTHER'),[name,setName]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[view,setView]=useState<Row|null>(null),[target,setTarget]=useState<Row|null>(null),[manifest,setManifest]=useState<Row|null>(null),[replace,setReplace]=useState(''),[pending,setPending]=useState<Row|null>(null),[selection,setSelection]=useState<File[]>([]),[previews,setPreviews]=useState<{name:string;url:string}[]>([]),[reason,setReason]=useState(''),[archiving,setArchiving]=useState<Row|null>(null);
 const files=useRef<HTMLInputElement>(null),base='/livelihood/families/'+familyId;
 useEffect(()=>{let live=true;if(editable)api<Row[]>(base+'/document-list').then(list=>{if(live)setRows(list);}).catch(e=>{if(live)setMessage(e.message);});else setRows(documents);return()=>{live=false;};},[documents,editable,familyId]);
 useEffect(()=>{const urls=selection.filter(f=>f.type.startsWith('image/')).map(f=>({name:f.name,url:URL.createObjectURL(f)}));setPreviews(urls);return()=>urls.forEach(p=>URL.revokeObjectURL(p.url));},[selection]);
 async function refresh(){const list=await api<Row[]>(base+'/document-list');setRows(list);await onChange();}
 async function send(body:Row){let saved=false;setBusy(true);setMessage('در حال ذخیره روی سامانه…');setPending(body);try{await api(base+'/document-versions',{method:'POST',body:JSON.stringify(body)});saved=true;setPending(null);setSelection([]);setTarget(null);setManifest(null);setReplace('');setName('');await refresh();setMessage('مدرک روی سامانه ذخیره شد. فایل بعدی مدرک جداگانه‌ای خواهد بود.');}catch(e){if(e instanceof ApiError&&e.status<500)setPending(null);setMessage(saved?'مدرک ذخیره شد؛ برای دریافت فهرست، صفحه را تازه کنید.':(e as Error).message+' — فایل هنوز به‌عنوان ذخیره‌شده تأیید نشده است.');}finally{setBusy(false);}}
 async function choose(selected:File[]){if(!selected.length)return;if(category==='OTHER'&&!name.trim()&&!target){setMessage('برای سایر مدارک، عنوان را بنویسید.');return;}setBusy(true);try{if(selected.reduce((sum,f)=>sum+f.size,0)>50*1024*1024)throw Error('مجموع حجم فایل‌های انتخابی باید کمتر از ۵۰ مگابایت باشد.');if(selected.some(f=>f.size>20*1024*1024))throw Error('حداکثر حجم هر فایل ۲۰ مگابایت است.');const encoded=[];for(const f of selected)encoded.push(await encode(f));await send({requestId:uuid(),name:target?.name??(category==='OTHER'?name.trim():kinds[category]),category:target?.category??category,files:encoded,...(target?{documentId:target.id}:{}),...(replace?{replaceFileId:replace}:{})});}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function edit(doc:Row){setTarget(doc);setReplace('');setManifest(null);try{setManifest(await api<Row>(base+'/documents/'+doc.id+'/manifest'));}catch(e){setMessage((e as Error).message);}}
 async function reorder(i:number,delta:number){const order=manifest!.files.map((f:Row)=>f.id);[order[i],order[i+delta]]=[order[i+delta],order[i]];await send({requestId:uuid(),name:target!.name,category:target!.category,documentId:target!.id,files:[],order});}
 return <section className="panel documents-panel"><h2>مدارک پایه و معیشتی</h2><p>ذخیره مدرک مستقل از ارسال ارزیابی است. نسخه ارسالی همراه ارزیابی ثابت می‌ماند.</p><div className="document-cards">{rows.map(d=><article className="document-card" key={d.id}><h3>{d.name}</h3><p>{kinds[d.category]??'مدرک قبلی'} · {({DRAFT:'پیش‌نویس ذخیره‌شده',SUBMITTED:'ارسال‌شده',ARCHIVED:'بایگانی‌شده'} as Row)[d.status]??'نسخه ثبت‌شده'}</p><dl><div><dt>صفحات</dt><dd>{digits(d.page_count??1)}</dd></div><div><dt>حجم اصلی</dt><dd>{d.original_size?size(d.original_size):'—'}</dd></div><div><dt>حجم ذخیره‌شده</dt><dd>{d.stored_size?size(d.stored_size):'—'}</dd></div><div><dt>ثبت‌کننده</dt><dd>{d.creator_name??'—'}</dd></div><div><dt>زمان ثبت</dt><dd><PersianDate value={d.created_at} withTime/></dd></div></dl><div className="document-toolbar"><button type="button" className="secondary" onClick={()=>setView(d)}>مشاهده {d.name}</button>{editable&&!d.archived&&<><button type="button" className="secondary" disabled={busy} onClick={()=>void edit(d)}>مدیریت صفحات</button><button type="button" className="secondary" disabled={busy} onClick={()=>{setArchiving(d);setReason('');}}>بایگانی</button></>}</div></article>)}</div>
 {editable&&<fieldset disabled={busy} className="document-uploader"><legend>{target?'افزودن / جایگزینی صفحات '+target.name:'افزودن مدرک جدید'}</legend>{!target&&<><DocumentTitle value={category} options={kinds} onChange={setCategory}/>{category==='OTHER'&&<label>عنوان سایر مدارک<input aria-label="عنوان سایر مدارک" value={name} maxLength={150} onChange={e=>setName(e.target.value)}/></label>}</>}
 {target&&<><button type="button" className="secondary" onClick={()=>{setTarget(null);setManifest(null);setReplace('');}}>انصراف از مدیریت صفحات</button><p>هر تغییر، نسخه تازه‌ای می‌سازد؛ صفحات نسخه قبلی حفظ می‌شوند.</p>{manifest?.files.map((f:Row,i:number)=><div className="document-toolbar" key={f.id}><span>{digits(i+1)}. {f.original_name}</span><button type="button" className="secondary" disabled={!i} onClick={()=>void reorder(i,-1)}>بالاتر</button><button type="button" className="secondary" disabled={i===manifest.files.length-1} onClick={()=>void reorder(i,1)}>پایین‌تر</button><button type="button" className="secondary" aria-pressed={replace===f.id} onClick={()=>setReplace(replace===f.id?'':f.id)}>جایگزینی این صفحه</button></div>)}<p>{replace?'فایل انتخابی جایگزین صفحه مشخص‌شده می‌شود.':'فایل انتخابی به انتهای مدرک اضافه می‌شود.'}</p></>}

 <input hidden ref={files} type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.txt" multiple={!replace} aria-label="بارگذاری مدرک" onChange={e=>{const list=Array.from(e.target.files??[]);e.target.value='';if(!list.length)return;if(list.some(f=>f.type.startsWith('image/'))){setSelection(list);setMessage('فایل انتخاب شده؛ پس از بررسی پیش‌نمایش، ذخیره را تأیید کنید.');}else {setSelection([]);void choose(list);}}}/>
 <div className="document-toolbar"><button type="button" disabled={!target&&category==='OTHER'&&!name.trim()||!!pending} onClick={()=>files.current?.click()}>انتخاب عکس یا فایل</button></div><small>عکس یا PDF را از گزینه‌های گوشی انتخاب کنید. JPEG، PNG، WebP یا PDF؛ حداکثر هر فایل ۲۰ مگابایت. HEIC فعلاً پشتیبانی نمی‌شود.</small>
 {selection.length>0&&<div className="camera-preview">{previews.map((p,i)=><figure key={p.url}><img src={p.url} alt={'پیش‌نمایش عکس '+digits(i+1)}/><figcaption>{p.name}</figcaption></figure>)}{selection.filter(f=>!f.type.startsWith('image/')).map(f=><p key={f.name}>{f.name}</p>)}<div className="document-toolbar"><button type="button" onClick={()=>void choose(selection)}>تأیید و ذخیره</button><button type="button" className="secondary" onClick={()=>files.current?.click()}>انتخاب مجدد</button><button type="button" className="secondary" onClick={()=>{setSelection([]);setMessage('انتخاب فایل لغو شد؛ مدرکی ذخیره نشد.');}}>انصراف</button></div></div>}
</fieldset>}
 {pending&&!busy&&<div className="document-toolbar"><button type="button" onClick={()=>void send(pending)}>تلاش مجدد برای ذخیره</button><button type="button" className="secondary" onClick={()=>{setPending(null);setSelection([]);void refresh().catch(e=>setMessage(e.message));}}>بررسی فهرست و انتخاب فایل دیگر</button></div>}{message&&<p role="status" aria-live="polite">{message}</p>}
 {archiving&&<div className="document-archive"><label>دلیل بایگانی<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reason.trim()} onClick={async()=>{setBusy(true);try{await api(base+'/documents/'+archiving.id+'/archive',{method:'POST',body:JSON.stringify({reason})});setArchiving(null);await refresh();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>تأیید بایگانی</button><button className="secondary" onClick={()=>setArchiving(null)}>انصراف</button></div>}
 {view&&<DocumentViewer familyId={familyId} document={view} onClose={()=>setView(null)}/>}</section>;
}
