import {Injectable} from '@nestjs/common';
import {PoolClient} from 'pg';
import {createHash} from 'node:crypto';
import {GuidanceService,id,input,str} from '../guidance/guidance.service';
import type {AuthUser} from '../auth/auth.types';
import {AppError} from '../common/app-error';
import {parseExcel,template,normalize} from './excel';
@Injectable()
export class FamilyImportService {
 constructor(private g:GuidanceService){}
 private role(u:AuthUser,write=false){if(!['GROUP_LEADER','EXECUTIVE_MANAGER','SUPREME_GUIDE'].includes(u.effectiveRole??'')||write&&u.effectiveRole==='SUPREME_GUIDE')throw new AppError(403,'ROLE','دسترسی ورود خانواده‌های قبلی برای این نقش مجاز نیست.');}
 private async group(c:PoolClient,groupId:string,u:AuthUser){if(u.effectiveRole!=='GROUP_LEADER'||!u.roles.some(r=>r.roleCode==='GROUP_LEADER'&&r.scopeId===groupId))throw new AppError(403,'SCOPE','فقط گروه تحت مسئولیت سرگروه قابل انتخاب است.');if(!(await c.query("SELECT 1 FROM organization.groups WHERE id=$1 AND status='ACTIVE'",[id(groupId)])).rowCount)throw new AppError(409,'GROUP','گروه فعال نیست.');}
 private async batch(c:PoolClient,batchId:string,u:AuthUser,write=false){this.role(u,write);const b=(await c.query('SELECT * FROM family_import.batches WHERE id=$1 FOR UPDATE',[id(batchId)])).rows[0];if(!b)throw new AppError(404,'NOT_FOUND','Batch پیدا نشد.');if(u.effectiveRole==='GROUP_LEADER')await this.group(c,b.group_id,u);return b;}
 async download(u:AuthUser){if(u.effectiveRole!=='GROUP_LEADER')throw new AppError(403,'ROLE','قالب برای سرگروه مسئول است.');return template();}
 async source(batchId:string,u:AuthUser){return this.g.tx(u,async c=>{const b=await this.batch(c,batchId,u);return {name:b.filename,content:b.file_content};},false);}
 private async duplicate(c:PoolClient,data:any){
  const name=normalize(data.first_name+' '+data.last_name);
  const rows=(await c.query(`SELECT p.national_id,p.mobile,to_char(p.birth_date,'YYYY-MM-DD') AS birth_date,
   regexp_replace(translate(p.first_name||' '||p.last_name,'يك‌','یک '),'\\s+',' ','g') AS name
   FROM identity.people p WHERE ($1::text IS NOT NULL AND p.national_id=$1) OR regexp_replace(translate(p.first_name||' '||p.last_name,'يك‌','یک '),'\\s+',' ','g')=$2`,[data.national_id,name])).rows;
  if(data.national_id&&rows.some(p=>p.national_id===data.national_id))return {classification:'DUPLICATE',reasons:['کد ملی در سامانه وجود دارد؛ ورود مجدد مجاز نیست.']};
  const match=rows.some(p=>p.name===name&&((data.mobile&&normalize(p.mobile??'').replace(/[\s()-]/g,'').replace(/^(\+98|0098)/,'0')===data.mobile)||(data.birth_date&&p.birth_date===data.birth_date)));
  return match?{classification:'SUSPECT',reasons:['نام همراه با شماره تماس یا تاریخ تولد در سامانه موجود است.']}:{classification:'VALID',reasons:[]};
 }
 async upload(groupId:string,value:unknown,u:AuthUser){const b=input(value);if(Object.keys(b).some(k=>!['filename','content'].includes(k)))throw new AppError(400,'INVALID','گروه و سرگروه از Context تعیین می‌شوند.');const filename=str(b.filename,150);if(!/\.xlsx$/i.test(filename)||/[\\/]/.test(filename)||typeof b.content!=='string'||b.content.length>2800000||!/^[A-Za-z0-9+/]+={0,2}$/.test(b.content))throw new AppError(400,'FILE','فایل XLSX حداکثر ۲ مگابایت لازم است.');const bytes=Buffer.from(b.content,'base64');if(!bytes.length||bytes.length>2*1024*1024)throw new AppError(400,'FILE','حجم فایل معتبر نیست.');
  // Authorize before parsing untrusted workbook bytes.
  await this.g.tx(u,c=>this.group(c,groupId,u),false);const parsed=await parseExcel(bytes);
  return this.g.tx(u,async c=>{await this.group(c,groupId,u);
   const batch=(await c.query('INSERT INTO family_import.batches(group_id,uploaded_by,filename,file_content,file_hash,state,errors) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[groupId,u.accountId,filename,bytes,createHash('sha256').update(bytes).digest('hex'),parsed.errors.length?'INVALID':'PREVIEW',JSON.stringify(parsed.errors)])).rows[0];
   await this.g.history(c,u,'IMPORT_BATCH',batch.id,'IMPORT_UPLOADED',null,{filename,groupId,bytes:bytes.length});
   for(const row of parsed.rows){const d=row.data;let classification=row.empty?'EMPTY':row.errors.length?'ERROR':'VALID',reasons:string[]=[];
    if(classification==='VALID'){
     const others=parsed.rows.filter(other=>other!==row&&!other.empty&&!other.errors.length);
     if(d.national_id&&others.some(x=>x.data.national_id===d.national_id)){classification='DUPLICATE';reasons.push('کد ملی در چند ردیف همین فایل تکرار شده است.');}
     else if(others.some(x=>normalize(x.data.first_name+' '+x.data.last_name)===normalize(d.first_name+' '+d.last_name)&&((d.mobile&&x.data.mobile===d.mobile)||(d.birth_date&&x.data.birth_date===d.birth_date)))){classification='SUSPECT';reasons.push('نام همراه با شماره تماس یا تاریخ تولد در همین فایل تکرار شده است.');}
     const db=await this.duplicate(c,d);if(db.classification==='DUPLICATE'||classification==='VALID')classification=db.classification;reasons.push(...db.reasons);
    }
    await c.query('INSERT INTO family_import.rows(batch_id,sheet,row_number,data,errors,classification,duplicate_reasons) VALUES($1,$2,$3,$4,$5,$6,$7)',[batch.id,row.sheet,row.row,JSON.stringify(d),JSON.stringify(row.errors),classification,JSON.stringify(reasons)]);
   }
   await this.g.history(c,u,'IMPORT_BATCH',batch.id,'IMPORT_VALIDATED',null,{errors:parsed.errors,rows:parsed.rows.length});return batch;
  },false);
 }
 async preview(batchId:string,u:AuthUser){return this.g.tx(u,async c=>{const b=await this.batch(c,batchId,u);const rows=(await c.query('SELECT r.*,f.family_code,f.status AS family_status,i.members_confirmed_at,i.activity_at FROM family_import.rows r LEFT JOIN family.families f ON f.id=r.family_id LEFT JOIN family_import.families i ON i.family_id=f.id WHERE r.batch_id=$1 ORDER BY row_number',[batchId])).rows;const {file_content,...batch}=b;
  const count=(test:(r:any)=>boolean)=>rows.filter(test).length;
  const summary={total:rows.length,valid:count(r=>r.classification==='VALID'),failed:count(r=>r.classification==='ERROR'),suspect:count(r=>r.classification==='SUSPECT'),duplicate:count(r=>r.classification==='DUPLICATE'),success:count(r=>r.family_id),skipped:count(r=>r.decision==='SKIP'),importable:count(r=>r.classification==='VALID'&&r.decision!=='SKIP'||r.classification==='SUSPECT'&&r.decision==='IMPORT')};
  if(u.effectiveRole==='GROUP_LEADER'&&b.state==='PREVIEW')await this.g.history(c,u,'IMPORT_BATCH',batchId,'IMPORT_PREVIEWED',null,{version:b.version});
  const history=(await c.query("SELECT h.id,h.action,h.reason,h.occurred_at,p.first_name||' '||p.last_name AS actor_name FROM guidance.history h LEFT JOIN identity.accounts a ON a.id=h.actor_id LEFT JOIN identity.people p ON p.id=a.person_id WHERE entity_type='IMPORT_BATCH' AND entity_id=$1 ORDER BY occurred_at DESC",[batchId])).rows;
  return {batch,rows,summary,history,canConfirm:u.effectiveRole==='GROUP_LEADER'&&b.state==='PREVIEW',canResolve:u.effectiveRole!=='SUPREME_GUIDE'&&b.state==='PREVIEW',canRollback:u.effectiveRole==='EXECUTIVE_MANAGER'&&b.state==='IMPORTED'&&!rows.some(r=>r.activity_at)};
 },false);}
 async resolve(batchId:string,rowId:string,value:unknown,u:AuthUser){const b=input(value),reason=str(b.reason,2000);if(!['IMPORT','SKIP'].includes(String(b.decision))||Object.keys(b).some(k=>!['version','decision','reason'].includes(k)))throw new AppError(400,'INVALID','تصمیم و دلیل معتبر لازم است.');return this.g.tx(u,async c=>{const batch=await this.batch(c,batchId,u,true);if(batch.state!=='PREVIEW'||batch.version!==b.version)throw new AppError(409,'STALE','پیش‌نمایش تغییر کرده است.');const row=(await c.query('SELECT * FROM family_import.rows WHERE batch_id=$1 AND id=$2',[batchId,id(rowId)])).rows[0];if(!row||!['SUSPECT','DUPLICATE'].includes(row.classification)||row.classification==='DUPLICATE'&&b.decision==='IMPORT')throw new AppError(409,'DUPLICATE','تکراری قطعی قابل ورود نیست؛ مورد مشکوک نیازمند تصمیم صریح است.');await c.query('UPDATE family_import.rows SET decision=$2,decision_reason=$3,decided_by=$4,decided_at=now() WHERE id=$1',[rowId,b.decision,reason,u.accountId]);await c.query('UPDATE family_import.batches SET version=version+1 WHERE id=$1',[batchId]);await this.g.history(c,u,'IMPORT_BATCH',batchId,'IMPORT_DUPLICATE_DECIDED',row,{rowId,decision:b.decision},reason);return {ok:true};},false);}
 async confirm(batchId:string,value:unknown,u:AuthUser){const b=input(value);if(u.effectiveRole!=='GROUP_LEADER')throw new AppError(403,'ROLE','تأیید ورود در اختیار سرگروه مسئول است.');if(Object.keys(b).some(k=>!['version','rowIds'].includes(k))||!Array.isArray(b.rowIds)||!b.rowIds.length||b.rowIds.length>3000)throw new AppError(400,'ROWS','ردیف‌های معتبر پیش‌نمایش را انتخاب کنید.');const selected=new Set(b.rowIds.map(id));
  try{return await this.g.tx(u,async c=>{const batch=await this.batch(c,batchId,u,true);if(batch.state!=='PREVIEW'||batch.version!==b.version)throw new AppError(409,'STALE','Batch قبلاً وارد شده یا پیش‌نمایش تغییر کرده است.');if(!(await c.query("SELECT 1 FROM guidance.history WHERE entity_type='IMPORT_BATCH' AND entity_id=$1 AND actor_id=$2 AND action='IMPORT_PREVIEWED' AND new_state->>'version'=$3 LIMIT 1",[batchId,u.accountId,String(batch.version)])).rowCount)throw new AppError(409,'PREVIEW','ابتدا پیش‌نمایش نسخه جاری را مشاهده کنید.');const rows=(await c.query('SELECT * FROM family_import.rows WHERE batch_id=$1 ORDER BY row_number',[batchId])).rows;
   if([...selected].some(key=>!rows.some(r=>r.id===key)))throw new AppError(400,'ROWS','ردیف متعلق به این Batch نیست.');
   for(const r of rows){if(!selected.has(r.id))continue;if(r.classification!=='VALID'&&!(r.classification==='SUSPECT'&&r.decision==='IMPORT')||r.decision==='SKIP')throw new AppError(409,'ROWS','ردیف خطادار، تکراری یا حل‌نشده قابل ورود نیست.');const check=await this.duplicate(c,r.data);if(check.classification==='DUPLICATE'||check.classification==='SUSPECT'&&r.decision!=='IMPORT')throw new AppError(409,'DUPLICATE','از زمان پیش‌نمایش، مورد تکراری جدید پیدا شد؛ فایل را مجدداً بررسی کنید.');
    const d=r.data,p=(await c.query('INSERT INTO identity.people(first_name,last_name,national_id,mobile,sex,birth_date) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[d.first_name,d.last_name,d.national_id,d.mobile,d.sex,d.birth_date])).rows[0];
    const f=(await c.query("INSERT INTO family.families(family_code,status,current_group_id,created_by) VALUES('HL-'||lpad(nextval('family.family_code_seq')::text,8,'0'),'NEEDS_CLASSIFICATION',$1,$2) RETURNING *",[batch.group_id,u.accountId])).rows[0];
    await c.query("INSERT INTO family.family_memberships(family_id,person_id,relationship_code) VALUES($1,$2,'HEAD')",[f.id,p.id]);await c.query('INSERT INTO family.head_history(family_id,person_id) VALUES($1,$2)',[f.id,p.id]);
    await c.query("UPDATE family_import.rows SET family_id=$2,decision='IMPORT',decided_by=COALESCE(decided_by,$3),decided_at=COALESCE(decided_at,now()) WHERE id=$1",[r.id,f.id,u.accountId]);await c.query('INSERT INTO family_import.families(family_id,batch_id,row_id) VALUES($1,$2,$3)',[f.id,batchId,r.id]);await this.g.history(c,u,'FAMILY',f.id,'IMPORT_FAMILY_CREATED',null,{batchId,row:r.row_number,status:f.status});
   }
   await c.query("UPDATE family_import.rows SET decision='SKIP',decided_by=COALESCE(decided_by,$2),decided_at=COALESCE(decided_at,now()) WHERE batch_id=$1 AND family_id IS NULL",[batchId,u.accountId]);
   await c.query("UPDATE family_import.batches SET state='IMPORTED',confirmed_at=now(),confirmed_by=$2,version=version+1 WHERE id=$1",[batchId,u.accountId]);await this.g.history(c,u,'IMPORT_BATCH',batchId,'IMPORT_CONFIRMED',null,{imported:selected.size,skipped:rows.length-selected.size});return {imported:selected.size};
  },false);}catch(error){await this.g.tx(u,async c=>{await this.batch(c,batchId,u,true);await this.g.history(c,u,'IMPORT_BATCH',batchId,'IMPORT_CONFIRM_FAILED',null,{code:error instanceof AppError?error.code:'ERROR'});},false);throw error;}
 }
 async familyState(familyId:string,value:unknown,u:AuthUser){const b=input(value);if(Object.keys(b).some(k=>!['version','action'].includes(k))||!['ACTIVE','INACTIVE','MEMBERS_COMPLETE'].includes(String(b.action)))throw new AppError(400,'ACTION','اقدام معتبر نیست.');return this.g.tx(u,async c=>{const row=(await c.query('SELECT f.*,i.batch_id,i.members_confirmed_at,b.state AS batch_state FROM family.families f JOIN family_import.families i ON i.family_id=f.id JOIN family_import.batches b ON b.id=i.batch_id WHERE f.id=$1 FOR UPDATE OF f,i',[id(familyId)])).rows[0];if(!row)throw new AppError(404,'NOT_FOUND','پرونده واردشده پیدا نشد.');await this.group(c,row.current_group_id,u);if(row.batch_state!=='IMPORTED'||row.version!==b.version)throw new AppError(409,'STALE','پرونده تغییر کرده یا Batch باطل شده است.');
  if(b.action==='MEMBERS_COMPLETE'){if(row.status!=='ACTIVE')throw new AppError(409,'STATE','ابتدا خانواده را فعال کنید.');await c.query('UPDATE family_import.families SET members_confirmed_at=now(),members_confirmed_by=$2 WHERE family_id=$1',[familyId,u.accountId]);await c.query('UPDATE family.families SET version=version+1,updated_at=now() WHERE id=$1',[familyId]);}
  else{const state=b.action==='ACTIVE'?'ACTIVE':'TEMPORARILY_INACTIVE';await c.query('UPDATE family.families SET status=$2,version=version+1,updated_at=now() WHERE id=$1',[familyId,state]);}
  await this.g.history(c,u,'FAMILY',familyId,'IMPORT_'+b.action,row,{action:b.action});await this.g.history(c,u,'IMPORT_BATCH',row.batch_id,'IMPORT_FAMILY_CLASSIFIED',null,{familyId,action:b.action});return {ok:true};
 },false);}
 async rollback(batchId:string,value:unknown,u:AuthUser){const b=input(value),reason=str(b.reason,2000);if(u.effectiveRole!=='EXECUTIVE_MANAGER')throw new AppError(403,'ROLE','ابطال Batch فقط در اختیار مدیر اجرایی است.');if(Object.keys(b).some(k=>!['version','reason'].includes(k)))throw new AppError(400,'INVALID','درخواست معتبر نیست.');return this.g.tx(u,async c=>{const batch=await this.batch(c,batchId,u,true);if(batch.state!=='IMPORTED'||batch.version!==b.version)throw new AppError(409,'STALE','Batch تغییر کرده است.');const rows=(await c.query('SELECT * FROM family_import.families WHERE batch_id=$1 FOR UPDATE',[batchId])).rows;if(rows.some(r=>r.activity_at))throw new AppError(409,'ACTIVITY','ابطال مجاز نیست؛ روی حداقل یک پرونده ویرایش یا فعالیت عملیاتی ثبت شده است.');for(const r of rows){await c.query("UPDATE family.families SET status='CLOSED',version=version+1,updated_at=now() WHERE id=$1",[r.family_id]);await this.g.history(c,u,'FAMILY',r.family_id,'IMPORT_VOIDED',null,{batchId},reason);}await c.query("UPDATE family_import.batches SET state='VOID',version=version+1,voided_at=now(),voided_by=$2,void_reason=$3 WHERE id=$1",[batchId,u.accountId,reason]);await this.g.history(c,u,'IMPORT_BATCH',batchId,'IMPORT_VOIDED',null,{families:rows.length},reason);return {ok:true};},false);}
 async dashboard(u:AuthUser){return this.g.tx(u,async c=>{this.role(u);const scoped=u.effectiveRole==='GROUP_LEADER',groups=u.roles.filter(r=>r.roleCode==='GROUP_LEADER').map(r=>r.scopeId);
  const batches=(await c.query('SELECT b.id,b.group_id,g.name AS group_name,b.filename,b.state,b.created_at,b.version,jsonb_array_length(b.errors) AS file_errors,(SELECT count(*)::int FROM family_import.rows r WHERE r.batch_id=b.id AND r.classification=\'ERROR\') AS row_errors,(SELECT count(*)::int FROM family_import.rows r WHERE r.batch_id=b.id AND r.classification IN(\'SUSPECT\',\'DUPLICATE\') AND r.decision IS NULL) AS unresolved FROM family_import.batches b JOIN organization.groups g ON g.id=b.group_id WHERE NOT $1::boolean OR b.group_id=ANY($2::uuid[]) ORDER BY b.created_at DESC',[scoped,groups])).rows;
  const families=(await c.query(`SELECT f.id,f.family_code,f.status,f.version,i.batch_id,i.members_confirmed_at,b.state AS batch_state,p.first_name||' '||p.last_name AS head_name,
   EXISTS(SELECT 1 FROM assessment.domain_reviews WHERE family_id=f.id UNION ALL SELECT 1 FROM assessment.health_reviews WHERE family_id=f.id UNION ALL SELECT 1 FROM assessment.snapshots WHERE family_id=f.id) AS has_assessment
   FROM family_import.families i JOIN family.families f ON f.id=i.family_id JOIN family_import.batches b ON b.id=i.batch_id JOIN family.head_history h ON h.family_id=f.id AND h.valid_to IS NULL JOIN identity.people p ON p.id=h.person_id WHERE NOT $1::boolean OR f.current_group_id=ANY($2::uuid[]) ORDER BY f.family_code`,[scoped,groups])).rows;
  const live=families.filter(f=>f.batch_state!=='VOID'),count=(fn:(f:any)=>boolean)=>live.filter(fn).length;
  return {batches,families,groups:(await c.query("SELECT id,name FROM organization.groups WHERE status='ACTIVE' AND (NOT $1::boolean OR id=ANY($2::uuid[])) ORDER BY name",[scoped,groups])).rows,summary:{total:live.length,needsClassification:count(f=>f.status==='NEEDS_CLASSIFICATION'),active:count(f=>f.status==='ACTIVE'),inactive:count(f=>f.status==='TEMPORARILY_INACTIVE'),needsMembers:count(f=>f.status==='ACTIVE'&&!f.members_confirmed_at),needsAssessment:count(f=>f.status==='ACTIVE'&&!f.has_assessment),hasAssessment:count(f=>f.has_assessment),errorBatches:batches.filter(b=>b.file_errors||b.row_errors).length,unresolved:batches.reduce((sum,b)=>sum+b.unresolved,0)}};
 },false);}
}
