import {useEffect,useRef,useState} from 'react';
import {Link,NavLink,useLocation,useNavigate,useParams,useSearchParams} from 'react-router-dom';
import {api} from '../api/client';
import {Screen,Field,useData} from './GuideWorkspace';
import {PersianDate} from '../components/PersianDate';
import {DocumentPanel,DocumentLink} from '../components/Documents';
import {digits} from './vocabulary';
import './ComprehensiveAssessment.css';
type Row=Record<string,any>;
const kinds={NATIONAL_CARD:'تصویر کارت ملی سرپرست',FAMILY_BOOK:'صفحات شناسنامه خانواده',INCOME:'درآمد',DEBT:'بدهی',EXPENSE:'هزینه',OTHER:'سایر'};
const severity:Row={ATTENTION:'نیازمند توجه',URGENT:'فوری',CRITICAL:'بحرانی',IMPORTANT:'نیازمند توجه',VERY_IMPORTANT:'فوری'};
const visible=(q:Row,v:Row)=>!q.when||q.when.values?.includes(String(v[q.when.field]??''))||q.when.not&&!q.when.not.includes(String(v[q.when.field]??''))||q.when.includes&&Array.isArray(v[q.when.field])&&v[q.when.field].includes(q.when.includes);
function Questions({questions,values,onChange,editing,domain,members,memberId,messages=[]}:{questions:Row[];values:Row;onChange:(k:string,v:any)=>void;editing:boolean;domain:string;members:Row[];memberId?:string;messages?:Row[]}){
 return <div className="assessment-questions">{questions.filter(q=>visible(q,values)).map(q=>{
 const target=domain+'-'+(memberId?memberId+'-':'')+q.key,value=values[q.key];
 const options=q.type==='members'?members.map(m=>({value:m.id,label:m.first_name+' '+m.last_name})):q.options??[];
 const show=(v:any)=>options.find((o:Row)=>o.value===v)?.label??(v===true?'بله':v===false?'خیر':v??'ثبت نشده');
 return <div className="assessment-question" id={target} key={q.key} tabIndex={-1}><Field label={q.label}>
 {!editing||q.locked?<p>{Array.isArray(value)?value.map(show).join('، ')||'ثبت نشده':show(value)}</p>:q.type==='text'?<textarea value={value??''} maxLength={2000} onChange={e=>onChange(q.key,e.target.value)}/>:q.multiple?<div className="assessment-options">{options.map((o:Row)=><label key={o.value}><input type="checkbox" checked={Array.isArray(value)&&value.includes(o.value)} onChange={e=>onChange(q.key,e.target.checked?[...(Array.isArray(value)?value:[]),o.value]:(value??[]).filter((x:string)=>x!==o.value))}/>{o.label}</label>)}</div>:<select value={q.type==='boolean'?(value===true?'YES':value===false?'NO':''):value??''} onChange={e=>onChange(q.key,q.type==='boolean'?(e.target.value===''?undefined:e.target.value==='YES'):e.target.value)}><option value="">انتخاب کنید</option>{options.map((o:Row)=><option key={o.value} value={o.value}>{o.label}</option>)}</select>}
 </Field>{messages.filter(m=>m.target===target).map((m,i)=><p role="note" key={i}>{m.reason}</p>)}{(value==='OTHER'||Array.isArray(value)&&value.includes('OTHER'))&&<div id={target+'Other'}><Field label="توضیح کوتاه سایر">{editing?<input maxLength={300} value={values[q.key+'Other']??''} onChange={e=>onChange(q.key+'Other',e.target.value)}/>:<p>{values[q.key+'Other']??'ثبت نشده'}</p>}</Field></div>}</div>;
 })}</div>;
}
export function ComprehensiveAssessment(){
 const {id='',section='review'}=useParams(),[params]=useSearchParams(),location=useLocation(),navigate=useNavigate();
 const [data,setData]=useState<Row|null>(null),[payload,setPayload]=useState<Row>({answers:{},evidence:[],notes:''}),[result,setResult]=useState<Row|null>(null);
 const [editing,setEditing]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [reviewed,setReviewed]=useState<string[]>([]);
 const [comments,setComments]=useState<Row[]>([{domain:'livelihood',field:'',reason:''}]);const previewSeq=useRef(0);
 const base='/shared/families/'+id+'/comprehensive',path='/workspace/families/'+id+'/assessment/';
 async function load(){const next=await api<Row>(base);setData(next);setReviewed(next.assessment.reviewedDomains);setPayload(next.payload);setResult(next.result);return next;}
 useEffect(()=>{setData(null);setEditing(false);void load().catch(e=>setError(e.message));},[id]);
 const chosen=data?.versions.find((s:Row)=>s.id===params.get('version'));
 const latest=data?.versions.find((v:Row)=>v.model_id===data.assessment.modelId),snapshot=chosen??(!editing&&!data?.draft&&latest&&(!latest.decision||latest.decision==='APPROVED'&&!params.has('new'))?latest:undefined);
 const shown=snapshot?{answers:snapshot.answers,evidence:snapshot.evidence.map((d:Row)=>d.id),notes:snapshot.result.notes}:payload;
 const computed=snapshot?snapshot.result:result;
 useEffect(()=>{
  if(!editing)return;const seq=++previewSeq.current;
  const timer=setTimeout(()=>{void api<Row>(base+'/preview',{method:'POST',body:JSON.stringify(payload)}).then(r=>{if(seq===previewSeq.current)setResult(r);}).catch(e=>{if(seq===previewSeq.current)setError(e.message);});},250);
  return()=>{clearTimeout(timer);previewSeq.current++;};
 },[payload,editing,base]);
 useEffect(()=>{if(!data||!location.hash)return;const timer=setTimeout(()=>{const el=document.getElementById(decodeURIComponent(location.hash.slice(1)));el?.scrollIntoView({block:'center',behavior:'smooth'});el?.focus({preventScroll:true});},50);return()=>clearTimeout(timer);},[location.hash,section,data]);
 const update=(domain:string,k:string,v:any)=>setPayload(p=>({...p,answers:{...p.answers,[domain]:{...p.answers[domain],[k]:v}}}));
 const updateMember=(domain:string,memberId:string,k:string,v:any)=>setPayload(p=>{
  const old=p.answers[domain]??{},rows=old.members??[],exists=rows.some((m:Row)=>m.memberId===memberId);
  return {...p,answers:{...p.answers,[domain]:{...old,members:exists?rows.map((m:Row)=>m.memberId===memberId?{...m,[k]:v}:m):[...rows,{memberId,[k]:v}]}}};
 });
 async function action(fn:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(){await action(async()=>{await api(base+'/save',{method:'POST',body:JSON.stringify({version:data?.draft?.version??null,payload,reviewedDomains:reviewed})});await load();setEditing(false);setMessage('تغییرات ارزیابی ذخیره شد.');});}
 const jump=(domain:string,target:string)=>path+(target==='review-documents'?'review':domain)+(snapshot?'?version='+snapshot.id:'')+'#'+target;
 return <Screen title="ارزیابی جامع خانواده" error={error} loading={!data}>{data&&<>
 <nav aria-label="breadcrumb"><Link to="/workspace/families">خانواده‌ها</Link> ← <Link to={'/workspace/families/'+id}>پرونده خانواده</Link> ← <Link to={path+'review'}>ارزیابی جامع</Link> ← {data.labels[section]??'مرور نهایی'}</nav>
 <header className="panel"><h2>{data.members.find((m:Row)=>m.relationship_code==='HEAD')?.first_name} {data.members.find((m:Row)=>m.relationship_code==='HEAD')?.last_name}</h2><p><bdi>{data.family.code??data.family.family_code}</bdi></p>
 {snapshot&&<p>زمان ارسال: <PersianDate value={snapshot.created_at} withTime/></p>}<p role="status">{snapshot?'مشاهده نسخه تاریخی / ارسالی':editing?'حالت ویرایش ارزیابی':'حالت مشاهده ارزیابی'} · {snapshot?.decision==='APPROVED'?'تأییدشده':snapshot?.decision==='RETURNED'?'بازگشت‌شده':snapshot?'ارسال‌شده؛ هنوز تأیید نشده':latest?.decision==='RETURNED'?'بازگشت برای اصلاح':data.draft?'پیش‌نویس در حال تکمیل':'ارزیابی جدید'}</p>
 {data.canEdit&&snapshot?.decision==='APPROVED'&&<button onClick={()=>{navigate(path+section+'?new=1');setEditing(true);}}>شروع ارزیابی جامع جدید با حفظ نسخه تأییدشده</button>}{data.canEdit&&!snapshot&&!editing&&<button onClick={()=>setEditing(true)}>{data.draft||latest?.decision==='RETURNED'?'ادامه ارزیابی در حال تکمیل':'شروع ارزیابی جامع جدید'}</button>}
 {editing&&<div className="action-row"><button disabled={busy} onClick={()=>void save()}>ذخیره تغییرات ارزیابی</button><button disabled={busy} className="secondary" onClick={()=>{setPayload(data.payload);setResult(data.result);setEditing(false);}}>انصراف از ویرایش</button></div>}
 <Field label="نسخه ارزیابی"><select value={chosen?.id??''} onChange={e=>{setEditing(false);navigate(path+section+(e.target.value?'?version='+e.target.value:''));}}><option value="">نسخه جاری</option>{data.versions.map((v:Row)=><option key={v.id} value={v.id}>نسخه {digits(v.revision)} · {v.decision==='APPROVED'?'تأییدشده':v.decision==='RETURNED'?'بازگشت‌شده':'ارسالی'}</option>)}</select></Field>
 {data.family.status&&data.family.status!=='ACTIVE'&&<p role="note">خانواده اکنون غیرفعال است؛ نسخه ارسالی همچنان قابل بررسی است.</p>}
 {data.assessment.warning&&<p role="alert">{data.assessment.warning}</p>}
 </header>
 <nav className="subnav comprehensive-nav" aria-label="حوزه‌های ارزیابی جامع"><Link to={'/workspace/families/'+id}>اطلاعات پایه</Link>{Object.entries(data.labels).map(([domain,label])=><NavLink key={domain} to={path+domain+(chosen?'?version='+chosen.id:'')}>{String(label)} <small>{domain==='education'&&computed?.educationApplicability.state==='NOT_APPLICABLE'?'N/A':computed?.missing.some((m:Row)=>m.domain===domain)?'…':'✓'}</small></NavLink>)}<NavLink to={path+'review'+(chosen?'?version='+chosen.id:'')}>مرور نهایی</NavLink></nav>
 {latest?.decision==='RETURNED'&&!snapshot&&<section className="panel"><h2>موارد بازگشت برای اصلاح</h2>{latest.comments.map((c:Row,i:number)=><p key={i}><Link to={jump(c.domain,c.target)}>{data.labels[c.domain]}: {c.reason}</Link></p>)}</section>}
 {section!=='review'&&data.labels[section]&&<section className="panel" id={section} tabIndex={-1}><h2>{data.labels[section]}</h2>
 {section==='education'&&computed?.educationApplicability.state==='NOT_APPLICABLE'?<p>آموزش: N/A — عضو مشمول تحصیل وجود ندارد؛ امتیاز null و خارج از سقف قابل اعمال.</p>:<>
 {['health','education'].includes(section)&&(snapshot?.members??data.members).filter((m:Row)=>section==='health'||computed?.educationApplicability.eligibleMemberIds.includes(m.id)).map((m:Row)=><fieldset key={m.id}><legend>{m.first_name} {m.last_name}</legend><Questions domain={section} memberId={m.id} messages={[...(computed?.alerts??[]),...(!snapshot&&latest?.decision==='RETURNED'?latest.comments:[])]} questions={data.fields[section+'Member']} values={(shown.answers[section]?.members??[]).find((r:Row)=>r.memberId===m.id)??{}} onChange={(k,v)=>updateMember(section,m.id,k,v)} editing={editing&&!snapshot&&!busy} members={snapshot?.members??data.members}/></fieldset>)}
 {section==='education'&&computed?.educationApplicability.unknownMemberIds.map((memberId:string)=><p id={'education-'+memberId+'-applicability'} key={memberId}>مشمولیت تحصیل نامشخص است. <Link to={'/workspace/families/'+id}>تکمیل اطلاعات پایه عضو</Link></p>)}
 {(section!=='health'||(shown.answers.health?.members??[]).some((m:Row)=>m.screening==='YES'))&&<Questions messages={[...(computed?.alerts??[]),...(!snapshot&&latest?.decision==='RETURNED'?latest.comments:[])]} questions={(data.fields[section]??[]).map((q:Row)=>section==='housing'&&q.key==='residenceType'&&data.family.residenceType?{...q,locked:true}:q)} domain={section} values={shown.answers[section]??{}} onChange={(k,v)=>update(section,k,v)} editing={editing&&!snapshot&&!busy} members={snapshot?.members??data.members}/>}
 </>}
 {data.assessment.requiresReview&&!snapshot&&<label className="check-field"><input type="checkbox" disabled={!editing} checked={reviewed.includes(section)} onChange={e=>setReviewed(r=>e.target.checked?[...new Set([...r,section])]:r.filter(d=>d!==section))}/>بازنگری این حوزه با مدل جاری انجام شد</label>}
 <p>امتیاز حوزه: {computed?.domainRawScores[section]===null?'نامشخص / N/A':digits(computed?.domainRawScores[section])} / {digits(data.maximums[section])}</p>
 </section>}
 {section==='review'&&computed&&<>
 <section className="panel"><h2>مرور نهایی ارزیابی خانواده</h2><div className="assessment-score-grid">{Object.entries(data.labels).map(([d,label])=><article key={d}><h3>{String(label)}</h3><p>{d==='education'&&computed.educationApplicability.state==='NOT_APPLICABLE'?'N/A':computed.domainRawScores[d]===null?'نامشخص':digits(computed.domainRawScores[d])+' / '+digits(data.maximums[d])}</p><Link to={path+d+(chosen?'?version='+chosen.id:'')}>مشاهده/ویرایش</Link><dl>{computed.summaryLines?.[d]?.items.filter((i:Row)=>i.value!==null&&i.value!=='').map((i:Row)=><div key={i.field}><dt>{i.label}</dt><dd>{String(i.value)}</dd></div>)}</dl>
 {d==='health'&&<p>اعضای فعال: {digits(computed.summaries.health.activeMembers)} · دارای مسئله: {digits(computed.summaries.health.affectedMembers)} · شدیدترین اثر: {digits(computed.summaries.health.maxFunctionalImpact)} · شکاف درمان: {digits(computed.summaries.health.maxTreatmentGap)}</p>}
 {d==='education'&&<p>مشمول: {digits(computed.summaries.education.eligibleMembers)} · دارای مشکل: {digits(computed.summaries.education.affectedMembers)}</p>}
 </article>)}</div><p>جمع خام: {digits(computed.rawTotal??'—')} / سقف قابل اعمال: {digits(computed.applicableMaximum)}</p><p data-testid="normalized-score">امتیاز نهایی: {computed.normalizedScore===null?'نامشخص':digits(Number(computed.normalizedScore.toFixed(2)))+' / ۱۰۰'} · سطح نیاز {computed.needLevel??'نامشخص'}</p><p>سطح نیاز مستقل از فوریت هشدارهاست.</p></section>
 {computed.missing.length>0&&<section className="panel"><h2>موارد نیازمند تکمیل</h2>{computed.missing.map((m:Row,i:number)=><p key={i}><Link to={jump(m.domain,m.target)}>{data.labels[m.domain]} — {m.reason}</Link></p>)}</section>}
 <section className="panel" id="review-documents" tabIndex={-1}><h2>مدارک مرتبط</h2>{snapshot?snapshot.evidence.map((d:Row)=><DocumentLink key={d.id} familyId={id} document={d}/>):<>{data.documents.map((d:Row)=><label className="check-field" key={d.id}><input type="checkbox" disabled={!editing} checked={shown.evidence?.includes(d.id)||['NATIONAL_CARD','FAMILY_BOOK'].includes(d.category)} onChange={e=>setPayload(p=>({...p,evidence:e.target.checked?[...p.evidence,d.id]:p.evidence.filter((x:string)=>x!==d.id)}))}/>{d.name}</label>)}<DocumentPanel familyId={id} documents={data.documents} kinds={kinds} editable={data.canEdit} onChange={async()=>{const next=await api<Row>(base);setData(next);}}/></>}</section>
 <section className="panel"><Field label="توضیح نهایی سرگروه (اختیاری)">{editing?<textarea value={payload.notes??''} maxLength={4000} onChange={e=>setPayload(p=>({...p,notes:e.target.value}))}/>:<p>{shown.notes||'—'}</p>}</Field>
 {data.canEdit&&!snapshot&&<><p>{editing?'ابتدا تغییرات را ذخیره کنید.':'ارسال، کل پنج حوزه را در یک نسخه تاریخی قفل می‌کند.'}</p><button disabled={busy||editing||!data.draft||!computed.complete||data.assessment.remainingDomains.length>0} onClick={()=>void action(async()=>{await api(base+'/submit',{method:'POST',body:JSON.stringify({draftId:data.draft.id,version:data.draft.version})});await load();setMessage('کل ارزیابی برای مدیر اجرایی ارسال شد.');})}>ارسال ارزیابی برای مدیر اجرایی</button></>}
 {data.canReview&&snapshot&&!snapshot.decision&&snapshot.model_id===data.assessment.modelId&&<><h2>تصمیم مدیر اجرایی</h2>{comments.map((c,i)=><fieldset key={i}><legend>توضیح بازگشت {digits(i+1)}</legend><Field label="حوزه"><select value={c.domain} onChange={e=>setComments(v=>v.map((x,j)=>j===i?{...x,domain:e.target.value,field:'',memberId:''}:x))}>{Object.entries(data.labels).map(([k,l])=><option key={k} value={k}>{String(l)}</option>)}</select></Field><Field label="بخش / سؤال"><select value={c.field} onChange={e=>setComments(v=>v.map((x,j)=>j===i?{...x,field:e.target.value}:x))}><option value="">کل حوزه</option>{[...(data.fields[c.domain]??[]),...(data.fields[c.domain+'Member']??[])].map((q:Row)=><option value={q.key} key={q.key}>{q.label}</option>)}</select></Field>{['health','education'].includes(c.domain)&&<Field label="عضو مرتبط"><select value={c.memberId??''} onChange={e=>setComments(v=>v.map((x,j)=>j===i?{...x,memberId:e.target.value}:x))}><option value="">حوزه خانواده</option>{snapshot.members.map((m:Row)=><option key={m.id} value={m.id}>{m.first_name} {m.last_name}</option>)}</select></Field>}<Field label="علت اصلاح"><textarea value={c.reason} onChange={e=>setComments(v=>v.map((x,j)=>j===i?{...x,reason:e.target.value}:x))}/></Field></fieldset>)}
 <div className="action-row"><button className="secondary" onClick={()=>setComments(v=>[...v,{domain:'livelihood',field:'',reason:''}])}>افزودن توضیح بازگشت</button><button disabled={busy} onClick={()=>void action(async()=>{await api(base+'/decision',{method:'POST',body:JSON.stringify({snapshotId:snapshot.id,decision:'RETURNED',comments})});await load();setMessage('کل ارزیابی برای اصلاح بازگشت داده شد.');})}>بازگشت کل ارزیابی برای اصلاح</button><button disabled={busy} onClick={()=>void action(async()=>{await api(base+'/decision',{method:'POST',body:JSON.stringify({snapshotId:snapshot.id,decision:'APPROVED'})});await load();setMessage('کل ارزیابی تأیید شد.');})}>تأیید کل ارزیابی</button></div></>}
 </section></>}
 <section className="panel"><h2>هشدارها و فوریت</h2>{(snapshot?computed?.alerts??[]:data.alerts.filter((a:Row)=>a.state!=='RESOLVED')).map((a:Row,i:number)=><article key={a.id??i}><p><Link to={a.deep_link??jump(a.sourceDomain,a.target)}>{severity[a.severity]} — {a.subject??a.reason}</Link></p>{a.due_at&&<p>مهلت: <PersianDate value={a.due_at} withTime/></p>}{a.state&&<p>{({OPEN:'جدید',ACKNOWLEDGED:'دیده‌شده',IN_PROGRESS:'در حال پیگیری',RESOLVED:'رفع‌شده'} as Row)[a.state]}</p>}{!snapshot&&data.canEdit&&['OPEN','ACKNOWLEDGED'].includes(a.state)&&<button className="secondary" disabled={busy} onClick={()=>void action(async()=>{await api('/shared/alerts/'+a.id+'/progress',{method:'POST',body:JSON.stringify({state:a.state==='OPEN'?'ACKNOWLEDGED':'IN_PROGRESS'})});await load();})}>{a.state==='OPEN'?'ثبت مشاهده هشدار':'شروع پیگیری'}</button>}</article>)}{!computed?.alerts?.length&&<p>هشدار ناشی از پاسخ‌های جاری وجود ندارد.</p>}</section>
 <details className="panel"><summary>تاریخچه و منابع قبلی</summary><Link to={'/workspace/families/'+id+'/assessments?legacy=1'}>نسخه‌های تاریخی ارزیابی عمومی</Link><p>پاسخ‌های قدیمی بدون نگاشت قطعی، خودکار به پاسخ جدید تبدیل نشده‌اند.</p><Link to={'/workspace/livelihood/'+id+'?legacy=1'}>نسخه‌های تاریخی معیشت</Link> · <Link to={'/workspace/health/'+id+'?legacy=1'}>نسخه‌های تاریخی سلامت</Link>{data.legacy.map((d:Row)=><details key={d.id}><summary>پیش‌نویس مدل {d.model_version} — فقط مرجع</summary><pre dir="auto">{JSON.stringify(d.payload,null,2)}</pre></details>)}{data.legacyDomains?.map((d:Row)=><details key={d.id}><summary>مرجع معیشت قبلی</summary><pre dir="auto">{JSON.stringify(d.payload,null,2)}</pre></details>)}{data.history.map((h:Row,i:number)=><p key={i}>{h.action} · <PersianDate value={h.occurred_at} withTime/></p>)}</details>
 {message&&<p role="status">{message}</p>}
 </>}</Screen>;
}
export function ComprehensiveQueue(){
 const {data,error}=useData('/shared/comprehensive/queue');
 return <Screen title="بررسی ارزیابی جامع خانواده‌ها" error={error}>{data?.items.map((s:Row)=><Link className="data-row" key={s.id} to={'/workspace/families/'+s.family_id+'/assessment/review?version='+s.id}><bdi>{s.family_code}</bdi><span>امتیاز {digits(s.score)} · سطح {s.level}</span><span>{s.status==='ACTIVE'?'فعال':'خانواده غیرفعال — بررسی نسخه محفوظ'}</span><PersianDate value={s.created_at}/></Link>)}</Screen>;
}
