import {useEffect,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {useAuth} from '../auth/AuthProvider';
import {api} from '../api/client';
import {Screen,Field,useData,date,Timeline} from './GuideWorkspace';
import {digits} from './vocabulary';
type Row=Record<string,any>;
const labels:Record<string,string>={PREVIEW:'آماده بررسی',INVALID:'فایل نامعتبر',IMPORTED:'واردشده',VOID:'باطل‌شده',VALID:'سالم',SUSPECT:'مشکوک به تکراری',DUPLICATE:'تکراری قطعی',ERROR:'خطادار',EMPTY:'ردیف خالی',IMPORT:'تأیید ورود',SKIP:'کنارگذاشته‌شده',NEEDS_CLASSIFICATION:'نیازمند تعیین وضعیت',ACTIVE:'فعال',TEMPORARILY_INACTIVE:'غیرفعال',CLOSED:'خارج از کار عملیاتی'};
function useWrite(refresh:()=>void){const [busy,setBusy]=useState(false),[error,setError]=useState('');async function run(url:string,b:Row){setBusy(true);setError('');try{const result=await api<Row>(url,{method:'POST',body:JSON.stringify(b)});refresh();return result;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}return {busy,error,run};}
export function FamilyImportDashboard(){
 const {user}=useAuth(),leader=user?.effectiveRole==='GROUP_LEADER',{data,error,refresh}=useData('/family-import'),action=useWrite(refresh),navigate=useNavigate();
 const [group,setGroup]=useState(''),[file,setFile]=useState<File|null>(null),[filter,setFilter]=useState('all'),[page,setPage]=useState(1);
 useEffect(()=>{if(data?.groups.length===1)setGroup(data.groups[0].id);},[data?.groups.length]);
 async function upload(){if(!file||!group)return;const content=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(Error('خواندن فایل ناموفق بود'));r.readAsDataURL(file);});const result=await action.run('/family-import/groups/'+group+'/upload',{filename:file.name,content});if(result)navigate('/workspace/family-import/'+result.id);}
 const families:Row[]=(data?.families??[]).filter((f:Row)=>filter==='all'||filter==='members'&&f.status==='ACTIVE'&&!f.members_confirmed_at||filter===f.status),shown=families.slice((page-1)*50,page*50);
 return <Screen title="ورود خانواده‌های قبلی از Excel" error={error||action.error} loading={!data&&!error}>{data&&<>
 <p>قالب → بارگذاری → بررسی خطا و تکراری → پیش‌نمایش → تأیید ورود → تعیین وضعیت خانواده</p>
 <div className="role-stat-grid">{Object.entries({total:'کل خانواده‌های واردشده',needsClassification:'نیازمند تعیین وضعیت',active:'فعال',inactive:'غیرفعال',needsMembers:'فعال؛ نیازمند تکمیل اعضا',needsAssessment:'فعال؛ بدون ارزیابی جدید',hasAssessment:'دارای ارزیابی جدید',errorBatches:'Batch دارای خطا',unresolved:'تکراری حل‌نشده'}).map(([key,label])=><div className="role-card" key={key}><span>{label}</span><strong>{digits(data.summary[key])}</strong></div>)}</div>
 {leader&&<section className="panel"><h2>بارگذاری فایل گروه</h2><p><a href="/api/v1/family-import/template">دریافت قالب رسمی Excel</a></p><p>فقط نام، نام خانوادگی، کد ملی، شماره تماس، جنسیت و تاریخ تولد. نام و نام خانوادگی الزامی‌اند. تاریخ تولد شمسی متنی مانند <bdi>1365/07/21</bdi>؛ سایر ستون‌ها اختیاری‌اند. حداکثر ۳۰۰۰ ردیف و ۲ مگابایت.</p><div className="filter-grid"><Field label="گروه مسئول"><select value={group} onChange={e=>setGroup(e.target.value)}><option value="">انتخاب گروه</option>{data.groups.map((g:Row)=><option key={g.id} value={g.id}>{g.name}</option>)}</select></Field><Field label="فایل خانواده‌های قبلی"><input type="file" accept=".xlsx" onChange={e=>setFile(e.target.files?.[0]??null)}/></Field></div>{file&&file.size>2*1024*1024&&<p role="alert">حجم فایل بیش از ۲ مگابایت است.</p>}<button disabled={action.busy||!file||file.size>2*1024*1024||!group} onClick={()=>void upload()}>بارگذاری و بررسی</button></section>}
 <section className="panel"><h2>سابقه Batchها</h2>{data.batches.map((b:Row)=><Link className="data-row" key={b.id} to={'/workspace/family-import/'+b.id}><strong>{b.filename}</strong><span>{b.group_name}</span><span>{labels[b.state]}</span><small>{date(b.created_at)}</small></Link>)}{!data.batches.length&&<p>فایلی بارگذاری نشده است.</p>}</section>
 <section className="panel"><h2>تعیین وضعیت و تکمیل پرونده‌ها</h2><Field label="فیلتر پرونده‌های واردشده"><select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}>{[['all','همه'],['NEEDS_CLASSIFICATION','نیازمند تعیین وضعیت'],['ACTIVE','فعال'],['TEMPORARILY_INACTIVE','غیرفعال'],['members','نیازمند تکمیل اعضا']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><div className="table-scroll"><table><thead><tr><th>خانواده</th><th>وضعیت</th><th>قدم بعدی</th><th>اقدام</th></tr></thead><tbody>{shown.map(f=><tr key={f.id}><td><Link to={'/workspace/families/'+f.id}>{f.head_name}</Link><small>{f.family_code}</small></td><td>{labels[f.status]}{f.batch_state==='VOID'&&' — Batch باطل شده'}</td><td>{f.status==='ACTIVE'?f.members_confirmed_at?f.has_assessment?'ارزیابی ایجاد شده':'نیازمند ارزیابی جدید':'نیازمند تکمیل اعضای خانواده':'—'}</td><td>{leader&&f.batch_state!=='VOID'&&<div className="action-row">{f.status!=='ACTIVE'&&<button disabled={action.busy} onClick={()=>void action.run('/family-import/families/'+f.id,{version:f.version,action:'ACTIVE'})}>فعال</button>}{f.status!=='TEMPORARILY_INACTIVE'&&<button className="secondary" disabled={action.busy} onClick={()=>void action.run('/family-import/families/'+f.id,{version:f.version,action:'INACTIVE'})}>غیرفعال</button>}{f.status==='ACTIVE'&&!f.members_confirmed_at&&<button disabled={action.busy} onClick={()=>void action.run('/family-import/families/'+f.id,{version:f.version,action:'MEMBERS_COMPLETE'})}>تکمیل اعضای خانواده تأیید شد</button>}{f.status==='ACTIVE'&&f.members_confirmed_at&&<Link to={'/workspace/livelihood/'+f.id}>ارزیابی جدید</Link>}</div>}</td></tr>)}</tbody></table></div><div className="workspace-actions"><button className="secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>قبلی</button><span>صفحه {digits(page)}</span><button className="secondary" disabled={page*50>=families.length} onClick={()=>setPage(p=>p+1)}>بعدی</button></div></section>
 </>}</Screen>;
}
export function FamilyImportBatch(){
 const {id}=useParams(),{data,error,refresh}=useData('/family-import/batches/'+id),action=useWrite(refresh),[selected,setSelected]=useState<string[]>([]),[resolveRow,setResolveRow]=useState(''),[reason,setReason]=useState(''),[decision,setDecision]=useState('SKIP'),[rollbackReason,setRollbackReason]=useState(''),[page,setPage]=useState(1);
 useEffect(()=>{if(data)setSelected(data.rows.filter((r:Row)=>r.classification==='VALID'&&r.decision!=='SKIP'||r.classification==='SUSPECT'&&r.decision==='IMPORT').map((r:Row)=>r.id));},[data?.batch.version]);
 return <Screen title="پیش‌نمایش و سابقه ورود خانواده‌ها" error={error||action.error} loading={!data&&!error}><p><Link to="/workspace/family-import">بازگشت به ورود خانواده‌ها</Link></p>{data&&<>
 <section className="panel"><h2>{data.batch.filename}</h2><p>{labels[data.batch.state]} · {date(data.batch.created_at)}</p><a href={'/api/v1/family-import/batches/'+id+'/file'}>دریافت فایل اصلی</a><div className="family-summary">{Object.entries({total:'کل ردیف‌ها',valid:'سالم',failed:'خطادار',suspect:'مشکوک',duplicate:'تکراری قطعی',importable:'قابل ورود',success:'واردشده',skipped:'کنارگذاشته‌شده'}).map(([key,label])=><p key={key}><small>{label}</small>{digits(data.summary[key])}</p>)}</div>{data.batch.errors.map((e:string)=><p role="alert" key={e}>{e}</p>)}{data.batch.state==='VOID'&&<p>ابطال غیرحذفی؛ فایل، شناسه‌ها و تاریخچه حفظ شده‌اند. دلیل: {data.batch.void_reason}</p>}</section>
 <div className="panel table-scroll"><table><thead><tr><th>انتخاب</th><th>Sheet / ردیف</th><th>سرپرست</th><th>نتیجه بررسی</th><th>جزئیات</th><th>تصمیم</th></tr></thead><tbody>{data.rows.slice((page-1)*50,page*50).map((r:Row)=>{const allowed=r.classification==='VALID'&&r.decision!=='SKIP'||r.classification==='SUSPECT'&&r.decision==='IMPORT';return <tr key={r.id}><td>{data.canConfirm&&<input type="checkbox" aria-label={'ورود ردیف '+r.row_number} disabled={!allowed||action.busy} checked={selected.includes(r.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,r.id]:old.filter(x=>x!==r.id))}/>}</td><td>{r.sheet} / {digits(r.row_number)}</td><td>{r.data.first_name} {r.data.last_name}<small>{r.family_code}</small></td><td>{labels[r.classification]}</td><td>{r.errors.map((e:Row,i:number)=><p key={i}>{e.sheet}، ردیف {digits(e.row)}، ستون {e.column}: {e.message}</p>)}{r.duplicate_reasons.map((x:string)=><p key={x}>{x}</p>)}<details><summary>مشخصات ردیف</summary><p>کد ملی: <bdi>{r.data.national_id||'—'}</bdi></p><p>شماره تماس: <bdi>{r.data.mobile||'—'}</bdi></p><p>تاریخ تولد: {r.data.birth_date?date(r.data.birth_date):'نامشخص'}</p></details></td><td>{r.decision&&<p>{labels[r.decision]} {r.decision_reason}</p>}{data.canResolve&&['SUSPECT','DUPLICATE'].includes(r.classification)&&<button className="secondary" onClick={()=>{setResolveRow(r.id);setReason('');setDecision('SKIP');}}>رسیدگی به تکراری</button>}</td></tr>;})}</tbody></table></div>
 <div className="workspace-actions"><button className="secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>قبلی</button><span>صفحه {digits(page)}</span><button className="secondary" disabled={page*50>=data.rows.length} onClick={()=>setPage(p=>p+1)}>بعدی</button></div>
 {resolveRow&&data.canResolve&&<section className="panel"><h2>تصمیم درباره ردیف مشکوک یا تکراری</h2><Field label="تصمیم تکراری"><select value={decision} onChange={e=>setDecision(e.target.value)}><option value="SKIP">کنار گذاشتن</option>{data.rows.find((r:Row)=>r.id===resolveRow)?.classification==='SUSPECT'&&<option value="IMPORT">تأیید ورود با دلیل</option>}</select></Field><Field label="دلیل تصمیم"><textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000}/></Field><button disabled={action.busy||!reason.trim()} onClick={()=>void action.run('/family-import/batches/'+id+'/rows/'+resolveRow,{version:data.batch.version,decision,reason}).then(ok=>{if(ok)setResolveRow('');})}>ثبت تصمیم تکراری</button></section>}
 {data.canConfirm&&<section className="panel"><h2>تأیید نهایی ورود</h2><p>{digits(selected.length)} خانواده انتخاب‌شده با وضعیت «نیازمند تعیین وضعیت» وارد می‌شوند. سایر ردیف‌ها در سابقه Batch باقی می‌مانند.</p><button disabled={action.busy||!selected.length} onClick={()=>void action.run('/family-import/batches/'+id+'/confirm',{version:data.batch.version,rowIds:selected})}>تأیید ورود خانواده‌های انتخاب‌شده</button></section>}
 {data.batch.state==='IMPORTED'&&<section className="panel"><h2>ابطال Batch</h2>{data.canRollback?<><p>پرونده‌ها از کار عملیاتی خارج می‌شوند؛ داده‌ها حذف نمی‌شوند.</p><Field label="دلیل ابطال"><textarea value={rollbackReason} onChange={e=>setRollbackReason(e.target.value)} maxLength={2000}/></Field><button disabled={action.busy||!rollbackReason.trim()} onClick={()=>void action.run('/family-import/batches/'+id+'/rollback',{version:data.batch.version,reason:rollbackReason})}>ابطال غیرحذفی Batch</button></>:<p>ابطال فقط توسط مدیر اجرایی و پیش از ویرایش یا فعالیت عملیاتی پرونده‌ها مجاز است.</p>}</section>}
 <details className="panel"><summary>تاریخچه Batch</summary><Timeline rows={data.history}/></details>
 </>}</Screen>;
}
