import {useState} from 'react';
import {Link,useLocation,useSearchParams} from 'react-router-dom';
import {Screen,Field,useData,date,fa} from './GuideWorkspace';
import {digits} from './vocabulary';
import './LeaderWorkspace.css';
type Row=Record<string,any>;
export const livelihoodStatus:Record<string,string>={VALID:'تأییدشده / معتبر',EXPIRED:'اعتبار پایان‌یافته',PENDING:'منتظر تأیید مدیر اجرایی',RETURNED:'برگشتی برای اصلاح',DRAFT:'در حال تکمیل',READY:'آماده ارسال',INCOMPLETE:'اطلاعات ناقص / نیازمند تکمیل',NOT_RECORDED:'ثبت نشده'};
export const urgencyLabel:Record<string,string>={IMMEDIATE:'فوری',NECESSARY:'ضروری',IMPORTANT:'مهم',NON_URGENT:'غیرفوری'};
export function operationalGroup(name:string|undefined,code?:string){const n=code?.match(/^V100-TEST-G([1-5])$/)?.[1]??name?.match(/^گروه\s*([1-5۱-۵])/u)?.[1];return n?'گروه '+digits(n):name??'گروه ثبت نشده';}
export function Score({value}:{value:number|null}){return <span>{value==null?'نامشخص — قابل محاسبه نیست':digits(value)+' از ۳۰'}</span>;}
export function Status({value}:{value:string}){return <span className={'leader-status state-'+value}>{livelihoodStatus[value]??'نامشخص'}</span>;}
const filters=[['all','همه خانواده‌ها'],['action','نیازمند اقدام من'],['PENDING','منتظر تأیید مدیر اجرایی'],['alerts','هشدار مهم / فوری'],['VALID','معتبر'],['RETURNED','برگشتی'],['DRAFT','در حال تکمیل'],['INCOMPLETE','ناقص'],['NOT_RECORDED','ثبت نشده']];
function matches(f:Row,filter:string){return filter==='all'||filter==='INCOMPLETE'&&['INCOMPLETE','UNKNOWN'].includes(f.data_status)||filter==='action'&&f.needs_action||filter==='alerts'&&f.alerts.some((a:Row)=>['IMPORTANT','VERY_IMPORTANT','CRITICAL'].includes(a.severity))||f.status===filter;}
export function LeaderDashboard({listOnly=false}:{listOnly?:boolean}){
 const {data,error}=useData('/livelihood/families'),[params,setParams]=useSearchParams(),location=useLocation(),filter=params.get('filter')??'all',[q,setQ]=useState('');
 const families:Row[]=data?.families??[],shown=families.filter(f=>matches(f,filter)&&[f.head_name,f.family_code].some(x=>String(x??'').includes(q))),back=location.pathname+location.search;
 const select=(value:string)=>setParams(value==='all'?{}:{filter:value});
 return <Screen title={listOnly?'خانواده‌های گروه':'داشبورد سرگروه'} error={error} loading={!data&&!error}><div className="leader-workspace">
 {data&&<><p className="leader-intro">{[...new Set(families.map(f=>operationalGroup(f.group_name,f.group_code)))].join('، ')} · وضعیت واقعی پرونده‌ها و قدم بعدی ارزیابی معیشت</p>
 <div className="role-stat-grid">{filters.slice(0,4).map(([key,label])=><button className={'role-card leader-stat '+(key===filter?'selected':'')} key={key} aria-pressed={key===filter} onClick={()=>select(key)}><span>{key==='all'?'خانواده‌های گروه':label}</span><strong>{digits(families.filter(f=>matches(f,key)).length)}</strong><small>نمایش در فهرست</small></button>)}</div>
 <section className="role-card"><header><h2>وضعیت ارزیابی معیشت گروه</h2><Link to="/workspace">پیگیری‌های من ←</Link></header><div className="leader-state-strip">{['VALID','PENDING','RETURNED','DRAFT','INCOMPLETE','READY','EXPIRED','NOT_RECORDED'].map(key=><button className="secondary" key={key} aria-pressed={filter===key} onClick={()=>select(key)}>{livelihoodStatus[key]}: {digits(families.filter(f=>matches(f,key)).length)}</button>)}</div></section>
 <section className="role-card"><header><h2>فهرست خانواده‌های گروه</h2><span role="status">{digits(shown.length)} از {digits(families.length)} خانواده</span></header><div className="filter-grid"><Field label="جست‌وجوی خانواده یا شناسه"><input value={q} onChange={e=>setQ(e.target.value)}/></Field><Field label="فیلتر وضعیت خانواده"><select value={filter} onChange={e=>select(e.target.value)}>{filters.map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></Field></div>
 <div className="table-scroll"><table><thead><tr><th>خانواده / سرپرست</th><th>اعضا</th><th>وضعیت ارزیابی معیشت</th><th>امتیاز معیشت</th><th>نیازمند توجه / قدم بعدی</th><th>آخرین تغییر</th><th>عملیات</th></tr></thead><tbody>{shown.map(f=><tr key={f.id}><td><strong>{f.head_name??'سرپرست ثبت نشده'}</strong><small><bdi>{f.family_code}</bdi></small></td><td>{digits(f.member_count)}</td><td><Status value={f.status}/><small>{f.data_status==='UNKNOWN'?'دارای پاسخ نامشخص':f.data_status==='INCOMPLETE'?'اطلاعات نیازمند تکمیل':f.data_status==='COMPLETED'?'اطلاعات کامل':'اطلاعات ثبت نشده'}</small></td><td>{f.status==='NOT_RECORDED'?'ثبت نشده':<Score value={f.score}/>}</td><td>{f.alerts.length?<span className="badge-red">{digits(f.alerts.length)} هشدار فعال</span>:nextAction(f)}{f.reason&&<details><summary>دلیل برگشت</summary><p>{f.reason}</p></details>}</td><td>{date(f.updated_at)}</td><td><Link to={'/workspace/families/'+f.id+'?returnTo='+encodeURIComponent(back)}>مشاهده پرونده</Link></td></tr>)}</tbody></table></div>{!shown.length&&<p className="quiet-state">خانواده‌ای مطابق این فیلتر وجود ندارد.</p>}</section></>}
 </div></Screen>;
}
export function nextAction(f:Row){return f.status==='RETURNED'?'اصلاح طبق دلیل مدیر اجرایی':f.status==='READY'?'بازبینی و ارسال برای تأیید':f.status==='PENDING'?'انتظار بررسی مدیر اجرایی':f.status==='VALID'?'مشاهده نسخه معتبر':f.status==='EXPIRED'?'بررسی برای ارزیابی جدید':f.status==='NOT_RECORDED'?'شروع ارزیابی معیشت':'تکمیل اطلاعات و شواهد';}
export function LeaderFollowups(){
 const {data,error}=useData('/livelihood/families'),tasks=useData('/roles/dashboard'),[category,setCategory]=useState('all');
 const rows:Row[]=[];
 for(const f of data?.families??[]){if(f.needs_action)rows.push({id:f.id,type:f.status,dataStatus:f.data_status,family:f.head_name??f.family_code,status:livelihoodStatus[f.status],time:f.updated_at,next:nextAction(f),link:'/workspace/livelihood/'+f.id});for(const a of f.alerts)rows.push({id:a.id,type:'ALERT',family:f.head_name??f.family_code,status:fa(a.state),time:null,next:a.subject,link:'/workspace/families/'+f.id+'?returnTo=%2Fworkspace'});}
 for(const i of tasks.data?.tasks.items??[])if(i.lifecycle==='ACTIVE'&&i.status!=='COMPLETED')rows.push({id:i.id,type:'TASK',family:i.subject,status:fa(i.status),time:i.deadline,next:'مشاهده مأموریت و ثبت نتیجه مجاز',link:'/workspace/items/'+i.id});
 const categories=[['all','همه پیگیری‌ها'],['RETURNED','برگشتی برای اصلاح'],['DRAFT','در حال تکمیل'],['INCOMPLETE','اطلاعات ناقص'],['READY','آماده ارسال'],['NOT_RECORDED','ثبت نشده'],['EXPIRED','اعتبار پایان‌یافته'],['ALERT','هشدارهای فعال'],['TASK','مأموریت‌های ارجاع‌شده']];
 return <Screen title="پیگیری‌های من" error={error||tasks.error} loading={!data&&!error}><div className="leader-workspace"><nav className="subnav"><Link to="/leader/families">گروه‌ها و خانواده‌های در دسترس</Link><Link to="/workspace/notifications">اعلان‌ها</Link></nav><Field label="نوع پیگیری"><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><section className="role-card"><h2>موارد نیازمند اقدام</h2><div className="table-scroll"><table><thead><tr><th>خانواده / موضوع</th><th>نوع پیگیری</th><th>وضعیت</th><th>مهلت / آخرین تغییر</th><th>اقدام بعدی</th></tr></thead><tbody>{rows.filter(r=>category==='all'||r.type===category||category==='INCOMPLETE'&&['INCOMPLETE','UNKNOWN'].includes(r.dataStatus)).map(r=><tr key={r.id}><td>{r.family}</td><td>{categories.find(c=>c[0]===r.type)?.[1]}</td><td>{r.status}</td><td>{date(r.time)}</td><td><Link to={r.link}>{r.next}</Link></td></tr>)}</tbody></table></div>{!rows.some(r=>category==='all'||r.type===category||category==='INCOMPLETE'&&['INCOMPLETE','UNKNOWN'].includes(r.dataStatus))&&<p>پیگیری بازی در این دسته وجود ندارد.</p>}</section><p className="quiet-state">قاعده «نزدیک انقضا» و گردش مستقل بازدید میدانی در مرحله بعد است. فقط پایان اعتبار ثبت‌شده و مأموریت‌های موجود نمایش داده می‌شوند.</p></div></Screen>;
}
