import {FamilyIdentity} from '../components/FamilyIdentity';
import {familyStates} from '../components/familyVocabulary';
import {useState} from 'react';
import {Link,useLocation,useSearchParams,useNavigate} from 'react-router-dom';
import {Screen,Field,useData,date,fa} from './GuideWorkspace';
import {digits} from './vocabulary';
import './LeaderWorkspace.css';
type Row=Record<string,any>;
export const livelihoodStatus:Record<string,string>={MODEL_REVIEW_REQUIRED:'نیازمند بازنگری پنج حوزه',VALID:'تأییدشده / معتبر',EXPIRED:'اعتبار پایان‌یافته',PENDING:'منتظر تأیید مدیر اجرایی',RETURNED:'برگشتی برای اصلاح',DRAFT:'در حال تکمیل',READY:'آماده ارسال',INCOMPLETE:'ناقص / نیازمند تکمیل',NOT_RECORDED:'ثبت نشده',APPROVED:'تأییدشده / معتبر',SUBMITTED:'منتظر تأیید مدیر اجرایی',IN_REVIEW:'در حال بررسی مدیر اجرایی'};
export const urgencyLabel:Record<string,string>={IMMEDIATE:'فوری',NECESSARY:'ضروری',IMPORTANT:'مهم',NON_URGENT:'غیرفوری'};
export function operationalGroup(name:string|undefined,code?:string){const n=code?.match(/^V100-TEST-G([1-5])$/)?.[1]??name?.match(/^گروه\s*([1-5۱-۵])/u)?.[1];return n?'گروه '+digits(n):name??'گروه ثبت نشده';}
export function Score({value}:{value:number|null}){return <span>{value==null?'نامشخص — قابل محاسبه نیست':digits(value)+' از ۳۰'}</span>;}
export function Status({value}:{value:string}){return <span className={'leader-status state-'+(({APPROVED:'VALID',SUBMITTED:'PENDING'} as Record<string,string>)[value]??value)}>{livelihoodStatus[value]??'نامشخص'}</span>;}
const filters=[['MODEL_REVIEW_REQUIRED','نیازمند بازنگری پنج حوزه'],['all','همه خانواده‌ها'],['action','نیازمند اقدام من'],['PENDING','منتظر تأیید مدیر اجرایی'],['alerts','هشدار مهم / فوری'],['VALID','معتبر'],['RETURNED','برگشتی'],['DRAFT','در حال تکمیل'],['INCOMPLETE','ناقص'],['NOT_RECORDED','ثبت نشده'],['READY','آماده ارسال'],['EXPIRED','اعتبار پایان‌یافته']];
function matches(f:Row,filter:string){return filter==='all'||filter==='INCOMPLETE'&&['INCOMPLETE','UNKNOWN'].includes(f.data_status)||filter==='action'&&f.needs_action||filter==='alerts'&&f.alerts.some((a:Row)=>['IMPORTANT','VERY_IMPORTANT','CRITICAL'].includes(a.severity))||f.status===filter;}
export function LeaderDashboard({listOnly=false,domain}:{listOnly?:boolean;domain?:'health'}){
 const {data,error}=useData('/family-workspace/families'),[params,setParams]=useSearchParams(),location=useLocation(),filter=params.get('filter')??'all',lifecycle=params.get('state')??'ACTIVE',[q,setQ]=useState('');
 const all:Row[]=data?.families??[],families=all.filter(f=>lifecycle==='all'||f.family_status===lifecycle);
 const matchesFamily=(f:Row)=>matches(f,filter);
 const shown=families.filter(f=>matchesFamily(f)&&[f.head_name,f.family_code].some(x=>String(x??'').includes(q))),back=location.pathname+location.search;
 const navigate=useNavigate();
 const select=(value:string)=>{const next=new URLSearchParams(params);if(value==='all')next.delete('filter');else next.set('filter',value);listOnly?setParams(next):navigate('/leader/families?'+next.toString());};
 const attention=(f:Row)=>f.family_status==='ACTIVE'&&(f.needs_action||['DRAFT','READY','RETURNED','NOT_RECORDED'].includes(f.health_status)||f.imported&&!f.imported.members_confirmed_at);
 return <Screen title={domain?'ارزیابی‌های سلامت و درمان':listOnly?'فهرست خانواده‌ها':'داشبورد سرگروه'} error={error} loading={!data&&!error}><div className="leader-workspace">
 {data&&<><p className="leader-intro">خانواده‌های در محدوده نقش فعال · وضعیت پرونده و حوزه‌های ارزیابی</p>
 {!listOnly&&<><div className="role-stat-grid">{[['خانواده‌های فعال',families.length,'all'],['نیازمند اقدام من',families.filter(attention).length,'action'],['منتظر مدیر اجرایی',families.filter(f=>f.status==='PENDING'||f.health_status==='SUBMITTED').length,'PENDING'],['هشدار مهم / فوری',families.filter(f=>matches(f,'alerts')).length,'alerts']].map(([label,n,key])=><button className="role-card leader-stat" key={key} onClick={()=>select(String(key))}><span>{label}</span><strong>{digits(n)}</strong><small>نمایش در فهرست</small></button>)}</div>
 <section className="role-card"><h2>خلاصه وضعیت ارزیابی‌ها</h2>{[['ارزیابی جامع خانواده','/workspace/families','status']].map(([title,to,key])=><div className="assessment-summary" key={key}><h3><Link to={to}>{title}</Link></h3><div className="leader-state-strip">{[['VALID','APPROVED','تأییدشده'],['PENDING','SUBMITTED','منتظر تأیید'],['RETURNED','RETURNED','برگشتی'],['DRAFT','DRAFT','در حال تکمیل'],['READY','READY','آماده ارسال'],['INCOMPLETE','INCOMPLETE','ناقص'],['NOT_RECORDED','NOT_RECORDED','ثبت نشده']].map(([lh,h,label])=><Link key={lh} to={to+'?filter='+lh}>{label}: {digits(families.filter(f=>lh==='INCOMPLETE'?(key==='status'?['INCOMPLETE','UNKNOWN'].includes(f.data_status):['DRAFT','RETURNED'].includes(f.health_status)&&!f.health_complete):f[key]===(key==='status'?lh:h)).length)}</Link>)}</div></div>)}</section>
 <section className="role-card"><h2>پیگیری‌های مهم</h2><p>{digits(families.filter(attention).length)} خانواده نیازمند اقدام شماست.</p><Link to="/workspace">مشاهده پیگیری‌های من</Link><p><Link to="/leader/families">مشاهده فهرست کامل خانواده‌ها</Link></p></section></>}
 {listOnly&&<section className="role-card"><header><h2>خانواده‌ها و وضعیت حوزه‌ها</h2><span role="status">{digits(shown.length)} از {digits(families.length)} خانواده</span></header>
 <div className="filter-grid"><Field label="جست‌وجوی خانواده یا شناسه"><input value={q} onChange={e=>setQ(e.target.value)}/></Field><Field label="وضعیت خانواده"><select value={lifecycle} onChange={e=>{const next=new URLSearchParams(params);next.set('state',e.target.value);setParams(next);}}><option value="all">همه</option>{Object.entries(familyStates).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><Field label="فیلتر وضعیت ارزیابی"><select value={filter} onChange={e=>select(e.target.value)}>{filters.map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></Field></div>
 <div className="active-filter" role="status">فیلتر فعال: {familyStates[lifecycle]??'همه'} · {filters.find(([key])=>key===filter)?.[1]}{filter!=='all'&&<button className="secondary" onClick={()=>select('all')}>پاک کردن فیلتر</button>}</div>
 <div className="table-scroll"><table><thead><tr><th>خانواده / سرپرست</th><th>وضعیت خانواده</th><th>وضعیت ارزیابی جامع</th><th>نتیجه تأییدشده</th><th>نیازمند توجه / قدم بعدی</th><th>آخرین تغییر</th><th>عملیات</th></tr></thead><tbody>{shown.map(f=><tr key={f.id}><td><FamilyIdentity name={f.head_name} code={f.family_code}/><small>{digits(f.member_count)} عضو</small></td><td>{familyStates[f.family_status]}</td><td><Link to={'/workspace/families/'+f.id+'/assessment/review'}><Status value={f.status}/></Link></td><td>{f.score==null?'نامشخص':digits(f.score)+' / ۱۰۰ · '+f.need_level}</td><td>{f.family_status!=='ACTIVE'?'مشاهده پرونده و سوابق':f.imported&&!f.imported.members_confirmed_at?<Link to="/workspace/family-import">نیازمند تکمیل اعضای خانواده</Link>:<>{f.alerts.length>0&&<span className="badge-red">{digits(f.alerts.length)} هشدار فعال</span>}{nextAction(f)}</>}{f.reason&&<details><summary>توضیح وضعیت ارزیابی</summary><p>{f.reason}</p></details>}</td><td>{date([f.updated_at,f.health_updated_at].filter(Boolean).sort().at(-1))}</td><td><Link to={'/workspace/families/'+f.id+'/assessment/review'}>ارزیابی جامع</Link> · <Link to={'/workspace/families/'+f.id+'?returnTo='+encodeURIComponent(back)}>مشاهده پرونده</Link></td></tr>)}</tbody></table></div>{!shown.length&&<p className="quiet-state">خانواده‌ای مطابق این فیلتر وجود ندارد.</p>}</section>}</>}
 </div></Screen>;
}
export function nextAction(f:Row){if(f.assessment)return ({COMPLETE_MEMBERS:'تکمیل و تأیید اعضای خانواده',VIEW:'مشاهده ارزیابی',REVIEW:'بررسی نسخه ارسالی',WAIT_FOR_APPROVAL:'انتظار بررسی مدیر اجرایی',START_ASSESSMENT:'شروع ارزیابی جامع',CONTINUE_DRAFT:'ادامه ارزیابی در حال تکمیل',REVIEW_ALL_DOMAINS:'بازنگری همه پنج حوزه'} as Row)[f.assessment.nextAction];return f.status==='RETURNED'?'اصلاح طبق دلیل مدیر اجرایی':f.status==='READY'?'بازبینی و ارسال برای تأیید':f.status==='PENDING'?'انتظار بررسی مدیر اجرایی':f.status==='VALID'?'مشاهده نسخه معتبر':f.status==='EXPIRED'?'بررسی برای ارزیابی جدید':f.status==='NOT_RECORDED'?'شروع ارزیابی معیشت':'تکمیل اطلاعات و شواهد';}
export function LeaderFollowups(){
 const {data,error}=useData('/family-workspace/families'),tasks=useData('/roles/dashboard'),[category,setCategory]=useState('all');
 const rows:Row[]=[];
 for(const f of data?.families??[]){if(f.family_status!=='ACTIVE')continue;if(f.imported&&!f.imported.members_confirmed_at){rows.push({id:f.id+'-members',type:'MEMBERS',family:f.head_name??f.family_code,status:'نیازمند تکمیل اعضای خانواده',time:f.updated_at,next:'تکمیل و تأیید اعضای خانواده',link:'/workspace/family-import'});continue;}if(!f.comprehensive&&['DRAFT','READY','RETURNED','NOT_RECORDED'].includes(f.health_status))rows.push({id:f.id+'-health',type:f.health_status,domain:'سلامت و درمان',reason:f.health_reason,family:f.head_name??f.family_code,status:livelihoodStatus[f.health_status],time:f.health_updated_at??f.updated_at,next:f.health_status==='RETURNED'?'اصلاح ارزیابی سلامت':'تکمیل ارزیابی سلامت',link:'/workspace/health/'+f.id});if(f.needs_action)rows.push({id:f.id,type:f.status,dataStatus:f.data_status,family:f.head_name??f.family_code,status:livelihoodStatus[f.status],reason:f.reason,time:f.updated_at,next:nextAction(f),link:f.comprehensive?'/workspace/families/'+f.id+'/assessment/review':'/workspace/livelihood/'+f.id});for(const a of f.alerts)rows.push({id:a.id,type:'ALERT',family:f.head_name??f.family_code,status:fa(a.state),time:null,next:a.subject,link:a.deep_link??('/workspace/families/'+f.id+'?returnTo=%2Fworkspace')});}
 for(const i of tasks.data?.tasks.items??[])if(i.lifecycle==='ACTIVE'&&i.status!=='COMPLETED')rows.push({id:i.id,type:'TASK',family:i.subject,status:fa(i.status),time:i.deadline,next:'مشاهده مأموریت و ثبت نتیجه مجاز',link:'/workspace/items/'+i.id});
 const categories=[['MODEL_REVIEW_REQUIRED','بازنگری پنج حوزه'],['MEMBERS','تکمیل اعضا'],['all','همه پیگیری‌ها'],['RETURNED','برگشتی برای اصلاح'],['DRAFT','در حال تکمیل'],['INCOMPLETE','اطلاعات ناقص'],['READY','آماده ارسال'],['NOT_RECORDED','ثبت نشده'],['EXPIRED','اعتبار پایان‌یافته'],['ALERT','هشدارهای فعال'],['TASK','مأموریت‌های ارجاع‌شده']];
 return <Screen title="پیگیری‌های من" error={error||tasks.error} loading={!data&&!error}><div className="leader-workspace"><Field label="نوع پیگیری"><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><section className="role-card"><h2>موارد نیازمند اقدام</h2><div className="table-scroll"><table><thead><tr><th>خانواده / موضوع</th><th>نوع پیگیری</th><th>وضعیت</th><th>مهلت / آخرین تغییر</th><th>اقدام بعدی</th></tr></thead><tbody>{rows.filter(r=>category==='all'||r.type===category||category==='INCOMPLETE'&&['INCOMPLETE','UNKNOWN'].includes(r.dataStatus)).map(r=><tr key={r.id}><td>{r.family}</td><td>{r.domain??(r.link.includes('/livelihood/')?'معیشت و اقتصاد':categories.find(c=>c[0]===r.type)?.[1])}</td><td>{r.status}{r.reason&&<p className="workflow-text">دلیل برگشت: {r.reason}</p>}</td><td>{date(r.time)}</td><td><Link to={r.link}>{r.next}</Link></td></tr>)}</tbody></table></div>{!rows.some(r=>category==='all'||r.type===category||category==='INCOMPLETE'&&['INCOMPLETE','UNKNOWN'].includes(r.dataStatus))&&<p>پیگیری بازی در این دسته وجود ندارد.</p>}</section><p className="quiet-state">قاعده «نزدیک انقضا» و گردش مستقل بازدید میدانی در مرحله بعد است. فقط پایان اعتبار ثبت‌شده و مأموریت‌های موجود نمایش داده می‌شوند.</p></div></Screen>;
}
