import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {api} from '../api/client';
import {useAuth} from '../auth/AuthProvider';
import {Screen,Field,useData,date} from './GuideWorkspace';
import {digits} from './vocabulary';
import './Livelihood.css';
type Row=Record<string,any>;
const states:Row={DRAFT:'پیش‌نویس / در حال تکمیل',READY:'آماده ارسال',SUBMITTED:'ارسال‌شده برای مدیر اجرایی',IN_REVIEW:'منتظر بررسی',RETURNED:'برگشت برای تکمیل',APPROVED:'تأییدشده / معتبر'};
const urgency:Row={IMMEDIATE:'فوری — حداکثر ۲۴ ساعت',NECESSARY:'ضروری — حداکثر ۷ روز',IMPORTANT:'مهم — حداکثر ۳۰ روز',NON_URGENT:'غیرفوری — برنامه عادی'};
export function LivelihoodFamilies(){const {data,error}=useData('/livelihood/families');return <Screen title="خانواده‌ها — ارزیابی معیشت" error={error}><p>اطلاعات پایه، اعضا، مدارک و ارزیابی معیشت و اقتصاد نسخه ۱٫۰۰</p><div className="table-scroll"><table><thead><tr><th>شناسه</th><th>سرپرست</th><th>گروه</th><th>وضعیت معیشت</th><th>عملیات</th></tr></thead><tbody>{data?.families.map((f:Row)=><tr key={f.id}><td><bdi>{f.family_code}</bdi></td><td>{f.head_name}</td><td>{f.group_name}</td><td>{states[f.state]??'هنوز ثبت نشده'}</td><td><Link to={'/workspace/livelihood/'+f.id}>تکمیل / مشاهده پرونده</Link></td></tr>)}</tbody></table></div></Screen>}
export function LivelihoodQueue(){const {data,error}=useData('/livelihood/queue');return <Screen title="ارزیابی‌های منتظر تأیید" error={error}><p>صف واقعی ارزیابی جزئی معیشت؛ نتیجه نهایی پنج حوزه هنوز محاسبه نمی‌شود.</p>{data?.items.map((s:Row)=><Link className="data-row" key={s.id} to={'/workspace/livelihood/'+s.family_id}><strong>{s.head_name||s.family_code}</strong><span>{s.group_name}</span><span>{states[s.state]}</span><span>{date(s.submitted_at)}</span></Link>)}{data&&!data.items.length&&<p>ارزیابی منتظر بررسی وجود ندارد.</p>}</Screen>}
export function LivelihoodApproved({familyId}:{familyId:string}){const {data}=useData('/livelihood/families/'+familyId);const s=data?.submissions.find((s:Row)=>s.decision==='APPROVED');return s?<section className="panel livelihood-summary"><h2>معیشت و اقتصاد — ارزیابی تأییدشده</h2><p>{digits(s.snapshot.result.score)} از ۳۰ · تأیید: {date(s.decided_at)} · اعتبار تا {date(s.valid_until)}</p><p>سلامت، مسکن، آسیب‌پذیری ویژه و آموزش: هنوز ارزیابی نشده / در مرحله بعد</p><p>امتیاز کل و سطح A/B/C/D برای این نسخه محاسبه نشده است.</p><Link to={'/workspace/livelihood/'+familyId}>مشاهده پاسخ‌ها، مدارک و سابقه تأیید</Link></section>:null;}
function Rows({name,title,fields,rows,members,disabled,onChange}:{name:string;title:string;fields:Row[];rows:Row[];members:Row[];disabled:boolean;onChange:(r:Row[])=>void}){return <section className="panel"><h2>{title}</h2>{rows.map((row,index)=><fieldset className="lv-row" key={index} disabled={disabled}><legend>{title} — ردیف {digits(index+1)}</legend><div className="filter-grid">{fields.map(f=><Field label={f.label} key={f.key}>{f.options||f.type==='member'?<select aria-label={title+' '+f.label+' '+(index+1)} value={row[f.key]??''} onChange={e=>onChange(rows.map((r,i)=>i===index?{...r,[f.key]:e.target.value}:r))}><option value="">ثبت نشده</option><option value="UNKNOWN">نامشخص / نیازمند تکمیل</option>{f.type==='member'?members.map(m=><option key={m.id} value={m.id}>{m.first_name} {m.last_name}</option>):f.options.map((o:string)=><option key={o}>{o}</option>)}</select>:<input aria-label={title+' '+f.label+' '+(index+1)} type={f.type==='number'?'number':f.type==='date'?'date':'text'} min={f.type==='number'?0:undefined} maxLength={3000} value={row[f.key]??''} onChange={e=>onChange(rows.map((r,i)=>i===index?{...r,[f.key]:f.type==='number'&&e.target.value!==''?Number(e.target.value):e.target.value}:r))}/>}</Field>)}</div>{!disabled&&<button type="button" className="secondary" onClick={()=>onChange(rows.filter((_,i)=>i!==index))}>حذف ردیف {digits(index+1)}</button>}</fieldset>)}{!rows.length&&<p>اطلاعات ثبت نشده است.</p>}{!disabled&&<button type="button" className="secondary" onClick={()=>onChange([...rows,{}])}>افزودن ردیف {title}</button>}</section>}
export function LivelihoodPage(){const {id}=useParams(),{user}=useAuth(),{data,error,refresh}=useData('/livelihood/families/'+id);const [tab,setTab]=useState('basic'),[p,setP]=useState<Row>({}),[basic,setBasic]=useState<Row>({}),[members,setMembers]=useState<Row[]>([]),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[reason,setReason]=useState(''),[selected,setSelected]=useState(''),[newDraft,setNewDraft]=useState(false),[category,setCategory]=useState('NATIONAL_CARD'),[docName,setDocName]=useState('');
 useEffect(()=>{if(data){setP(data.payload??{});setDirty(false);}},[data?.review?.version,data?.family?.id]);
 useEffect(()=>{if(data){setBasic(data.family);setMembers(data.members);}},[data?.family?.version,data?.family?.id]);
 useEffect(()=>{if(data?.submissions[0]?.decision==='APPROVED')setNewDraft(false);},[data?.submissions[0]?.id,data?.submissions[0]?.decision]);
 const review=data?.review,editable=!!data?.canEdit&&(!review||['DRAFT','READY','RETURNED'].includes(review.state))&&(!!review||!data?.submissions.some((s:Row)=>s.decision==='APPROVED')||newDraft);
 const submission=data?.submissions.find((s:Row)=>s.id===selected)??data?.submissions[0];
 const historical=!editable&&submission;const shown=historical?submission.snapshot.payload:p,shownMembers=historical?submission.snapshot.members:members,shownBasic=historical?submission.snapshot.family:basic,documents=historical?submission.snapshot.documents:data?.documents??[];
 const form=historical?submission.snapshot.formSchema:data;
 const result=historical?submission.snapshot.result:data?.result,definition=historical?submission.snapshot.modelDefinition:data?.model.definition;
 const change=(key:string,value:any)=>{setP(v=>({...v,[key]:value}));setDirty(true);setMessage('');};
 async function run(url:string,body:unknown){setBusy(true);setMessage('');try{await api(url,{method:'POST',body:JSON.stringify(body)});setMessage('ثبت شد.');refresh();return true;}catch(e){setMessage((e as Error).message);return false;}finally{setBusy(false);}}
 async function upload(file?:File){if(!file)return;if(file.size>256*1024){setMessage('حداکثر اندازه مدرک ۲۵۶ کیلوبایت است.');return;}const content=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});await run('/livelihood/families/'+id+'/documents',{name:docName||file.name,category,mediaType:file.type||'text/plain',content});}
 return <Screen title="اطلاعات خانواده و ارزیابی معیشت" error={error} loading={!data&&!error}>{data&&<div className="livelihood"><p><bdi>{data.family.code}</bdi> · {data.family.groupName} · {states[review?.state]??(submission?.decision?states[submission.decision]:'هنوز ثبت نشده')}</p>{data.family.code.startsWith('HL-TEST-')&&<p className="quiet-state">پرونده و مدارک کاملاً فرضی Development/Test — اطلاعات واقعی نیست.</p>}{data.canEdit&&!review&&!newDraft&&data.submissions.some((s:Row)=>s.decision==='APPROVED')&&<button onClick={()=>{setNewDraft(true);setSelected('');}}>ایجاد ارزیابی جدید با حفظ نسخه تأییدشده</button>}<nav className="subnav" aria-label="مراحل ارزیابی">{[['basic','اطلاعات پایه و اعضا'],['documents','مدارک پایه'],['livelihood','معیشت و اقتصاد'],['result','نتیجه و ارسال']].map(([key,label])=><button className={tab===key?'':'secondary'} key={key} onClick={()=>setTab(key)}>{label}</button>)}</nav>{message&&<p role="status" className="lv-message">{message}</p>}{dirty&&<p>پاسخ‌های ذخیره‌نشده دارید؛ برای محاسبه و ارسال ابتدا «ذخیره و محاسبه» را بزنید.</p>}{submission?.decision==='RETURNED'&&<p className="lv-message">علت برگشت: {submission.reason}</p>}{historical&&<section className="panel"><p>نمای ثابت ارسال {digits(submission.revision)} · ارسال: {date(submission.submitted_at)} · {states[submission.decision]??states[review?.state]}</p>{submission.decision==='APPROVED'&&<p>تأییدکننده: {submission.approver} · تأیید: {date(submission.decided_at)} · اعتبار تا {date(submission.valid_until)} · {new Date(submission.valid_until)<new Date()?'اعتبار پایان یافته':'معتبر (حوزه معیشت)'}</p>}<Field label="نسخه ارسالی"><select value={submission.id} onChange={e=>setSelected(e.target.value)}>{data.submissions.map((s:Row)=><option key={s.id} value={s.id}>{date(s.submitted_at)} · {states[s.decision]??'منتظر تصمیم'}</option>)}</select></Field></section>}
 {tab==='basic'&&<><section className="panel"><h2>اطلاعات پایه خانواده</h2><fieldset disabled={!editable||busy}><div className="filter-grid">{[['neighborhood','محله / محدوده سکونت'],['residenceType','نوع سکونت فعلی'],['formedOn','تاریخ تشکیل/انتقال پرونده'],['source','منبع اطلاعات اولیه']].map(([key,label])=><Field key={key} label={label}><input type={key==='formedOn'?'date':'text'} value={shownBasic[key]??''} onChange={e=>setBasic(v=>({...v,[key]:e.target.value}))}/></Field>)}</div></fieldset><p>گروه: {shownBasic.groupName} · تعداد اعضا: {digits(shownMembers.length)}</p></section><section className="panel"><h2>اعضای خانواده</h2>{shownMembers.map((m:Row,i:number)=><fieldset key={m.id??i} className="lv-row" disabled={!editable||busy}><legend>عضو {digits(i+1)}</legend><div className="filter-grid">{[['first_name','نام'],['last_name','نام خانوادگی'],['national_id','شناسه ملی'],['mobile','شماره تماس'],['birth_date','تاریخ تولد']].map(([key,label])=><Field label={label+' عضو '+digits(i+1)} key={key}><input type={key==='birth_date'?'date':'text'} value={m[key]?.slice?.(0,key==='birth_date'?10:undefined)??''} onChange={e=>setMembers(v=>v.map((x,j)=>j===i?{...x,[key]:e.target.value}:x))}/></Field>)}<Field label={'نسبت عضو '+digits(i+1)}><select value={m.relationship_code??''} onChange={e=>setMembers(v=>v.map((x,j)=>j===i?{...x,relationship_code:e.target.value}:x))}>{Object.entries({HEAD:'سرپرست',SPOUSE:'همسر',CHILD:'فرزند',PARENT:'والد',SIBLING:'خواهر/برادر',OTHER:'سایر'}).map(([k,l])=><option value={k} key={k}>{l}</option>)}</select></Field>{[['age','سن (اگر تاریخ تولد معلوم نیست)'],['education','وضعیت تحصیل'],['health','وضعیت سلامت مؤثر'],['notes','توضیح']].map(([key,label])=><Field label={label+' عضو '+digits(i+1)} key={key}><input type={key==='age'?'number':'text'} min={0} max={key==='age'?130:undefined} value={m.profile_data?.[key]??''} onChange={e=>setMembers(v=>v.map((x,j)=>j===i?{...x,profile_data:{...x.profile_data,[key]:key==='age'&&e.target.value!==''?Number(e.target.value):e.target.value}}:x))}/></Field>)}</div></fieldset>)}{editable&&<><button className="secondary" onClick={()=>setMembers(v=>[...v,{first_name:'',last_name:'',relationship_code:'CHILD',profile_data:{}}])}>افزودن عضو</button><button disabled={busy||dirty} onClick={()=>void run('/livelihood/families/'+id+'/basic',{version:data.family.version,family:basic,members})}>ذخیره اطلاعات پایه و اعضا</button></>}</section></>}
 {tab==='documents'&&<section className="panel"><h2>مدارک پایه و معیشتی</h2><p>تصویر کارت ملی سرپرست و صفحات شناسنامه خانواده لازم است. نبود فیش حقوقی به‌تنهایی نقص نیست؛ شاهد متناسب با موضوع ثبت کنید.</p>{documents.map((d:Row)=><p key={d.id}><a href={'/api/v1/livelihood/families/'+id+'/documents/'+d.id}>{d.name}</a> · {form.documentKinds[d.category]??'مدرک قبلی'}</p>)}{editable&&<fieldset disabled={busy||dirty}><Field label="عنوان مدرک"><select value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries(data.documentKinds).map(([k,l])=><option key={k} value={k}>{String(l)}</option>)}</select></Field><Field label="نام مدرک (برای سایر عنوان را بنویسید)"><input value={docName} onChange={e=>setDocName(e.target.value)}/></Field><Field label="بارگذاری مدرک — حداکثر ۲۵۶ کیلوبایت"><input type="file" accept=".pdf,.png,.jpg,.jpeg,.txt" onChange={e=>void upload(e.target.files?.[0]).catch(err=>setMessage(err.message))}/></Field></fieldset>}</section>}
 {tab==='livelihood'&&<><p>خانواده در حال حاضر هزینه‌های زندگی خود را از چه منابعی تأمین می‌کند؟ اطلاعات اشتغال زمینه‌ای است و امتیاز مستقلی ندارد.</p>{Object.entries({income:'درآمد و منابع',employment:'اشتغال و توان اقتصادی',expenses:'هزینه‌ها و تعهدات',evidence:'شواهد و توضیحات'}).map(([name,title])=><Rows key={name} name={name} title={title} fields={form.schema[name]} rows={shown[name]??[]} members={shownMembers} disabled={!editable||busy} onChange={rows=>change(name,rows)}/>)}<section className="panel"><h2>جمع‌بندی چهار شاخص معیشت</h2><fieldset disabled={!editable||busy}><div className="filter-grid">{definition.indicators.map((i:Row)=><Field label={i.label} key={i.key}><select value={shown.summaries?.[i.key]??''} onChange={e=>change('summaries',{...p.summaries,[i.key]:e.target.value})}><option value="">ثبت نشده</option><option value="UNKNOWN">نامشخص / نیازمند بررسی</option>{i.options.map((o:Row)=><option key={o.code} value={o.code}>{o.label}</option>)}</select></Field>)}</div><Field label="فوریت موضوع معیشت"><select value={shown.urgency??''} onChange={e=>change('urgency',e.target.value)}><option value="">ثبت نشده</option>{Object.entries(urgency).map(([k,l])=><option key={k} value={k}>{String(l)}</option>)}</select></Field><p>هر نشانه بحرانی فعال، فوریت را دست‌کم «فوری» می‌کند. امتیاز بالا به‌تنهایی نشانه بحرانی نیست.</p>{form.criticalOptions.map((c:string)=><label className="check-field" key={c}><input type="checkbox" checked={shown.critical?.includes(c)??false} onChange={e=>change('critical',e.target.checked?[...(p.critical??[]),c]:(p.critical??[]).filter((x:string)=>x!==c))}/>{c}</label>)}<Field label="اقدام فوری آغازشده / شواهد نشانه بحرانی"><textarea value={shown.criticalAction??''} onChange={e=>change('criticalAction',e.target.value)}/></Field><Field label="جمع‌بندی نهایی سرگروه"><textarea value={shown.notes??''} onChange={e=>change('notes',e.target.value)}/></Field>{form.checks.map((c:string,i:number)=><label key={c} className="check-field"><input aria-label={c} type="checkbox" checked={shown.checks?.[i]??false} onChange={e=>{const v=[...(p.checks??[])];v[i]=e.target.checked;change('checks',Array.from({length:10},(_,j)=>v[j]??false));}}/>{c}</label>)}</fieldset></section></>}
 {(tab==='livelihood'||tab==='result')&&editable&&<button disabled={busy} onClick={()=>void run('/livelihood/families/'+id+'/draft',{payload:p,version:review?.version??0})}>ذخیره و محاسبه</button>}
 {tab==='result'&&<><section className="panel"><h2>نتیجه معیشت و اقتصاد</h2><p>مدل: <bdi>{historical?submission.snapshot.modelVersion:data.model.version}</bdi></p><strong>{result?.score===null?'نامشخص':digits(result?.score)} از ۳۰</strong><p>فوریت: {urgency[result?.urgency]??'ثبت نشده'}</p><p>سلامت، مسکن، آسیب‌پذیری ویژه و آموزش: هنوز ارزیابی نشده / در مرحله بعد</p><p>امتیاز کل ۱۰۰ و سطح A/B/C/D در این نسخه محاسبه نمی‌شوند.</p>{result?.breakdown?.map((b:Row)=><p key={b.key}>{b.label}: {b.selection} — {b.points===null?'نامشخص':digits(b.points)} از {digits(b.max)}</p>)}</section>{editable&&<section className="panel"><h2>کنترل کامل‌بودن</h2>{data.result.missing.length?<ul>{data.result.missing.map((s:string)=><li key={s}>{s}</li>)}</ul>:<p>همه موارد لازم تکمیل شده‌اند.</p>}<button disabled={busy||dirty||!review||!data.result.complete} onClick={()=>void run('/livelihood/families/'+id+'/submit',{version:review.version})}>ارسال برای مدیر اجرایی</button></section>}{data.canReview&&review&&['SUBMITTED','IN_REVIEW'].includes(review.state)&&submission&&submission.id===data.submissions[0]?.id&&<section className="panel"><h2>بررسی مدیر اجرایی</h2><p>تصمیم برای همین نسخه ثابت ثبت می‌شود؛ امتیاز قابل تغییر دستی نیست.</p>{review.state==='SUBMITTED'&&<button disabled={busy} onClick={()=>void run('/livelihood/submissions/'+submission.id+'/begin',{version:review.version})}>شروع بررسی</button>}<Field label="علت برگشت برای تکمیل"><textarea value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="action-row"><button disabled={busy||!result?.complete} onClick={()=>void run('/livelihood/submissions/'+submission.id+'/approve',{version:review.version})}>تأیید ارزیابی معیشت</button><button disabled={busy||!reason.trim()} className="secondary" onClick={()=>void run('/livelihood/submissions/'+submission.id+'/return',{version:review.version,reason})}>برگشت برای تکمیل</button></div></section>}<section className="panel"><h2>تاریخچه</h2>{data.history.map((h:Row,i:number)=><p key={i}>{date(h.occurred_at)} · {h.actor_name} · {({LIVELIHOOD_CREATED:'ایجاد پیش‌نویس',LIVELIHOOD_DRAFT_UPDATED:'ویرایش پیش‌نویس',LIVELIHOOD_SUBMITTED:'ارسال',LIVELIHOOD_RETURNED:'برگشت برای تکمیل',LIVELIHOOD_APPROVED:'تأیید',LIVELIHOOD_REVIEW_STARTED:'شروع بررسی',LIVELIHOOD_BASE_UPDATED:'ویرایش اطلاعات پایه',LIVELIHOOD_DOCUMENT_ADDED:'ثبت مدرک',LIVELIHOOD_CRITICAL_RECORDED:'ثبت نشانه بحرانی',LIVELIHOOD_TEST_SEEDED:'ثبت داده آزمایشی'} as Row)[h.action]??'رویداد ارزیابی'} {h.simulation?'(آزمایش نقش)':''} {h.reason&&' — '+h.reason}</p>)}</section></>}
 </div>}</Screen>}
