import {LivelihoodSnapshot} from '../components/LivelihoodSnapshot';
import {livelihoodStatus,Status} from './LeaderWorkspace';
import {FamilyBaseView} from '../components/FamilyBase';
import {PersianDateInput} from '../components/PersianDateInput';
import {PersianDate} from '../components/PersianDate';
import {AssessmentDomainTabs} from '../components/AssessmentDomainTabs';
import {formatPersianDateTime} from '../utils/persianDate';
import {LivelihoodReview,WorkflowQueue} from './LivelihoodReview';
import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {api,ApiError} from '../api/client';
import {useAuth} from '../auth/AuthProvider';
import {Screen,Field,useData} from './GuideWorkspace';
import {digits} from './vocabulary';
import './Livelihood.css';
type Row=Record<string,any>;
const states:Row=livelihoodStatus;
const urgency:Row={IMMEDIATE:'فوری — حداکثر ۲۴ ساعت',NECESSARY:'ضروری — حداکثر ۷ روز',IMPORTANT:'مهم — حداکثر ۳۰ روز',NON_URGENT:'غیرفوری — برنامه عادی'};
export function LivelihoodFamilies(){const {user}=useAuth(),executive=user?.effectiveRole==='EXECUTIVE_MANAGER',{data,error}=useData('/livelihood/families'),[filter,setFilter]=useState('all');const rows=(data?.families??[]).filter((f:Row)=>filter==='all'||f.status===filter||filter==='INCOMPLETE'&&['INCOMPLETE','UNKNOWN'].includes(f.data_status));return <Screen title={executive?'پایش ارزیابی خانواده‌ها':'خانواده‌ها — ارزیابی معیشت'} error={error}><p>{executive?'پایش وضعیت معیشت؛ تصمیم‌گیری از صف ارزیابی‌های منتظر تأیید انجام می‌شود.':'اطلاعات پایه، اعضا، مدارک و ارزیابی معیشت و اقتصاد نسخه ۱٫۰۰'}</p>{executive&&<Link to="/executive/assessments">ارزیابی‌های منتظر تأیید ←</Link>}<Field label="وضعیت ارزیابی"><select value={filter} onChange={e=>setFilter(e.target.value)}>{Object.entries({all:'همه وضعیت‌ها',NOT_RECORDED:'ثبت نشده',DRAFT:'در حال تکمیل',INCOMPLETE:'ناقص / نامشخص',READY:'آماده ارسال',PENDING:'منتظر تأیید مدیر اجرایی',RETURNED:'برگشتی برای اصلاح',VALID:'معتبر',EXPIRED:'منقضی'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><div className="table-scroll"><table><thead><tr><th>شناسه</th><th>سرپرست</th><th>گروه</th><th>وضعیت معیشت</th><th>عملیات</th></tr></thead><tbody>{rows.map((f:Row)=><tr key={f.id}><td><bdi>{f.family_code}</bdi></td><td>{f.head_name}</td><td>{f.group_name}</td><td><Status value={f.status==='EXPIRED'?'EXPIRED':f.state??'NOT_RECORDED'}/>{['INCOMPLETE','UNKNOWN'].includes(f.data_status)&&<small>اطلاعات ناقص / نیازمند تکمیل</small>}</td><td><Link to={'/workspace/families/'+f.id}>{user?.effectiveRole==='GROUP_LEADER'?'تکمیل / مشاهده پرونده':'مشاهده پرونده'}</Link></td></tr>)}</tbody></table></div>{data&&!rows.length&&<p>خانواده‌ای مطابق این وضعیت وجود ندارد.</p>}</Screen>}
export function LivelihoodQueue(){return <WorkflowQueue/>;}
export function LivelihoodApproved({familyId}:{familyId:string}){const {data}=useData('/livelihood/families/'+familyId);const s=data?.submissions.find((s:Row)=>s.decision==='APPROVED');return s?<section className="panel livelihood-summary"><h2>معیشت و اقتصاد — ارزیابی تأییدشده</h2><p>{digits(s.snapshot.result.score)} از ۳۰ · تأیید: <PersianDate value={s.decided_at} withTime/> · اعتبار تا <PersianDate value={s.valid_until} withTime/></p><p>سلامت، مسکن، آسیب‌پذیری ویژه و آموزش: هنوز ارزیابی نشده / در مرحله بعد</p><p>امتیاز کل و سطح A/B/C/D برای این نسخه محاسبه نشده است.</p><Link to={'/workspace/livelihood/'+familyId}>مشاهده پاسخ‌ها، مدارک و سابقه تأیید</Link></section>:null;}
function Rows({name,title,fields,rows,members,disabled,onChange,onDateValidity}:{name:string;title:string;fields:Row[];rows:Row[];members:Row[];disabled:boolean;onChange:(r:Row[])=>void;onDateValidity:(key:string,valid:boolean)=>void}){return <section className="panel" id={'section-'+name}><h2>{title}</h2>{rows.map((row,index)=><fieldset className="lv-row" key={index} disabled={disabled}><legend>{title} — ردیف {digits(index+1)}</legend><div className="filter-grid">{fields.map(f=><Field label={f.label} key={f.key}>{f.options||f.type==='member'?<select aria-label={title+' '+f.label+' '+(index+1)} value={row[f.key]??''} onChange={e=>onChange(rows.map((r,i)=>i===index?{...r,[f.key]:e.target.value}:r))}><option value="">ثبت نشده</option><option value="UNKNOWN">نامشخص / نیازمند تکمیل</option>{f.type==='member'?members.map(m=><option key={m.id} value={m.id}>{m.first_name} {m.last_name}</option>):f.options.map((o:string)=><option key={o}>{o}</option>)}</select>:f.type==='date'?<PersianDateInput aria-label={title+' '+f.label+' '+(index+1)} value={row[f.key]??''} onChange={value=>onChange(rows.map((r,i)=>i===index?{...r,[f.key]:value}:r))} onValidityChange={valid=>onDateValidity(name+'-'+index+'-'+f.key,valid)}/>:<input aria-label={title+' '+f.label+' '+(index+1)} type={f.type==='number'?'number':'text'} min={f.type==='number'?0:undefined} maxLength={3000} value={row[f.key]??''} onChange={e=>onChange(rows.map((r,i)=>i===index?{...r,[f.key]:f.type==='number'&&e.target.value!==''?Number(e.target.value):e.target.value}:r))}/>}</Field>)}</div>{!disabled&&<button type="button" className="secondary" onClick={()=>onChange(rows.filter((_,i)=>i!==index))}>حذف ردیف {digits(index+1)}</button>}</fieldset>)}{!rows.length&&<p>اطلاعات ثبت نشده است.</p>}{!disabled&&<button type="button" className="secondary" onClick={()=>onChange([...rows,{}])}>افزودن ردیف {title}</button>}</section>}
export function LivelihoodPage(){const {id}=useParams(),{user}=useAuth(),{data,error,refresh}=useData('/livelihood/families/'+id);const [invalidDates,setInvalidDates]=useState<Record<string,boolean>>({});const dateValidity=(key:string,valid:boolean)=>setInvalidDates(v=>v[key]===!valid?v:{...v,[key]:!valid});const [tab,setTab]=useState('livelihood'),[p,setP]=useState<Row>({}),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[reason,setReason]=useState(''),[selected,setSelected]=useState(''),[category,setCategory]=useState('NATIONAL_CARD'),[docName,setDocName]=useState('');
 useEffect(()=>{if(data){setP(data.payload??{});setDirty(false);}},[data?.review?.version,data?.family?.id]);


 const review=data?.review,editable=!!data?.canEdit&&(!review||['DRAFT','READY','RETURNED'].includes(review.state))&&(!!review||!data?.submissions.some((s:Row)=>s.decision==='APPROVED'));
 const submission=data?.submissions.find((s:Row)=>s.id===selected)??data?.submissions[0];
 const historical=!!submission&&(!editable||!!selected);const shown=historical?submission.snapshot.payload:p,shownMembers=historical?submission.snapshot.members:data?.members??[],documents=historical?submission.snapshot.documents:data?.documents??[];
 const form=historical?submission.snapshot.formSchema:data;
 const result=historical?submission.snapshot.result:data?.result,definition=historical?submission.snapshot.modelDefinition:data?.model.definition;
 const change=(key:string,value:any)=>{setP(v=>({...v,[key]:value}));setDirty(true);setMessage('');};
 async function run(url:string,body:unknown){setBusy(true);setMessage('');try{await api(url,{method:'POST',body:JSON.stringify(body)});setMessage('ثبت شد.');refresh();return true;}catch(e){setMessage((e as Error).message+(e instanceof ApiError&&Array.isArray(e.details)?'\n'+e.details.join('\n'):''));return false;}finally{setBusy(false);}}
 async function upload(file?:File){if(!file)return;if(file.size>256*1024){setMessage('حداکثر اندازه مدرک ۲۵۶ کیلوبایت است.');return;}const content=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});await run('/livelihood/families/'+id+'/documents',{name:docName||file.name,category,mediaType:file.type||'text/plain',content});}
 if(user?.effectiveRole==='EXECUTIVE_MANAGER')return data?submission?<LivelihoodReview submissionId={submission.id}/>:<Screen title="مشاهده ارزیابی معیشت"><AssessmentDomainTabs familyId={id!}/><p>هنوز نسخه‌ای برای بررسی ارسال نشده است. تکمیل ارزیابی در اختیار سرگروه است.</p><Link to={'/workspace/families/'+id}>مشاهده پرونده</Link></Screen>:<Screen title="مشاهده ارزیابی معیشت" error={error} loading={!error}>{null}</Screen>;
 return <Screen title="ارزیابی معیشت و اقتصاد" error={error} loading={!data&&!error}>{data&&<div className="livelihood"><AssessmentDomainTabs familyId={id!}/><p><bdi>{data.family.code}</bdi> · {data.family.groupName} · <Status value={review?.state??submission?.decision??'NOT_RECORDED'}/></p>{data.family.code.startsWith('HL-TEST-')&&<p className="quiet-state">پرونده و مدارک کاملاً فرضی Development/Test — اطلاعات واقعی نیست.</p>}{data.canEdit&&!review&&data.submissions.some((s:Row)=>s.decision==='APPROVED')&&<button disabled={busy} onClick={()=>{setSelected('');void run('/livelihood/families/'+id+'/draft',{payload:data.payload,version:0});}}>ایجاد ارزیابی جدید با حفظ نسخه تأییدشده</button>}{review&&['DRAFT','READY','RETURNED'].includes(review.state)&&<p className="family-edit-banner">ارزیابی در حال تکمیل وجود دارد. <button className="secondary" onClick={()=>{setSelected('');setTab('livelihood');}}>ادامه ارزیابی در حال تکمیل</button></p>}{editable&&data.submissions.length>0&&<Field label="مشاهده نسخه تاریخی"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">ارزیابی جاری</option>{data.submissions.map((s:Row)=><option key={s.id} value={s.id}>{'نسخه '+digits(s.revision)+' · '+(states[s.decision]??'ارسال‌شده')}</option>)}</select></Field>}<nav className="subnav assessment-subnav" aria-label="مراحل ارزیابی">{[['documents','مدارک پایه'],['livelihood','معیشت و اقتصاد'],['result','نتیجه و ارسال']].map(([key,label])=><button aria-current={tab===key?'step':undefined} className={tab===key?'':'secondary'} key={key} onClick={()=>setTab(key)}>{label}</button>)}</nav>{message&&<p role="status" className="lv-message">{message}</p>}{dirty&&<p>پاسخ‌های ذخیره‌نشده دارید؛ برای محاسبه و ارسال ابتدا «ذخیره و محاسبه» را بزنید.</p>}{submission?.decision==='RETURNED'&&<p className="lv-message">علت برگشت: {submission.reason}</p>}{historical&&<section className="panel"><p>نمای ثابت ارسال {digits(submission.revision)} · ارسال: <PersianDate value={submission.submitted_at} withTime/> · {states[submission.decision]??states[review?.state]}</p>{submission.decision==='APPROVED'&&<p>تأییدکننده: {submission.approver} · تأیید: <PersianDate value={submission.decided_at} withTime/> · اعتبار تا <PersianDate value={submission.valid_until} withTime/> · {new Date(submission.valid_until)<new Date()?'اعتبار پایان یافته':'معتبر (حوزه معیشت)'}</p>}<Field label="نسخه ارسالی"><select value={submission.id} onChange={e=>setSelected(e.target.value)}>{data.submissions.map((s:Row)=><option key={s.id} value={s.id}>{'\u2066'+formatPersianDateTime(s.submitted_at)+'\u2069'} · {states[s.decision]??'منتظر تصمیم'}</option>)}</select></Field><details><summary>اطلاعات خانواده در زمان ارسال این نسخه</summary><FamilyBaseView family={submission.snapshot.family} members={submission.snapshot.members} asOf={submission.submitted_at}/></details></section>}
 {tab==='documents'&&<section className="panel"><h2>مدارک پایه و معیشتی</h2><p>تصویر کارت ملی سرپرست و صفحات شناسنامه خانواده لازم است. نبود فیش حقوقی به‌تنهایی نقص نیست؛ شاهد متناسب با موضوع ثبت کنید.</p>{documents.map((d:Row)=><p key={d.id}><a href={'/api/v1/livelihood/families/'+id+'/documents/'+d.id}>{d.name}</a> · {form.documentKinds[d.category]??'مدرک قبلی'}</p>)}{editable&&!historical&&<fieldset disabled={busy||dirty}><Field label="عنوان مدرک"><select value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries(data.documentKinds).map(([k,l])=><option key={k} value={k}>{String(l)}</option>)}</select></Field><Field label="نام مدرک (برای سایر عنوان را بنویسید)"><input value={docName} onChange={e=>setDocName(e.target.value)}/></Field><Field label="بارگذاری مدرک — حداکثر ۲۵۶ کیلوبایت"><input type="file" accept=".pdf,.png,.jpg,.jpeg,.txt" onChange={e=>void upload(e.target.files?.[0]).catch(err=>setMessage(err.message))}/></Field></fieldset>}</section>}
 {tab==='livelihood'&&<><nav className="section-index" aria-label="بخش‌های معیشت">{[['income','درآمد و منابع'],['employment','اشتغال و توان اقتصادی'],['expenses','هزینه‌ها و تعهدات'],['evidence','شواهد و توضیحات'],['summary','جمع‌بندی چهار شاخص']].map(([key,label])=><a key={key} href={'#section-'+key}>{label}</a>)}</nav>{historical?<LivelihoodSnapshot snapshot={submission.snapshot}/>:<><p>خانواده در حال حاضر هزینه‌های زندگی خود را از چه منابعی تأمین می‌کند؟ اطلاعات اشتغال زمینه‌ای است و امتیاز مستقلی ندارد.</p>{Object.entries({income:'درآمد و منابع',employment:'اشتغال و توان اقتصادی',expenses:'هزینه‌ها و تعهدات',evidence:'شواهد و توضیحات'}).map(([name,title])=><Rows key={name} name={name} title={title} fields={form.schema[name]} rows={shown[name]??[]} members={shownMembers} disabled={!editable||historical||busy} onChange={rows=>change(name,rows)} onDateValidity={dateValidity}/>)}<section className="panel" id="section-summary"><h2>جمع‌بندی چهار شاخص معیشت</h2><fieldset disabled={!editable||historical||busy}><div className="filter-grid">{definition.indicators.map((i:Row)=><Field label={i.label} key={i.key}><select value={shown.summaries?.[i.key]??''} onChange={e=>change('summaries',{...p.summaries,[i.key]:e.target.value})}><option value="">ثبت نشده</option><option value="UNKNOWN">نامشخص / نیازمند بررسی</option>{i.options.map((o:Row)=><option key={o.code} value={o.code}>{o.label}</option>)}</select></Field>)}</div><Field label="فوریت موضوع معیشت"><select value={shown.urgency??''} onChange={e=>change('urgency',e.target.value)}><option value="">ثبت نشده</option>{Object.entries(urgency).map(([k,l])=><option key={k} value={k}>{String(l)}</option>)}</select></Field><p>هر نشانه بحرانی فعال، فوریت را دست‌کم «فوری» می‌کند. امتیاز بالا به‌تنهایی نشانه بحرانی نیست.</p>{form.criticalOptions.map((c:string)=><label className="check-field" key={c}><input type="checkbox" checked={shown.critical?.includes(c)??false} onChange={e=>change('critical',e.target.checked?[...(p.critical??[]),c]:(p.critical??[]).filter((x:string)=>x!==c))}/>{c}</label>)}<Field label="اقدام فوری آغازشده / شواهد نشانه بحرانی"><textarea value={shown.criticalAction??''} onChange={e=>change('criticalAction',e.target.value)}/></Field><Field label="جمع‌بندی نهایی سرگروه"><textarea value={shown.notes??''} onChange={e=>change('notes',e.target.value)}/></Field>{form.checks.map((c:string,i:number)=><label key={c} className="check-field"><input aria-label={c} type="checkbox" checked={shown.checks?.[i]??false} onChange={e=>{const v=[...(p.checks??[])];v[i]=e.target.checked;change('checks',Array.from({length:10},(_,j)=>v[j]??false));}}/>{c}</label>)}</fieldset></section></>}</>}
 {(tab==='livelihood'||tab==='result')&&editable&&!historical&&<button disabled={busy||Object.values(invalidDates).some(Boolean)} onClick={()=>void run('/livelihood/families/'+id+'/draft',{payload:p,version:review?.version??0})}>ذخیره و محاسبه</button>}
 {tab==='result'&&<><section className="panel"><h2>نتیجه معیشت و اقتصاد</h2><p>مدل: <bdi>{historical?submission.snapshot.modelVersion:data.model.version}</bdi></p><strong>{result?.score===null?'نامشخص':digits(result?.score)} از ۳۰</strong><p>فوریت: {urgency[result?.urgency]??'ثبت نشده'}</p><p>سلامت، مسکن، آسیب‌پذیری ویژه و آموزش: هنوز ارزیابی نشده / در مرحله بعد</p><p>امتیاز کل ۱۰۰ و سطح A/B/C/D در این نسخه محاسبه نمی‌شوند.</p>{result?.breakdown?.map((b:Row)=><p key={b.key}>{b.label}: {b.selection} — {b.points===null?'نامشخص':digits(b.points)} از {digits(b.max)}</p>)}</section>{editable&&!historical&&<section className="panel"><h2>کنترل کامل‌بودن</h2>{data.result.missing.length?<ul>{data.result.missing.map((s:string)=><li key={s}>{s}</li>)}</ul>:<p>همه موارد لازم تکمیل شده‌اند.</p>}<button disabled={busy||dirty||Object.values(invalidDates).some(Boolean)||!review||!data.result.complete} onClick={()=>void run('/livelihood/families/'+id+'/submit',{version:review.version})}>ارسال برای مدیر اجرایی</button></section>}<section className="panel"><h2>تاریخچه</h2>{data.history.map((h:Row,i:number)=><p key={i}><PersianDate value={h.occurred_at} withTime/> · {h.actor_name} · {({LIVELIHOOD_CREATED:'ایجاد پیش‌نویس',LIVELIHOOD_DRAFT_UPDATED:'ویرایش پیش‌نویس',LIVELIHOOD_SUBMITTED:'ارسال',LIVELIHOOD_RESUBMITTED:'ارسال مجدد پس از اصلاح',LIVELIHOOD_SNAPSHOT_VALIDATED:'ثبت اعتبار نسخه معیشت',LIVELIHOOD_RETURNED:'برگشت برای تکمیل',LIVELIHOOD_APPROVED:'تأیید',LIVELIHOOD_REVIEW_STARTED:'شروع بررسی',LIVELIHOOD_BASE_UPDATED:'ویرایش اطلاعات پایه',LIVELIHOOD_DOCUMENT_ADDED:'ثبت مدرک',LIVELIHOOD_CRITICAL_RECORDED:'ثبت نشانه بحرانی',LIVELIHOOD_TEST_SEEDED:'ثبت داده آزمایشی'} as Row)[h.action]??'رویداد ارزیابی'} {h.simulation?'(آزمایش نقش)':''} {h.reason&&' — '+h.reason}</p>)}</section></>}
 </div>}</Screen>}
