import {AssessmentDomainTabs} from '../components/AssessmentDomainTabs';
import {formatPersianDate,formatPersianDateTime as date} from '../utils/persianDate';
import {useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {api,ApiError} from '../api/client';
import {Screen,Field,useData,fa} from './GuideWorkspace';
import {Status,Score,operationalGroup,urgencyLabel} from './LeaderWorkspace';
import {Modal} from '../components/WorkspaceNavigation';
import {digits} from './vocabulary';
import './Livelihood.css';
type Row=Record<string,any>;
const stateLabel:Row={SUBMITTED:'منتظر تأیید مدیر اجرایی',IN_REVIEW:'در حال بررسی مدیر اجرایی',RETURNED:'برگشتی برای اصلاح',APPROVED:'معتبر'};
const relation:Row={HEAD:'سرپرست',SPOUSE:'همسر',CHILD:'فرزند',PARENT:'والد',SIBLING:'خواهر/برادر',OTHER:'سایر'};
const show=(v:any)=>v===null||v===undefined||v===''?'ثبت نشده':v==='UNKNOWN'?'نامشخص':String(v);
export function WorkflowQueue({followups=false}:{followups?:boolean}){
 const {data,error}=useData('/livelihood/queue');
 return <Screen title={followups?'پیگیری‌های من':'ارزیابی‌های منتظر تأیید'} error={error} loading={!data&&!error}>
 <div className="livelihood"><p>نسخه‌های ارسالی معیشت برای تصمیم مدیر اجرایی؛ نسخه ارسالی قابل ویرایش نیست.</p>
 <section className="panel"><div className="table-scroll"><table><thead><tr><th>خانواده / شناسه</th><th>گروه</th><th>سرگروه / ارسال‌کننده</th><th>وضعیت</th><th>زمان ارسال</th><th>اقدام</th></tr></thead><tbody>{data?.items.map((s:Row)=><tr key={s.submission_id}><td><strong>{s.head_name||s.family_code}</strong><small><bdi>{s.family_code}</bdi></small></td><td>{operationalGroup(s.group_name)}</td><td>{s.leader_name}<small>ارسال‌کننده: {s.sender_name}</small></td><td>{stateLabel[s.state]}{s.revision>1&&<small className="workflow-resubmitted">ارسال مجدد پس از اصلاح · نسخه {digits(s.revision)}</small>}</td><td>{date(s.submitted_at)}</td><td><Link to={'/executive/assessments/'+s.submission_id}>بررسی ارزیابی</Link></td></tr>)}</tbody></table></div>{data&&!data.items.length&&<p className="quiet-state">ارزیابی منتظر بررسی وجود ندارد.</p>}</section></div>
 </Screen>;
}
export function LivelihoodReview({submissionId}:{submissionId?:string}){
 const route=useParams(),sid=submissionId??route.submissionId,{data,error,refresh}=useData('/livelihood/submissions/'+sid);
 const [returning,setReturning]=useState(false),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[blocked,setBlocked]=useState<string[]>([]);
 const s:Row|undefined=data?.submission,snapshot=s?.snapshot??{},f=snapshot.family??{},p=snapshot.payload??{},result=data?.result,previous=data?.previous;
 const missing=[...new Set<string>([...(result?.missing??[]),...blocked])];
 async function decide(action:'approve'|'return'){
  if(!s)return;setBusy(true);setMessage('');setBlocked([]);
  try{await api('/livelihood/submissions/'+s.id+'/'+action,{method:'POST',body:JSON.stringify({version:s.version,...(action==='return'?{reason}:{})})});setReturning(false);setReason('');setMessage(action==='approve'?'ارزیابی تأیید شد؛ نسخه معتبر ثبت شد.':'ارزیابی با دلیل برای تکمیل بازگردانده شد.');refresh();window.dispatchEvent(new Event('lahout-notifications-changed'));}
  catch(e){setMessage((e as Error).message);if(e instanceof ApiError&&Array.isArray(e.details))setBlocked(e.details);}
  finally{setBusy(false);}
 }
 return <Screen title="بررسی ارزیابی معیشت" error={error} loading={!data&&!error}>{s&&<div className="livelihood executive-review"><AssessmentDomainTabs familyId={s.family_id}/>
 <section className="panel"><header className="workflow-header"><div><h2>{f.headName??'خانواده'}</h2><bdi>{f.code}</bdi></div><strong className="leader-status">{s.decision==='APPROVED'&&new Date(s.valid_until)<new Date()?'منقضی':stateLabel[s.decision??s.state]}</strong><Link to={'/workspace/families/'+s.family_id+'?returnTo=%2Fexecutive'}>مشاهده پرونده</Link></header>
 <div className="workflow-facts"><p><small>گروه</small>{operationalGroup(f.groupName)}</p><p><small>سرگروه</small>{snapshot.leaderName??s.sender_name}</p><p><small>ارسال‌کننده</small>{s.sender_name}{snapshot.simulation?' (آزمایش نقش)':''}</p><p><small>زمان ارسال</small>{date(s.submitted_at)}</p><p><small>نسخه ارسالی</small>{digits(s.revision)}</p><p><small>فوریت موضوع</small>{urgencyLabel[result?.urgency]??'ثبت نشده'}</p></div>
 <p className="quiet-state">اطلاعات این صفحه از نسخه ثابت ارسالی خوانده می‌شود. تکمیل فرم و تغییر امتیاز در اختیار مدیر اجرایی نیست.</p>
 {s.decision==='APPROVED'&&<p className="workflow-success">تأییدکننده: {s.approver} · تاریخ تأیید: {date(s.decided_at)} · اعتبار تا: {date(s.valid_until)} (یک سال از تأیید)</p>}{s.reason&&<p className="error-banner">دلیل بازگشت: {s.reason}</p>}</section>
 <section className="panel"><h2>نتیجه چهار شاخص معیشت</h2><strong className="workflow-score"><Score value={result?.score??null}/></strong><div className="workflow-indicators">{result?.breakdown?.map((b:Row)=><div key={b.key}><h3>{b.label}</h3><p>{b.selection}</p><strong>{b.points==null?'نامشخص':digits(b.points)} از {digits(b.max)}</strong></div>)}</div><p className="quiet-state">این نتیجه فقط حوزه معیشت است؛ امتیاز نهایی پنج حوزه محاسبه نمی‌شود.</p></section>
 <div className="workflow-two-columns"><section className="panel"><h2>اطلاعات پایه و اعضای نسخه ارسالی</h2><div className="workflow-facts">{[['neighborhood','محله'],['residenceType','نوع سکونت'],['formedOn','تاریخ تشکیل پرونده'],['source','منبع اطلاعات اولیه']].map(([k,l])=><p key={k}><small>{l}</small>{k==='formedOn'?formatPersianDate(f[k]):show(f[k])}</p>)}</div><div className="table-scroll"><table><thead><tr><th>عضو / نسبت</th><th>شناسه / تماس</th><th>سن / تولد</th><th>وضعیت تحصیل / سلامت</th></tr></thead><tbody>{(snapshot.members??[]).map((m:Row)=><tr key={m.id}><td>{m.first_name} {m.last_name}<small>{relation[m.relationship_code]??'ثبت نشده'}</small></td><td><bdi>{show(m.national_id)}</bdi><small><bdi>{show(m.mobile)}</bdi></small></td><td>{m.birth_date?formatPersianDate(m.birth_date):show(m.profile_data?.age)}</td><td>{show(m.profile_data?.education)}<small>{show(m.profile_data?.health)}</small></td></tr>)}</tbody></table></div></section>
 <section className="panel"><h2>مدارک و شواهد</h2>{(snapshot.documents??[]).map((d:Row)=><p key={d.id}><a href={'/api/v1/livelihood/families/'+s.family_id+'/documents/'+d.id}>{d.name}</a><small>{snapshot.formSchema?.documentKinds?.[d.category]??'مدرک ثبت‌شده'}</small></p>)}{!snapshot.documents?.length&&<p>مدرکی ثبت نشده است.</p>}{(p.evidence??[]).map((e:Row,i:number)=><div className="workflow-evidence" key={i}><strong>{show(e.source)}</strong><p>{show(e.description)}</p></div>)}</section></div>
 <section className="panel"><h2>جمع‌بندی سرگروه و نشانه‌های بحرانی</h2><p className="workflow-text">{show(p.notes)}</p>{result?.critical?.length?<><ul>{result.critical.map((c:string)=><li key={c}>{c}</li>)}</ul><p>اقدام فوری: {show(p.criticalAction)}</p></>:<p>نشانه بحرانی فعال در نسخه ارسالی ثبت نشده است.</p>}</section>
 <details className="panel"><summary>جزئیات پاسخ‌های ارسالی معیشت</summary>{Object.entries({income:'درآمد و منابع',employment:'اشتغال و توان اقتصادی',expenses:'هزینه‌ها و تعهدات'}).map(([key,title])=><section key={key}><h3>{title}</h3>{(p[key]??[]).map((row:Row,i:number)=><div className="workflow-facts workflow-evidence" key={i}>{(snapshot.formSchema?.schema?.[key]??[]).filter((field:Row)=>!field.optional||row[field.key]).map((field:Row)=><p key={field.key}><small>{field.label}</small>{field.type==='member'?(snapshot.members??[]).filter((m:Row)=>m.id===row[field.key]).map((m:Row)=>m.first_name+' '+m.last_name).join('، ')||'ثبت نشده':show(row[field.key])}</p>)}</div>)}</section>)}</details>
 {previous&&<section className="panel"><h2>خلاصه نسخه معتبر پیشین</h2><p>تأیید: {date(previous.decided_at)} · اعتبار تا {date(previous.valid_until)} · {new Date(previous.valid_until)<new Date()?'اعتبار پایان یافته':'هنوز معتبر'}</p><p>امتیاز پیشین: <Score value={previous.result?.score??null}/> · امتیاز این ارسال: <Score value={result?.score??null}/></p><ul>{(result?.breakdown??[]).filter((b:Row)=>previous.result?.breakdown?.find((old:Row)=>old.key===b.key)?.points!==b.points).map((b:Row)=><li key={b.key}>{b.label}: {show(previous.result?.breakdown?.find((old:Row)=>old.key===b.key)?.points)} ← {show(b.points)}</li>)}</ul><p>فوریت پیشین: {urgencyLabel[previous.result?.urgency]??'ثبت نشده'} · فوریت این ارسال: {urgencyLabel[result?.urgency]??'ثبت نشده'}</p><small>نسخه پیشین و تاریخچه آن محفوظ می‌مانند.</small></section>}
 {message&&<p role="status" className="lv-message">{message}</p>}
 {data?.canDecide&&<section className="panel workflow-decisions"><h2>تصمیم مدیر اجرایی</h2>{missing.length>0&&<div className="error-banner" role="alert"><strong>این ارزیابی هنوز قابل تأیید نیست.</strong><ul>{missing.map(m=><li key={m}>{m}</li>)}</ul></div>}<div className="action-row"><button disabled={busy||!result?.complete||missing.length>0} onClick={()=>void decide('approve')}>تأیید ارزیابی</button><button className="secondary" disabled={busy} onClick={()=>setReturning(true)}>بازگشت برای تکمیل</button></div></section>}
 {!data?.canDecide&&!s.decision&&<p className="quiet-state">این نسخه دیگر قابل تصمیم‌گیری نیست؛ ارسال جدیدتر را از صف بررسی باز کنید.</p>}
 <details className="panel" open><summary>تاریخچه همین چرخه ارزیابی</summary>{data?.history.map((h:Row,i:number)=><p key={i}>{date(h.occurred_at)} · {fa(h.action)} · {h.actor_name} · {fa(h.effective_role)}{h.simulation?' (آزمایش نقش)':''}{h.reason&&' — '+h.reason}</p>)}{!data?.history.length&&<p>رویدادی ثبت نشده است.</p>}</details>
 {returning&&<Modal title="بازگشت برای تکمیل" onClose={()=>{if(!busy)setReturning(false);}}><form onSubmit={e=>{e.preventDefault();void decide('return');}}><p>دلیل مشخص اصلاح برای سرگروه و در تاریخچه ثبت می‌شود.</p><Field label="دلیل بازگشت (الزامی)"><textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></Field><button disabled={busy||!reason.trim()} type="submit">ثبت بازگشت برای تکمیل</button>{message&&<p role="alert">{message}</p>}</form></Modal>}
 </div>}</Screen>;
}
