import {useRef,useState} from 'react';
import {api,apiFile} from '../api/client';
import {Screen,Field,useData} from './GuideWorkspace';
const tabs=[['families','خانواده‌ها'],['supports','حمایت‌ها'],['stipends','مقرری‌ها'],['distribution','توزیع'],['groups','گروه‌ها'],['performance','افراد و عملکرد'],['sponsor','گزارش حامی']];
const value=(v:any):string=>v==null?'—':typeof v==='object'?JSON.stringify(v):String(v);
export function MonitoringPage(){
 const [tab,setTab]=useState('families'),[sponsor,setSponsor]=useState('families'),[filters,setFilters]=useState<Record<string,string>>({}),[fields,setFields]=useState<string[]>([]),[title,setTitle]=useState('گزارش مدیریتی کانون'),[orientation,setOrientation]=useState('landscape'),[html,setHtml]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const dataset=tab==='sponsor'?sponsor:tab,options=useData('/monitoring/options'),data=useData('/monitoring/data/'+dataset+'?'+new URLSearchParams(filters)),frame=useRef<HTMLIFrameElement>(null);
 const change=(next:string)=>{setTab(next);setFilters({});setFields([]);setHtml('');};
 const filter=(key:string,v:string)=>setFilters(old=>{const n={...old};if(v)n[key]=v;else delete n[key];return n;});
 const select=(key:string,label:string,rows:any[]) => <Field key={key} label={label}><select value={filters[key]??''} onChange={e=>filter(key,e.target.value)}><option value="">همه</option>{rows.map(r=><option key={r.id??r.name} value={r.id??r.name}>{r.name}</option>)}</select></Field>;
 const output=async(format:string)=>{setBusy(true);setError('');try{const body={dataset,filters,fields,title,orientation,format};if(format==='preview'){const r=await api<{html:string}>('/monitoring/export',{method:'POST',body:JSON.stringify(body)});setHtml(r.html);}else{const blob=await apiFile('/monitoring/export',body),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='lahout-report.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Screen title="گزارش‌ها و پایش" error={error||data.error}><nav className="report-tabs" aria-label="حوزه گزارش">{tabs.map(([key,label])=><button key={key} className={tab===key?'selected':''} onClick={()=>change(key)}>{label}</button>)}</nav>{tab==='sponsor'&&<Field label="حوزه گزارش حامی"><select value={sponsor} onChange={e=>{setSponsor(e.target.value);setFields([]);setFilters({});setHtml('');}}>{tabs.filter(t=>t[0]!=='sponsor').map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field>}
 <div className="filter-grid"><Field label="جستجو"><input value={filters.q??''} onChange={e=>filter('q',e.target.value)}/></Field>{dataset!=='groups'&&select('group','گروه',options.data?.groups??[])}{['families','supports','stipends','distribution'].includes(dataset)&&select('family','خانواده',options.data?.families??[])}{['families','supports'].includes(dataset)&&select('supportType','نوع حمایت',options.data?.supportTypes??[])}{['families','distribution'].includes(dataset)&&select('plan','طرح توزیع',options.data?.plans??[])}{dataset==='families'&&<>{select('level','سطح نیاز',['A','B','C','D'].map(id=>({id,name:id})))}<Field label="حداقل امتیاز"><input type="number" value={filters.minScore??''} onChange={e=>filter('minScore',e.target.value)}/></Field><Field label="حداکثر امتیاز"><input type="number" value={filters.maxScore??''} onChange={e=>filter('maxScore',e.target.value)}/></Field></>}{dataset==='performance'&&<>{select('person','فرد',options.data?.people??[])}{select('role','نقش',options.data?.roles??[])}</>}{select('state','وضعیت',[...new Set((data.data?.rows??[]).map((r:any)=>r.case_status??r.status).filter(Boolean))].map(id=>({id,name:String(id)})))}<Field label={dataset==='performance'?'ایجاد حساب از تاریخ':'از تاریخ'}><input type="date" value={filters.from??''} onChange={e=>filter('from',e.target.value)}/></Field><Field label={dataset==='performance'?'ایجاد حساب تا تاریخ':'تا تاریخ'}><input type="date" value={filters.to??''} onChange={e=>filter('to',e.target.value)}/></Field>{dataset==='families'&&<>{select('urgency','فوریت',['NORMAL','HIGH','CRITICAL'].map(id=>({id,name:{NORMAL:'عادی',HIGH:'بالا',CRITICAL:'فوری'}[id]})))}{select('research','وضعیت تحقیق',['NOT_STARTED','PENDING','COMPLETED','OVERDUE'].map(id=>({id,name:{NOT_STARTED:'شروع نشده',PENDING:'در انتظار',COMPLETED:'انجام‌شده',OVERDUE:'معوق'}[id]})))}{select('support','وضعیت حمایت',['NONE','PENDING','COMPLETED'].map(id=>({id,name:{NONE:'ثبت نشده',PENDING:'در انتظار',COMPLETED:'انجام‌شده'}[id]})))}<Field label="آخرین تحقیق تا تاریخ"><input type="date" value={filters.lastResearch??''} onChange={e=>filter('lastResearch',e.target.value)}/></Field>{select('domain','حوزه نیاز',[...new Set((data.data?.rows??[]).flatMap((r:any)=>Object.keys(r.domains??{})))].map(id=>({id,name:String(id)})))}<label><input type="checkbox" checked={filters.review==='true'} onChange={e=>filter('review',e.target.checked?'true':'')}/>نیازمند بازبینی</label><label><input type="checkbox" checked={filters.alert==='true'} onChange={e=>filter('alert',e.target.checked?'true':'')}/>هشدار باز</label></>}<Field label="مرتب‌سازی"><select value={filters.sort??''} onChange={e=>filter('sort',e.target.value)}><option value="">پیش‌فرض</option>{data.data?.fields.filter((f:any)=>dataset!=='performance'||!['visits','completed_supports','completed_research'].includes(f.key)).map((f:any)=><option key={f.key} value={f.key}>{f.label}</option>)}</select></Field></div>
 {dataset==='performance'&&<p>عملکرد بر پایه درصدها و بار مسئولیت نمایش داده می‌شود. فیلتر گروه، افراد مرتبط را انتخاب می‌کند؛ شاخص هر فرد همه مسئولیت‌های او را پوشش می‌دهد. داده ثبت‌نشده به معنی عملکرد صفر نیست.</p>}
 {data.data&&<><section className="panel"><h2>نمای آماری و تجمیعی</h2><p>تعداد ردیف‌های منطبق: {data.data.aggregate.count}</p><div className="aggregate-grid">{Object.entries(data.data.aggregate).filter(([k])=>k!=='count').map(([key,v]:any)=><div key={key}><strong>{data.data!.fields.find((f:any)=>f.key===key)?.label??key}</strong><p>{typeof v==='object'&&v!==null?('average' in v?(key.endsWith('_pct')||key.startsWith('avg_')?'میانگین: '+value(v.average):'مجموع: '+value(v.sum)+' · میانگین: '+value(v.average)):value(v)):value(v)}</p></div>)}</div></section><section className="panel"><h2>ساخت خروجی</h2><Field label="عنوان گزارش"><input value={title} onChange={e=>setTitle(e.target.value)} required/></Field><Field label="جهت صفحه A4"><select value={orientation} onChange={e=>setOrientation(e.target.value)}><option value="landscape">افقی</option><option value="portrait">عمودی</option></select></Field><p>فیلدهای قابل ارائه را انتخاب کنید؛ هیچ فیلدی از پیش انتخاب نشده است.</p><button type="button" onClick={()=>setFields(data.data!.fields.map((f:any)=>f.key))}>انتخاب همه</button> <button type="button" onClick={()=>setFields([])}>پاک کردن انتخاب</button><div className="field-picker">{data.data!.fields.map((f:any)=><label key={f.key}><input type="checkbox" checked={fields.includes(f.key)} onChange={e=>setFields(old=>e.target.checked?[...old,f.key]:old.filter(k=>k!==f.key))}/>{f.label}</label>)}</div><div className="action-row">{[['preview','پیش‌نمایش A4'],['pdf','دریافت PDF'],['xlsx','دریافت Excel']].map(([format,label])=><button key={format} disabled={busy||!fields.length||!title.trim()} onClick={()=>void output(format)}>{label}</button>)}</div></section><details className="panel" open={dataset==='groups'||dataset==='performance'}><summary>ردیف‌های گزارش ({data.data.rows.length})</summary><div className="table-scroll"><table><thead><tr>{data.data!.fields.map((f:any)=><th key={f.key}>{f.label}</th>)}</tr></thead><tbody>{data.data.rows.map((r:any,i:number)=><tr key={i}>{data.data!.fields.map((f:any)=><td key={f.key}>{value(r[f.key])}</td>)}</tr>)}</tbody></table></div></details></>}
 {html&&<section className="panel"><h2>پیش‌نمایش خروجی</h2><button onClick={()=>frame.current?.contentWindow?.print()}>چاپ A4</button><iframe ref={frame} title="پیش‌نمایش گزارش" className="report-preview" srcDoc={html}/></section>}</Screen>;
}
