import {translate} from './vocabulary';
import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api/client';
import {useAuth} from '../auth/AuthProvider';
type Row=Record<string,any>;
const when=(v:unknown)=>v?new Date(String(v)).toLocaleString('fa-IR'):'—';
export function ContextAlerts({alerts,refresh}:{alerts:Row[],refresh:()=>void}){const {user}=useAuth();const prefix=user?.roles.some(r=>r.roleCode==='SUPREME_GUIDE')?'/guide':'/workspace';const [selected,setSelected]=useState(''),[action,setAction]=useState(''),[result,setResult]=useState(''),[done,setDone]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function progress(a:Row,state:string){setBusy(true);setError('');try{await api('/shared/alerts/'+a.id+'/progress',{method:'POST',body:JSON.stringify({state,action,result,actionCompleted:done})});setSelected('');refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}return <section className="panel"><h2>هشدارهای مرتبط</h2>{!alerts.length&&<p>هشدار مرتبطی ثبت نشده است.</p>}{alerts.map(a=><details className="context-alert" key={a.id}><summary><span className={'badge-'+(a.severity==='CRITICAL'?'red':a.severity==='VERY_IMPORTANT'||a.severity==='IMPORTANT'?'amber':'info')}>{translate(a.severity)}</span> {a.subject} · {translate(a.state??(a.closed_at?'RESOLVED':'OPEN'))}</summary><p>مسئول: {a.owner_name??'نیازمند تعیین مسئول'}</p><p>{when(a.created_at)}{a.escalated?' · ارجاع‌شده به راهبر':''}</p>{a.trigger_detected===false&&<p>نشانه دیگر مشاهده نشده است؛ نتیجه واقعی رسیدگی هنوز لازم است.</p>}{a.family_id&&<Link to={prefix+'/families/'+a.family_id}>مشاهده پرونده خانواده</Link>}{a.canProgress&&a.state==='OPEN'&&<button disabled={busy} onClick={()=>void progress(a,'ACKNOWLEDGED')}>پذیرش مسئولیت</button>}{a.canProgress&&a.state==='ACKNOWLEDGED'&&<button disabled={busy} onClick={()=>void progress(a,'IN_PROGRESS')}>شروع رسیدگی</button>}{a.canResolve&&a.state==='IN_PROGRESS'&&<button onClick={()=>setSelected(a.id)}>ثبت نتیجه رسیدگی</button>}{a.result&&<p>نتیجه: {a.result}</p>}{selected===a.id&&<form className="compact-form" onSubmit={e=>{e.preventDefault();void progress(a,'RESOLVED');}}><label>اقدام انجام‌شده<textarea required value={action} onChange={e=>setAction(e.target.value)}/></label><label>نتیجه<textarea required value={result} onChange={e=>setResult(e.target.value)}/></label><label><input type="checkbox" required checked={done} onChange={e=>setDone(e.target.checked)}/>اقدام انجام شد</label><button disabled={busy||!done}>ثبت نتیجه نهایی</button></form>}</details>)}{error&&<p role="alert">{error}</p>}</section>;}
export function ContextNote({context,refresh}:{context:Row,refresh:()=>void}){const [type,setType]=useState('MESSAGE'),[subject,setSubject]=useState(''),[body,setBody]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <details className="panel"><summary>ثبت یادداشت، تذکر یا یادآوری</summary><form className="compact-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await api('/cases/notes',{method:'POST',body:JSON.stringify({...context,type,subject,body})});setSubject('');setBody('');refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>نوع یادداشت<select value={type} onChange={e=>setType(e.target.value)}><option value="REMINDER">تذکر / پیگیری</option><option value="WARNING">تذکر</option><option value="MESSAGE">پیام</option><option value="COORDINATION">پیگیری و سابقه هماهنگی</option></select></label><label>موضوع یادداشت<input required maxLength={200} value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>شرح یادداشت<textarea required maxLength={4000} value={body} onChange={e=>setBody(e.target.value)}/></label><button disabled={busy}>ثبت یادداشت</button>{error&&<p role="alert">{error}</p>}</form></details>;}
export function PersonContextPanel({personId,data,refresh}:{personId:string,data:Row,refresh:()=>void}){const {user}=useAuth();useEffect(()=>{for(const n of data.notes??[])if(n.unread)void api('/workspace/items/'+n.id+'/seen',{method:'POST'}).catch(()=>{});},[personId,user?.accountId]);return <><ContextAlerts alerts={data.alerts??[]} refresh={refresh}/><ContextNote context={{personId}} refresh={refresh}/><section className="panel"><h2>پیام‌ها، هماهنگی‌ها و سوابق مهم</h2>{!(data.notes??[]).length&&<p>سابقه‌ای ثبت نشده است.</p>}{data.notes?.map((n:Row)=><details key={n.id}><summary>{n.subject} · {when(n.created_at)}</summary><p className="preserve-text">{n.body}</p>{n.result&&<p>نتیجه: {n.result}</p>}</details>)}</section></>;}
