import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api/client';
import {useAuth} from '../auth/AuthProvider';
type Row=Record<string,any>;
const when=(v:unknown)=>v?new Date(String(v)).toLocaleString('fa-IR'):'—';
export function ContextAlerts({alerts,refresh}:{alerts:Row[],refresh:()=>void}){const [selected,setSelected]=useState(''),[result,setResult]=useState(''),[done,setDone]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <section className="panel"><h2>هشدارها و پیگیری‌ها</h2>{!alerts.length&&<p>هشدار مرتبطی ثبت نشده است.</p>}{alerts.map(a=><article className="context-alert" key={a.id}><span className={'badge-'+(a.severity==='RED'?'red':a.severity==='AMBER'?'amber':'info')}>{a.severity==='RED'?'هشدار جدی':a.severity==='AMBER'?'پیگیری':'اطلاع'}</span><strong>{a.subject}</strong><p>{a.body}</p><small>{when(a.created_at)} · {a.closed_at?'رسیدگی‌شده':'باز'}</small>{!a.closed_at&&<button className="secondary" onClick={()=>{setSelected(a.id);setResult('');setDone(false);}}>ثبت نتیجه رسیدگی</button>}{selected===a.id&&!a.closed_at&&<form className="compact-form" onSubmit={async e=>{e.preventDefault();if(!done||!result.trim()||busy)return;setBusy(true);setError('');try{await api('/cases/alerts/'+a.id+'/resolve',{method:'POST',body:JSON.stringify({result,actionCompleted:done})});setSelected('');refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>نتیجه رسیدگی<textarea required maxLength={4000} value={result} onChange={e=>setResult(e.target.value)}/></label><label className="check-field"><input type="checkbox" required checked={done} onChange={e=>setDone(e.target.checked)}/>اقدام لازم انجام شده است</label><button disabled={busy||!done}>ثبت نتیجه و رفع هشدار</button></form>}</article>)}{error&&<p role="alert">{error}</p>}</section>;}
export function ContextNote({context,refresh}:{context:Row,refresh:()=>void}){const [type,setType]=useState('REMINDER'),[subject,setSubject]=useState(''),[body,setBody]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <details className="panel"><summary>ثبت تذکر، هشدار یا یادداشت مرتبط</summary><form className="compact-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await api('/cases/notes',{method:'POST',body:JSON.stringify({...context,type,subject,body})});setSubject('');setBody('');refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>نوع یادداشت<select value={type} onChange={e=>setType(e.target.value)}><option value="REMINDER">تذکر / پیگیری</option><option value="ALERT">هشدار جدی</option><option value="MESSAGE">پیام</option><option value="COORDINATION">سابقه هماهنگی</option></select></label><label>موضوع یادداشت<input required maxLength={200} value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>شرح یادداشت<textarea required maxLength={4000} value={body} onChange={e=>setBody(e.target.value)}/></label><button disabled={busy}>ثبت یادداشت</button>{error&&<p role="alert">{error}</p>}</form></details>;}
export function PersonContextPanel({personId,data,refresh}:{personId:string,data:Row,refresh:()=>void}){const {user}=useAuth();useEffect(()=>{for(const n of data.notes??[])if(n.unread)void api('/workspace/items/'+n.id+'/seen',{method:'POST'}).catch(()=>{});},[personId,user?.accountId]);return <><ContextAlerts alerts={data.alerts??[]} refresh={refresh}/><ContextNote context={{personId}} refresh={refresh}/><section className="panel"><h2>پیام‌ها، هماهنگی‌ها و سوابق مهم</h2>{!(data.notes??[]).length&&<p>سابقه‌ای ثبت نشده است.</p>}{data.notes?.map((n:Row)=><details key={n.id}><summary>{n.subject} · {when(n.created_at)}</summary><p className="preserve-text">{n.body}</p>{n.result&&<p>نتیجه: {n.result}</p>}</details>)}</section><section className="panel"><h2>درخواست‌های مرتبط با شخص</h2>{!data.permissions?.length&&<p>مجوز موردی مرتبط ثبت نشده است.</p>}{data.permissions?.map((v:Row)=><p key={v.id}><Link to={'/guide/permissions/'+v.id}>{v.subject}</Link> · {v.decision==='APPROVED'?'تأیید':v.decision==='NOT_APPROVED'?'عدم تأیید':'منتظر تصمیم'}</p>)}</section></>;}
