import {useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {useAuth} from '../auth/AuthProvider';
import {Screen,useData,Field,date,fa} from './GuideWorkspace';
import {roleLabels,roleHomes,displayName} from '../components/rolePresentation';
import {digits} from './vocabulary';
import './TechnicalWorkspace.css';
type Row=Record<string,any>;
const accountTypes:Record<string,string>={TEST:'آزمایشی',LEGACY:'توسعه قدیمی',OPERATIONAL:'عملیاتی'};
function Badge({children,tone='purple'}:{children:React.ReactNode;tone?:string}){return <span className={'tech-badge '+tone}>{children}</span>;}
function Mark({kind='person'}:{kind?:string}){return <span className="tech-mark" aria-hidden="true"><svg viewBox="0 0 32 32" width="28" height="28" fill="none" stroke="currentColor" strokeWidth="2">{kind==='person'?<><circle cx="16" cy="10" r="5"/><path d="M6 28v-4a10 10 0 0 1 20 0v4"/></>:kind==='database'?<><ellipse cx="16" cy="7" rx="11" ry="4"/><path d="M5 7v18c0 6 22 6 22 0V7M5 16c0 6 22 6 22 0"/></>:kind==='status'?<path d="M2 17h7l4-10 6 19 4-9h7"/>:<><rect x="5" y="5" width="22" height="18" rx="3"/><path d="M10 28h12M16 23v5M10 12h12M10 17h8"/></>}</svg></span>;}
const environmentLabels:Record<string,string>={development:'توسعه محلی',test:'تست',staging:'محیط آزمایشی',production:'عملیاتی'};
function HealthCards({data}:{data:Row}){return <section className="role-card"><header><h2>وضعیت فنی سامانه</h2><Link to="/technical/health">جزئیات سلامت سامانه ←</Link></header><div className="role-stat-grid tech-health-grid">{[
 ['سرویس سامانه',data.service==='UP'?'در دسترس':'بررسی ناموفق','پاسخ Backend / API','status',data.service==='UP'],
 ['پایگاه داده',data.database==='CONNECTED'?'متصل':'بررسی ناموفق','اتصال PostgreSQL','database',data.database==='CONNECTED'],
 ['نسخه نرم‌افزار',data.version??'ثبت نشده','نسخه بسته فعلی برای گزارش خطا','version',false],
 ['محیط اجرا',environmentLabels[data.environment]??'ثبت نشده','محیط پیکربندی‌شده سرویس','environment',false]
 ].map(([title,value,hint,kind,healthy])=><article className={'tech-health '+(healthy?'healthy':'')} key={String(title)}><Mark kind={String(kind)}/><span>{title}</span><strong dir={kind==='version'?'ltr':undefined}>{value}</strong><small>{hint}</small><small>آخرین بررسی: {date(data.checkedAt)}</small></article>)}</div></section>;}
function SimulationCards({data}:{data:Row}){
 const {simulate}=useAuth(),navigate=useNavigate();const [selected,setSelected]=useState(''),[group,setGroup]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function enter(role:string){setBusy(true);setError('');void simulate(role,['GROUP_LEADER','HELPER'].includes(role)?group:undefined).then(()=>navigate(roleHomes[role])).catch(e=>setError(e.message)).finally(()=>setBusy(false));}
 return <section className="role-card"><h2>ورود آزمایشی به داشبورد نقش‌ها</h2><p className="tech-warning" role="note">در حالت آزمایش، عملیات مجاز واقعی است و با هویت شما در تاریخچه ثبت می‌شود.</p>{error&&<p role="alert" className="error-banner">{error}</p>}<div className="tech-role-grid">{data.roles.map((r:Row)=>{const scoped=['GROUP_LEADER','HELPER'].includes(r.code);return <article className="tech-role-card" key={r.code}><Mark/><h3>{r.label}</h3>{scoped?<><button className="secondary" aria-expanded={selected===r.code} onClick={()=>{setSelected(r.code);setGroup('');}} disabled={busy}>انتخاب گروه برای {r.label}</button>{selected===r.code&&<Field label={'گروه برای آزمایش '+r.label}><select value={group} onChange={e=>setGroup(e.target.value)}><option value="">انتخاب گروه…</option>{data.groups.map((g:Row)=><option key={g.id} value={g.id}>{'گروه '+digits(Number(g.code.slice(-1)))}</option>)}</select></Field>}<small id={'group-hint-'+r.code}>{selected===r.code&&group?'محدوده انتخاب‌شده اعمال می‌شود.':'ابتدا گروه را انتخاب کنید.'}</small><button className="tech-primary" aria-label={'ورود آزمایشی '+r.label} aria-describedby={'group-hint-'+r.code} disabled={busy||selected!==r.code||!group} onClick={()=>enter(r.code)}>ورود آزمایشی ←</button></>:<><p>دسترسی در محدوده نقش انتخاب‌شده</p><button className="tech-primary" aria-label={'ورود آزمایشی '+r.label} disabled={busy} onClick={()=>enter(r.code)}>ورود آزمایشی ←</button></>}</article>;})}</div>{!data.groups.length&&<p className="tech-warning">گروه جاری برای آزمایش موجود نیست؛ داده‌های جاری باید توسط مسئول توسعه آماده شوند.</p>}</section>;
}
export function TechnicalDashboard(){const {data,error}=useData('/technical/status');return <Screen title="پنل پشتیبان فنی سامانه" error={error} loading={!data&&!error}><div className="role-dashboard technical-workspace"><section className="tech-welcome"><Mark kind="settings"/><div><h2>به پنل پشتیبان فنی سامانه خوش آمدید</h2><p>وضعیت فنی را بررسی کنید و با مجوزهای همان نقش، وارد محیط آزمایش شوید.</p></div></section>{data&&<><HealthCards data={data}/><SimulationCards data={data}/><div className="role-panel-grid"><section className="role-card"><h2>کاربران و نقش‌ها</h2><p>حساب‌های جاری و سوابق توسعه، با نمایش روشن مسئولیت‌ها</p><Link to="/technical/users">مشاهده کاربران ←</Link></section><section className="role-card"><h2>رویدادها و تاریخچه</h2><p>کاربر واقعی، نقش مؤثر و زمان رویدادهای ثبت‌شده</p><Link to="/technical/audit">مشاهده رویدادها ←</Link></section></div></>}</div></Screen>;}
export function TechnicalSimulation(){const {data,error}=useData('/technical/status');return <Screen title="آزمایش نقش‌ها" error={error} loading={!data&&!error}><div className="technical-workspace">{data&&<SimulationCards data={data}/>}</div></Screen>;}
export function TechnicalHealth(){const {data,error,refresh}=useData('/technical/status');return <Screen title="سلامت سامانه" error={error} loading={!data&&!error}><div className="role-dashboard technical-workspace"><button className="secondary tech-refresh" onClick={refresh}>بررسی دوباره اتصال</button>{error&&<p className="tech-warning">سلامت سامانه قابل تأیید نیست؛ نتیجه موفق قبلی نمایش داده نمی‌شود.</p>}{data&&<HealthCards data={data}/>}<section className="role-card"><h2>خطاهای فنی اخیر</h2><Badge tone="amber">در مرحله بعد</Badge><p>منبع مستقل و قابل اتکای پایش خطای فنی هنوز به این صفحه متصل نشده است.</p></section></div></Screen>;}
export function TechnicalUsers(){
 const {data,error}=useData('/technical/users');const [tab,setTab]=useState('CURRENT'),[query,setQuery]=useState(''),[role,setRole]=useState(''),[group,setGroup]=useState(''),[status,setStatus]=useState(''),[kind,setKind]=useState('');
 const users:Row[]=data?.users??[],base=users.filter(u=>u.cohort===tab),groups:Row[]=[...new Map(base.flatMap(u=>u.roles).filter(r=>r.scopeId).map(r=>[r.scopeId,r])).values()];
 const normalize=(s:string)=>s.replace(/ي/g,'ی').replace(/ك/g,'ک').toLocaleLowerCase();
 const rows=base.filter(u=>(!query||normalize(u.name+' '+u.username).includes(normalize(query.trim())))&&(!role||u.roles.some((r:Row)=>r.code===role))&&(!group||u.roles.some((r:Row)=>r.scopeId===group))&&(!status||u.status===status)&&(!kind||u.accountType===kind));
 return <Screen title="کاربران و نقش‌ها" error={error} loading={!data&&!error}><div className="technical-workspace"><section className="role-card"><div className="tech-tabs" role="tablist" aria-label="نوع فهرست کاربران">{[['CURRENT','کاربران نسخه جاری'],['LEGACY','حساب‌های توسعه و قدیمی']].map(([code,label])=><button key={code} role="tab" aria-selected={tab===code} onClick={()=>{setTab(code);setQuery('');setGroup('');setRole('');setStatus('');setKind('');}}>{label} <Badge>{digits(users.filter(u=>u.cohort===code).length)}</Badge></button>)}</div><p className={tab==='LEGACY'?'tech-notice':''}>{tab==='LEGACY'?'این حساب‌ها برای حفظ سوابق و تست‌های قبلی نگه داشته شده‌اند؛ وضعیت واقعی آن‌ها بدون تغییر نمایش داده می‌شود.':'حساب‌های جاری؛ مدیریت تغییر حساب و نقش در مرحله بعد است.'}</p><div className="tech-filters"><Field label="جست‌وجوی نام یا نام کاربری"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جست‌وجو…"/></Field><Field label="نقش"><select value={role} onChange={e=>setRole(e.target.value)}><option value="">همه نقش‌ها</option>{Object.entries(roleLabels).map(([code,label])=><option value={code} key={code}>{label}</option>)}</select></Field><Field label="گروه"><select value={group} onChange={e=>setGroup(e.target.value)}><option value="">همه گروه‌ها</option>{groups.map(g=><option key={g.scopeId} value={g.scopeId}>{g.scope}</option>)}</select></Field><Field label="وضعیت"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">همه وضعیت‌ها</option>{[...new Set(users.map(u=>u.status))].map(v=><option value={v} key={v}>{fa(v)}</option>)}</select></Field><Field label="نوع حساب"><select value={kind} onChange={e=>setKind(e.target.value)}><option value="">همه انواع</option>{Object.entries(accountTypes).map(([code,label])=><option value={code} key={code}>{label}</option>)}</select></Field></div><p aria-live="polite">{digits(rows.length)} حساب</p><div className="table-scroll"><table className="tech-users"><thead><tr>{['نام','نام کاربری','نقش‌ها','گروه','وضعیت','نوع حساب','عملیات'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(u=><tr key={u.id}><td>{displayName(u.name)}</td><td><bdi>{u.username}</bdi></td><td><div className="tech-badges">{[...new Set<string>(u.roles.map((r:Row)=>r.code))].map(code=><Badge key={code}>{roleLabels[code]??'نقش ثبت‌شده'}</Badge>)}</div></td><td>{[...new Set(u.roles.map((r:Row)=>r.scope).filter(Boolean))].join('، ')||'سطح کانون'}</td><td><Badge tone={u.status==='ACTIVE'?'green':'amber'}>{fa(u.status)}</Badge></td><td><Badge tone="blue">{accountTypes[u.accountType]}</Badge></td><td><span className="tech-deferred" title="تغییر حساب و نقش هنوز فعال نیست">در مرحله بعد</span></td></tr>)}</tbody></table></div>{!rows.length&&data&&<p className="quiet-state">حسابی مطابق این فیلترها پیدا نشد.</p>}</section></div></Screen>;
}
const events:Record<string,string>={SIMULATION_STARTED:'شروع آزمایش نقش',SIMULATION_ENDED:'پایان آزمایش نقش',SIMULATION_OPERATION_ATTEMPT:'درخواست عملیات در حالت آزمایش',ROLE_SELECTED:'انتخاب نقش فعال',LOGIN_SUCCESS:'ورود موفق',LOGIN_FAILED:'ورود ناموفق',LOGOUT:'خروج از حساب',LIVELIHOOD_CREATED:'ایجاد ارزیابی معیشت',LIVELIHOOD_SUBMITTED:'ارسال ارزیابی معیشت',LIVELIHOOD_APPROVED:'تأیید ارزیابی معیشت',LIVELIHOOD_RETURNED:'برگشت ارزیابی معیشت',LIVELIHOOD_DEMO_SEEDED:'ثبت داده آزمایشی معیشت',LIVELIHOOD_REVIEW_STARTED:'شروع بررسی معیشت'};
export function TechnicalAudit(){const {data,error}=useData('/technical/audit');return <Screen title="رویدادها و تاریخچه فنی" error={error} loading={!data&&!error}><div className="technical-workspace"><section className="role-card"><p>۱۰۰ رویداد اخیر؛ نقش مؤثر رویدادهای قدیمی یا سیستمی ممکن است ثبت نشده باشد. ثبت یک درخواست، به معنی موفقیت عملیات نیست.</p><div className="table-scroll"><table><thead><tr>{['کاربر واقعی','نقش مؤثر','رویداد','وضعیت','حالت','زمان'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data?.events.map((e:Row)=>{const code=e.event_type.replace(/^GUIDE_/,'');return <tr key={e.id}><td>{displayName(e.actor_name??'سامانه')}{e.username&&<small className="tech-username"><bdi>{e.username}</bdi></small>}</td><td>{roleLabels[e.effective_role]??'ثبت نشده'}</td><td><span>{events[code]??(fa(code)==='ثبت نشده'?'رویداد ثبت‌شده سامانه':fa(code))}</span><details className="tech-event-code"><summary>کد رویداد</summary><bdi>{e.event_type}</bdi></details></td><td><Badge tone={code.includes('FAILED')?'red':code.endsWith('ATTEMPT')?'amber':'green'}>{code.includes('FAILED')?'ناموفق':code.endsWith('ATTEMPT')?'درخواست ثبت‌شده':'ثبت‌شده'}</Badge></td><td>{e.simulation?<Badge tone="amber">آزمایش نقش</Badge>:'عادی'}</td><td>{date(e.occurred_at)}</td></tr>;})}</tbody></table></div>{data&&!data.events.length&&<p className="quiet-state">رویدادی ثبت نشده است.</p>}</section></div></Screen>;}
