import {Pool} from 'pg';
import argon2 from 'argon2';
import {createHash} from 'node:crypto';
const uuid=(key:string)=>{const h=createHash('sha256').update('lahout-review-development:'+key).digest('hex');return h.slice(0,8)+'-'+h.slice(8,12)+'-4'+h.slice(13,16)+'-8'+h.slice(17,20)+'-'+h.slice(20,32);};
const provenance='DEVELOPMENT/TEST — synthetic reporting snapshot; not an assessment eligibility formula';
async function main(){
 if(process.env.APP_ENV!=='development'||!process.env.DATABASE_URL||!process.env.DEV_SEED_PASSWORD)throw new Error('Explicit development environment and local seed password required');
 const pool=new Pool({connectionString:process.env.DATABASE_URL}),c=await pool.connect();
 try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(1405,5)');
 if((await c.query("SELECT 1 FROM monitoring.seed_batches WHERE key='guide-review-v1'")).rowCount){await c.query('COMMIT');console.log('Review development seed already exists; current data preserved.');return;}
 const guide=(await c.query("SELECT id FROM identity.accounts WHERE username='Aseman'")).rows[0];if(!guide)throw new Error('Seed Aseman first');
 const hash=await argon2.hash(process.env.DEV_SEED_PASSWORD,{type:argon2.argon2id});
 async function account(key:string,first:string,index:number){const person=uuid('person-'+key),account=uuid('account-'+key);await c.query("INSERT INTO identity.people(id,first_name,last_name,mobile,national_id) VALUES($1,$2,'آزمایشی Development/Test',$3,$4)",[person,first,'TEST-PHONE-'+index,'TEST-ID-'+index]);await c.query('INSERT INTO identity.accounts(id,person_id,username,password_hash) VALUES($1,$2,$3,$4)',[account,person,key,hash]);return {person,account};}
 async function assign(account:string,code:string,group?:string){await c.query('INSERT INTO identity.role_assignments(account_id,role_code,scope_type,scope_id) VALUES($1,$2,$3,$4)',[account,code,group?'GROUP':'ORGANIZATION',group??null]);}
 const leaders:{person:string;account:string}[]=[],familyIds:string[]=[];
 for(let n=1;n<=3;n++){
 const group=uuid('group-'+n);await c.query('INSERT INTO organization.groups(id,code,group_number,name) VALUES($1,$2,$3,$4)',[group,'REVIEW-TEST-GROUP-'+n,n,n===2?'':'گروه آزمایشی '+n]);
 const leader=await account('ReviewLeader'+n,'سرگروه '+n,100+n);leaders.push(leader);await assign(leader.account,'GROUP_LEADER',group);await assign(leader.account,n===2?'EXECUTIVE_MANAGER':'COUNCIL_MEMBER');
 for(let h=1;h<=2;h++){const helper=await account('ReviewHelper'+n+h,'همیار '+n+'-'+h,200+n*10+h);await assign(helper.account,'HELPER',group);}
 for(let j=1;j<=3;j++){
 const family=uuid('family-'+n+j);familyIds.push(family);await c.query("INSERT INTO family.families(id,family_code,current_group_id,created_by,neighborhood) VALUES($1,$2,$3,$4,'محله آزمایشی')",[family,'HL-TEST-'+n+j,group,guide.id]);
 for(let m=0;m<3;m++){const person=uuid('family-person-'+n+j+m);await c.query("INSERT INTO identity.people(id,first_name,last_name,mobile,national_id) VALUES($1,$2,'خانواده آزمایشی',$3,$4)",[person,(m===0?'سرپرست':'عضو')+' '+n+'-'+j+'-'+m,'TEST-F-'+n+j+m,'TEST-FID-'+n+j+m]);await c.query('INSERT INTO family.family_memberships(family_id,person_id,relationship_code) VALUES($1,$2,$3)',[family,person,m===0?'HEAD':m===1?'SPOUSE':'CHILD']);if(m===0)await c.query('INSERT INTO family.head_history(family_id,person_id) VALUES($1,$2)',[family,person]);}
 const level=['A','B','C','D'][(n+j-2)%4],score={A:90,B:70,C:50,D:30}[level]!,domains:Record<string,unknown>={};const names=[['livelihood','معیشت'],['health','سلامت'],['housing','مسکن'],['vulnerability','آسیب‌پذیری ویژه'],['education','آموزش']];let remaining=score;
 for(let d=0;d<names.length;d++){const points=d===names.length-1?remaining:Math.floor(score/names.length);remaining-=points;domains[names[d][0]]={title:names[d][1],score:points,answers:[{question:'وضعیت ثبت‌شده '+names[d][1],response:'پاسخ نمونه آزمایشی '+j,score:points,max_score:20}],research_data:'مشاهده آزمایشی؛ داده واقعی نیست.'};}
 const overdue=j===1,last=new Date(Date.now()-(n+j)*86400000).toISOString();await c.query(`INSERT INTO family.case_profiles(family_id,score,need_level,urgency,research_status,last_research_at,research_due_at,review_required,support_status,special_case,domains,provenance) VALUES($1,$2,$3,$4,$5,$6,now()+($7::text||' days')::interval,$8,$9,$10,$11,$12)`,[family,score,level,j===1?'CRITICAL':j===2?'HIGH':'NORMAL',overdue?'PENDING':'COMPLETED',last,overdue?-2:30,j===2,j===3?'COMPLETED':'PENDING',j===1,JSON.stringify(domains),provenance]);
 for(const source of ['LEADER','RESEARCH_BOARD'])await c.query('INSERT INTO family.research_records(family_id,actor_id,source,recorded_at,due_at,completed_at,answers,document_names,provenance) VALUES($1,$2,$3,$4,now()-interval \'1 day\',$5,$6,$7,$8)',[family,leader.account,source,last,overdue?null:last,JSON.stringify(domains),JSON.stringify(['مدرک نمونه آزمایشی.txt']),provenance]);
 await c.query("INSERT INTO family.documents(family_id,name,media_type,content) VALUES($1,'مدرک نمونه آزمایشی.txt','text/plain; charset=utf-8',$2)",[family,Buffer.from('Development/Test — مدرک نمونه بدون اطلاعات واقعی')]);
 const categories=['یخچال','لباسشویی','تلویزیون','درمان','اجاره','تحصیل','کمک نقدی','پوشاک','لوازم تحصیلی'];await c.query("INSERT INTO monitoring.support_records(family_id,category,amount,status,source,result,occurred_at,actor_id,provenance) VALUES($1,$2,$3,$4,'حامی آزمایشی',$5,now()-interval '3 days',$6,$7)",[family,categories[(n-1)*3+j-1],1000000*n*j,j===3?'COMPLETED':'PENDING',j===3?'تحویل آزمایشی ثبت شد':null,leader.account,provenance]);
 const stipend=uuid('stipend-'+n+j);await c.query("INSERT INTO monitoring.stipends(id,family_id,monthly_amount,starts_on,provenance) VALUES($1,$2,$3,current_date-60,$4)",[stipend,family,2000000*n,provenance]);for(let pay=0;pay<3;pay++)await c.query("INSERT INTO monitoring.stipend_payments(stipend_id,due_on,amount,paid_at) VALUES($1,current_date-($2::int*30),$3,CASE WHEN $2>0 THEN now()-interval '30 days' ELSE NULL END)",[stipend,pay,2000000*n]);
 for(let visit=0;visit<2;visit++)await c.query("INSERT INTO monitoring.activities(family_id,account_id,kind,occurred_at,due_at,completed_at,result,provenance) VALUES($1,$2,'VISIT',now()-($3::text||' days')::interval,now()-interval '1 day',now()-($3::text||' days')::interval,'نتیجه مستند آزمایشی',$4)",[family,leader.account,n+visit+1,provenance]);
 await c.query("INSERT INTO monitoring.activities(family_id,account_id,kind,occurred_at,due_at,completed_at,result,provenance) VALUES($1,$2,'RESEARCH',now()-interval '5 days',now()-interval '1 day',$3,$4,$5)",[family,leader.account,overdue?null:last,overdue?null:'تحقیق آزمایشی تکمیل شد',provenance]);
 if(j===1){const item=(await c.query("INSERT INTO guidance.items(kind,subject,body,created_by,audience_type,confidential,family_id,note_type) VALUES('NOTE','هشدار خانواده آزمایشی','نیازمند رسیدگی آزمایشی',$1,'GUIDE',true,$2,'ALERT') RETURNING id",[leader.account,family])).rows[0];await c.query("INSERT INTO guidance.alerts(item_id,category,severity) VALUES($1,'IMPORTANT','RED')",[item.id]);await c.query('INSERT INTO guidance.recipients(item_id,account_id) VALUES($1,$2)',[item.id,guide.id]);}
 }
 }
 const council=await account('ReviewCouncil3','عضو شورا مستقل',303);await assign(council.account,'COUNCIL_MEMBER');
 for(const [type,severity] of [['ALERT','RED'],['REMINDER','AMBER'],['MESSAGE','INFO']]){const item=(await c.query("INSERT INTO guidance.items(kind,subject,body,created_by,audience_type,person_id,note_type,confidential) VALUES('NOTE',$1,'سوابق آزمایشی شخص',$2,'GUIDE',$3,$4,true) RETURNING id",['مورد '+type+' آزمایشی',leaders[0].account,leaders[0].person,type])).rows[0];await c.query('INSERT INTO guidance.recipients(item_id,account_id) VALUES($1,$2)',[item.id,guide.id]);if(type!=='MESSAGE')await c.query("INSERT INTO guidance.alerts(item_id,category,severity) VALUES($1,'IMPORTANT',$2)",[item.id,severity]);}
 const item=(await c.query("INSERT INTO guidance.items(kind,subject,body,created_by,audience_type,execution_status) VALUES('COUNCIL','مصوبه آزمایشی بازبینی','متن مصوبه؛ فقط توقف اجرا یا درخواست بازنگری مجاز است.',$1,'GUIDE','RUNNING') RETURNING id",[council.account])).rows[0];await c.query('INSERT INTO guidance.recipients(item_id,account_id) VALUES($1,$2)',[item.id,guide.id]);await c.query("INSERT INTO guidance.attachments(item_id,name,media_type,content) VALUES($1,'پیوست آزمایشی.txt','text/plain; charset=utf-8',$2)",[item.id,Buffer.from('پیوست آزمایشی شورا')]);
 const plan=uuid('plan-school');await c.query("INSERT INTO monitoring.distribution_plans(id,title,category,capacity,unit_value,source,planned_on,provenance) VALUES($1,'طرح آزمایشی لوازم تحصیلی','لوازم تحصیلی',9,1500000,'حامی آزمایشی',current_date,$2)",[plan,provenance]);for(let k=0;k<familyIds.length;k++)await c.query('INSERT INTO monitoring.distribution_recipients(plan_id,family_id,status) VALUES($1,$2,$3)',[plan,familyIds[k],['FINAL','ELIGIBLE','RESERVE','NON_DELIVERY','REPLACEMENT','TARGET'][k%6]]);
 await c.query("INSERT INTO monitoring.seed_batches(key) VALUES('guide-review-v1')");await c.query('COMMIT');console.log('Review Development/Test seed: 3 groups, 3 leaders, 6 helpers, 9 families, 3 council members. Existing data never reset.');
 }catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();await pool.end();}
}
main().catch(e=>{console.error('Review seed failed:',e instanceof Error?e.message:'unknown');process.exitCode=1;});
