import type {PoolClient} from 'pg';
import {draftDefinition,evaluate} from '../src/oversight/scoring';
/** Only named development fixtures are amended; operational records are untouched. */
export async function finalGuideSeed(c:PoolClient){
 if((await c.query("SELECT 1 FROM monitoring.seed_batches WHERE key='guide-final-v2'")).rowCount)return;
 const names=[['ReviewLeader1','علی','رضایی'],['ReviewLeader2','مریم','احمدی'],['ReviewLeader3','حسین','کریمی'],['ReviewHelper11','زهرا','محمدی'],['ReviewHelper12','رضا','حسینی'],['ReviewHelper21','فاطمه','موسوی'],['ReviewHelper22','امیر','جعفری'],['ReviewHelper31','نرگس','صادقی'],['ReviewHelper32','سعید','مرادی'],['ReviewCouncil3','لیلا','کاظمی']];
 for(const [username,first,last] of names){const p=(await c.query('SELECT person_id FROM identity.accounts WHERE username=$1',[username])).rows[0];if(!p)continue;await c.query('UPDATE identity.people SET first_name=$2,last_name=$3 WHERE id=$1',[p.person_id,first,last]);await c.query("INSERT INTO guidance.history(entity_type,entity_id,action,new_state) VALUES('PERSON',$1,'DEVELOPMENT_DATA_UPDATED',$2)",[p.person_id,JSON.stringify({name:first+' '+last})]);}
 const familyNames=['نجفی','بهرامی','قاسمی','اکبری','سلیمانی','رحیمی','رستمی','عباسی','زارعی'];const firstNames=[['محمد','سمیه','آرین'],['فاطمه','نرگس','مهدی'],['حسن','فریده','مریم'],['رضا','لیلا','زهرا'],['ناهید','علی','سارا'],['جواد','زینب','امیر'],['محمود','پروین','حسین'],['سعید','الهام','یاسمن'],['رقیه','مجید','کیانا']];
 const families=(await c.query("SELECT id,family_code FROM family.families WHERE family_code ~ '^HL-TEST-[1-3][1-3]$' ORDER BY family_code")).rows;
 for(let i=0;i<families.length;i++){const f=families[i],members=(await c.query("SELECT p.id,m.relationship_code FROM family.family_memberships m JOIN identity.people p ON p.id=m.person_id WHERE m.family_id=$1 AND m.valid_to IS NULL ORDER BY CASE m.relationship_code WHEN 'HEAD' THEN 0 WHEN 'SPOUSE' THEN 1 ELSE 2 END",[f.id])).rows;
 for(let j=0;j<members.length;j++){const years=j===0?[42,38,71,47,35,52,68,40,63][i]:j===1?[39,17,65,43,14,48,62,37,34][i]:[12,9,32,15,8,18,30,11,7][i];const female=j===0?[1,4,8].includes(i):j===1?![1,4,8].includes(i):[2,3,4,7,8].includes(i);await c.query("UPDATE identity.people SET first_name=$2,last_name=$3,sex=$4,birth_date=(current_date-($5::text||' years')::interval)::date WHERE id=$1",[members[j].id,firstNames[i][j],familyNames[i],female?'FEMALE':'MALE',years]);}
 await c.query("INSERT INTO guidance.history(entity_type,entity_id,action,new_state) VALUES('FAMILY',$1,'DEVELOPMENT_DATA_UPDATED',$2)",[f.id,JSON.stringify({description:'نام و تنوع سنی داده‌های نمونه اصلاح شد؛ سوابق قبلی محفوظ است.'})]);
 }
 await c.query("UPDATE guidance.items SET subject=CASE note_type WHEN 'ALERT' THEN 'تذکر ثبت‌شده برای بررسی' WHEN 'REMINDER' THEN 'یادآوری پیگیری' ELSE 'یادداشت مرتبط با شخص' END WHERE body='سوابق آزمایشی شخص'");
 await c.query("UPDATE oversight.alerts a SET subject=i.subject FROM guidance.items i WHERE i.id=(SELECT item_id FROM guidance.alerts WHERE id=a.legacy_id) AND i.body='سوابق آزمایشی شخص'");
 await c.query("UPDATE guidance.items SET archive_final=true,category='حمایت آموزشی' WHERE kind='COUNCIL' AND subject='مصوبه آزمایشی بازبینی'");
 await c.query("UPDATE monitoring.distribution_plans SET status='FINAL',occasion='آغاز سال تحصیلی',result_summary='لوازم تحصیلی به خانواده‌های ثبت‌شده تحویل شد.' WHERE title='طرح آزمایشی لوازم تحصیلی'");
 // Import legacy reminder/alert fixtures created after migration; leave originals intact.
 await c.query("INSERT INTO oversight.reminders(legacy_item_id,person_id,subject,created_by,due_at) SELECT id,person_id,subject,created_by,now()-interval '1 day' FROM guidance.items WHERE note_type='REMINDER' AND body='سوابق آزمایشی شخص' ON CONFLICT(legacy_item_id) DO NOTHING");
 await c.query(`INSERT INTO oversight.alerts(id,legacy_id,family_id,person_id,rule_code,subject,severity,owner_id,escalated)
 SELECT a.id,a.id,i.family_id,i.person_id,'LEGACY_'||a.id,i.subject,'IMPORTANT',(SELECT r.account_id FROM identity.role_assignments r WHERE r.scope_id=f.current_group_id AND r.role_code='GROUP_LEADER' AND r.valid_to IS NULL LIMIT 1),true
 FROM guidance.alerts a JOIN guidance.items i ON i.id=a.item_id LEFT JOIN family.families f ON f.id=i.family_id WHERE a.closed_at IS NULL AND i.note_type='ALERT' ON CONFLICT(legacy_id) DO NOTHING`);
 const model=(await c.query("SELECT * FROM assessment.models WHERE version='1.0' AND state='ACTIVE'")).rows[0];
 if(model)for(let index=0;index<families.length;index++){
 const f=families[index];if((await c.query('SELECT 1 FROM assessment.snapshots WHERE family_id=$1',[f.id])).rowCount)continue;
 const members=(await c.query('SELECT p.*,m.relationship_code FROM family.family_memberships m JOIN identity.people p ON p.id=m.person_id WHERE m.family_id=$1 AND m.valid_to IS NULL ORDER BY p.id',[f.id])).rows;
 const leader=(await c.query("SELECT r.account_id FROM identity.role_assignments r JOIN family.families f ON f.current_group_id=r.scope_id WHERE f.id=$1 AND r.role_code='GROUP_LEADER' AND r.valid_to IS NULL LIMIT 1",[f.id])).rows[0]?.account_id;if(!leader)continue;
 const answers:Record<string,any>={};for(const [domain,definition] of Object.entries(model.definition.domains) as [string,any][]){const severity=index%4;const summaries=Object.fromEntries(Object.entries(definition.indicators).map(([key,indicator]:any)=>{const options=Object.keys(indicator.responses).sort((a,b)=>indicator.responses[a].points-indicator.responses[b].points);return [key,options[Math.min(severity,options.length-1)]];}));const screening=['health','vulnerability'].includes(domain);const education=domain==='education';const memberRows=members.map((m:any,i:number)=>({id:m.id,name:m.first_name+' '+m.last_name,...(education?{eligible:index===2?false:i===2,studyStatus:'در حال تحصیل',futureRisk:'خطر وجود ندارد'}:screening?{status:severity===0?'NO_PROBLEM':'AFFECTED',description:'مشاهده نمونه آموزشی'}:{})}));const section=model.form_schema[domain]?.find((s:any)=>s.screen);answers[domain]={summaries,critical:Object.fromEntries(model.definition.criticalRules.filter((r:any)=>r.domain===domain).map((r:any)=>[r.code,index===0&&r.code==='LIVELIHOOD_BASIC'])),notes:'داده نمونه برای آموزش و آزمون؛ اطلاعات واقعی نیست.',sections:section?{[section.key]:memberRows}:{},members:memberRows.map((r:any)=>({id:r.id,status:r.status,eligible:r.eligible,details:r}))};}
 if(index===8)delete answers.housing.summaries.quality;
 const result=evaluate(model.definition,answers,members.map((m:any)=>m.id));const snapshot=(await c.query('INSERT INTO assessment.snapshots(family_id,model_id,revision,actor_id,answers,members,result,state,score,level,urgency) VALUES($1,$2,1,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id',[f.id,model.id,leader,JSON.stringify(answers),JSON.stringify(members),JSON.stringify(result),result.state,result.score,result.level,['IMMEDIATE','NECESSARY','IMPORTANT','NON_URGENT'][index%4]])).rows[0];
 await c.query("INSERT INTO guidance.history(entity_type,entity_id,actor_id,action,new_state) VALUES('FAMILY',$1,$2,'ASSESSMENT_SUBMITTED',$3)",[f.id,leader,JSON.stringify({revision:1,model_version:'1.0',score:result.score,level:result.level,state:result.state,description:'نسخه نمونه توسعه با جدول مصوب محاسبه شد.'})]);
 for(const flag of result.criticalFlags)await c.query('INSERT INTO oversight.alerts(family_id,rule_code,subject,severity,owner_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING',[f.id,flag.code,flag.label,flag.severity,leader]);
 }
 await c.query("INSERT INTO monitoring.seed_batches(key) VALUES('guide-final-v2')");
}
