import {Pool} from 'pg';
import argon2 from 'argon2';
import {createHash} from 'node:crypto';
const staff=[["ژینو علی‌پناه", "روناک کریمی", "آیدا کمانگر"], ["سیران قوامی", "کانی شریعتی", "نیلوفر لطفی"], ["سودابه ویسی", "مهسا امانی", "فروزان جلالی"], ["گلنار ایازی", "زیبا بختیاری", "نسرین کرباسی"], ["سونیا محمدی", "شیوا غلامی", "دلنیا محمدی"]];
const heads=[["محمد احمدی", "فاطمه مرادی", "حسن کریمی", "ناهید رحیمی", "رضا حسینی", "سمیره محمدی", "جواد محمودی", "لیلا قادری", "بهرام صادقی", "مریم عزیزی"], ["علی رضایی", "زهرا امینی", "کیوان عباسی", "روژین مرادی", "رحمان نادری", "شبنم قاسمی", "اکبر صالحی", "شیرین کریمی", "کاوه یوسفی", "نسرین محمدی"], ["حمید رستمی", "سمیه احمدی", "آزاد محمودی", "مژگان رحیمی", "فرهاد کریمی", "پروین قادری", "سامان حسینی", "لیلا صادقی", "منصور عزیزی", "هانا محمدی"], ["حسین مرادی", "زینب احمدی", "بهروز کریمی", "ناهید محمودی", "امید رحیمی", "مهتاب حسینی", "یوسف قادری", "نرگس رضایی", "کوروش صادقی", "آرام محمدی"], ["سعید احمدی", "فریبا مرادی", "سامان رضایی", "شیلان کریمی", "داود حسینی", "مریم محمودی", "زانیار رحیمی", "الهام قادری", "آرمان صادقی", "سارا محمدی"]];
const uid=(key:string)=>{const h=createHash('sha256').update('lahout-livelihood-v100-test:'+key).digest('hex');return h.slice(0,8)+'-'+h.slice(8,12)+'-4'+h.slice(13,16)+'-a'+h.slice(17,20)+'-'+h.slice(20,32);};
async function main(){if(process.env.APP_ENV!=='development'||!process.env.DEV_SEED_PASSWORD||process.env.DEV_SEED_PASSWORD.length<12)throw new Error('Development environment and 12+ character DEV_SEED_PASSWORD required');const pool=new Pool({connectionString:process.env.DATABASE_URL}),c=await pool.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(1405,11)');const hash=await argon2.hash(process.env.DEV_SEED_PASSWORD,{type:argon2.argon2id});
async function account(key:string,name:string,roles:string[],group:string|null){const aid=uid('account:'+key);if((await c.query('SELECT 1 FROM identity.accounts WHERE id=$1',[aid])).rowCount)return aid;const parts=name.split(' '),person=uid('person:'+key);await c.query('INSERT INTO identity.people(id,first_name,last_name) VALUES($1,$2,$3)',[person,parts[0],parts.slice(1).join(' ')]);await c.query('INSERT INTO identity.accounts(id,person_id,username,password_hash) VALUES($1,$2,$3,$4)',[aid,person,'TestV100_'+key,hash]);for(const role of roles)await c.query('INSERT INTO identity.role_assignments(account_id,role_code,scope_type,scope_id) VALUES($1,$2,$3,$4)',[aid,role,['GROUP_LEADER','HELPER'].includes(role)?'GROUP':'ORGANIZATION',['GROUP_LEADER','HELPER'].includes(role)?group:null]);await c.query("INSERT INTO admin.audit_events(event_type,entity_type,entity_id,metadata) VALUES('DEVELOPMENT_ROLE_ACCOUNT_CREATED','ACCOUNT',$1,$2)",[aid,JSON.stringify({source:'V100 DEVELOPMENT/TEST ONLY'})]);return aid;}
const executive=await account('Executive','شاهده بنفشی',['EXECUTIVE_MANAGER','COUNCIL_MEMBER'],null);
for(const [i,name] of ['منیره نصری','نشمین پیمانکار','آمنه آذرپیرا'].entries())await account('Council'+(i+1),name,['COUNCIL_MEMBER'],null);
for(let g=1;g<=5;g++){const group=uid('group:'+g);await c.query('INSERT INTO organization.groups(id,code,name) VALUES($1,$2,$3) ON CONFLICT(id) DO NOTHING',[group,'V100-TEST-G'+g,'گروه '+g+' — آزمایشی نسخه ۱٫۰۰']);const leader=await account('Leader'+g,staff[g-1][0],['GROUP_LEADER','COUNCIL_MEMBER'],group);for(let h=1;h<=2;h++)await account('Helper'+g+'_'+h,staff[g-1][h],['HELPER'],group);
for(let n=1;n<=10;n++){const key='G'+g+'-'+String(n).padStart(2,'0'),family=uid('family:'+key);if((await c.query('SELECT 1 FROM family.families WHERE id=$1',[family])).rowCount)continue;
await c.query("INSERT INTO family.families(id,family_code,current_group_id,created_by,neighborhood,basic_data) VALUES($1,$2,$3,$4,'محله کاملاً فرضی — Development/Test',$5)",[family,'HL-TEST-'+key,group,leader,JSON.stringify({residenceType:'اجاره‌ای',formedOn:'2026-09-01',source:'سناریوی کاملاً فرضی Development/Test؛ پذیرش واقعی نیست'})]);
for(let m=0;m<3;m++){const person=uid('member:'+key+':'+m),full=m===0?heads[g-1][n-1]:(m===1?'همسر فرضی':'فرزند فرضی')+' '+key,parts=full.split(' '),rel=['HEAD','SPOUSE','CHILD'][m];await c.query('INSERT INTO identity.people(id,first_name,last_name,national_id,mobile) VALUES($1,$2,$3,$4,$5)',[person,parts[0],parts.slice(1).join(' '),'TEST-'+key+'-'+m,m===0?'TEST-PHONE-'+key:null]);await c.query('INSERT INTO family.family_memberships(family_id,person_id,relationship_code,profile_data) VALUES($1,$2,$3,$4)',[family,person,rel,JSON.stringify({age:[40,35,10][m],education:m===2?'دانش‌آموز':'خارج از تحصیل',health:'فاقد مشکل مؤثر',notes:'اطلاعات کاملاً فرضی'})]);if(m===0)await c.query('INSERT INTO family.head_history(family_id,person_id) VALUES($1,$2)',[family,person]);}
await c.query("INSERT INTO family.case_profiles(family_id,provenance) VALUES($1,'V100 DEVELOPMENT/TEST ONLY — no full assessment')",[family]);
for(const category of ['NATIONAL_CARD','FAMILY_BOOK']){const doc=(await c.query("INSERT INTO family.documents(family_id,name,media_type,content) VALUES($1,$2,'text/plain',$3) RETURNING id",[family,'نمونه فرضی '+(category==='NATIONAL_CARD'?'کارت ملی':'شناسنامه')+' '+key+'.txt',Buffer.from('DEVELOPMENT/TEST ONLY. NOT A REAL IDENTITY DOCUMENT. '+key)])).rows[0];await c.query('INSERT INTO family.document_context(document_id,category,actor_id) VALUES($1,$2,$3)',[doc.id,category,leader]);}
await c.query("INSERT INTO guidance.history(entity_type,entity_id,actor_id,action,new_state,effective_role,effective_scopes) VALUES('FAMILY',$1,$2,'LIVELIHOOD_TEST_SEEDED',$3,'GROUP_LEADER',$4)",[family,leader,JSON.stringify({source:'DEVELOPMENT/TEST ONLY',code:'HL-TEST-'+key}),JSON.stringify([{roleCode:'GROUP_LEADER',scopeType:'GROUP',scopeId:group}])]);
}}
await c.query('COMMIT');console.log('V1.00 development fixtures ready: 5 groups, 50 families, 19 accounts, 9 council memberships. Existing rows and passwords preserved.');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();await pool.end();}}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
