import { Inject, Injectable } from '@nestjs/common';
import { Pool } from 'pg';
import { randomUUID } from 'node:crypto';
import { PG_POOL } from '../database/database.constants';
import { GuidanceService,input,str } from '../guidance/guidance.service';
import type { AuthUser } from '../auth/auth.types';
import { AppError } from '../common/app-error';
import {reportHtml,workbook,pdfDocument} from './report-export';
const datasets:Record<string,string>={families:'family_facts',supports:'support_facts',stipends:'stipend_facts',distribution:'distribution_facts',groups:'group_facts',performance:'performance_facts'};
const labels:Record<string,string>={reviews_required:'پرونده نیازمند بازبینی',red_alerts:'هشدار قرمز باز',alert_resolution_hours:'میانگین زمان رسیدگی هشدار (ساعت)',council_executed:'مصوبه اجراشده',verification_requests:'درخواست استعلام',verification_completed:'استعلام تعیین تکلیف‌شده',family_id:'شناسه خانواده',family_code:'کد خانواده',group_id:'شناسه گروه',group_number:'شماره گروه',group_name:'گروه',head_name:'سرپرست',mobile:'تلفن',national_id:'کد ملی',case_status:'وضعیت پرونده',neighborhood:'محله',created_at:'تاریخ',member_count:'تعداد اعضا',score:'امتیاز کل',need_level:'سطح نیاز',urgency:'فوریت',research_status:'وضعیت تحقیق',last_research_at:'آخرین تحقیق',research_due_at:'مهلت تحقیق',review_required:'نیازمند بازبینی',support_status:'وضعیت حمایت',special_case:'آسیب‌پذیری ویژه',domains:'پاسخ‌ها و امتیازهای حوزه‌ها',profile_updated_at:'آخرین به‌روزرسانی',open_alerts:'هشدار باز',visits:'بازدید',last_visit:'آخرین بازدید',support_total:'مجموع حمایت',support_type:'نوع حمایت',amount:'مبلغ',status:'وضعیت',source:'منبع',result:'نتیجه',actor_id:'ثبت‌کننده',provenance:'منشأ داده',monthly_amount:'مبلغ ماهانه',starts_on:'شروع',ends_on:'پایان',paid_count:'تعداد پرداخت',paid_total:'مجموع پرداخت',overdue_amount:'مبلغ معوق',payments:'ریز پرداخت‌ها',plan_id:'شناسه طرح',title:'عنوان طرح',plan_type:'نوع طرح',capacity:'ظرفیت',unit_value:'ارزش واحد',target_families:'خانواده هدف',eligible:'واجد شرایط',final_recipients:'دریافت‌کننده نهایی',reserve:'ذخیره',non_delivery:'عدم تحویل',replacement:'جایگزین',family_count:'بار مسئولیت: تعداد خانواده',level_a:'سطح A',level_b:'سطح B',level_c:'سطح C',level_d:'سطح D',avg_need_score:'میانگین نیاز',overdue_research:'تحقیق معوق',special_cases:'بار مسئولیت: موارد ویژه',up_to_date_pct:'درصد پرونده به‌روز',avg_response_hours:'میانگین زمان رسیدگی (ساعت)',person_id:'شناسه فرد',person_name:'فرد',account_id:'شناسه حساب',role_codes:'نقش‌ها',high_need_families:'بار مسئولیت: خانواده A/B',avg_visit_gap_days:'فاصله متوسط بازدید (روز)',completed_research:'تحقیق انجام‌شده',overdue_actions:'اقدام معوق',timeliness_pct:'به‌موقع بودن (%)',completion_pct:'تکمیل (%)',documented_followup_pct:'نتیجه مستند (%)',freshness_pct:'تازگی پرونده (%)',alert_resolution_pct:'رسیدگی هشدار (%)',completed_supports:'حمایت انجام‌شده',performance_pct:'شاخص عملکرد (%)'};
@Injectable()
export class MonitoringService {
 constructor(@Inject(PG_POOL) private readonly pool:Pool,private readonly g:GuidanceService){}
 async catalog(dataset:string){if(dataset==='performance')throw new AppError(410,'RETIRED','رتبه‌بندی عملکرد از این نسخه کنار گذاشته شده است.');const view=datasets[dataset];if(!view)throw new AppError(400,'DATASET','حوزه گزارش معتبر نیست.');const cols=(await this.pool.query("SELECT column_name,data_type FROM information_schema.columns WHERE table_schema='monitoring' AND table_name=$1 ORDER BY ordinal_position",[view])).rows;return {dataset,fields:cols.map(c=>({key:c.column_name,label:labels[c.column_name]??c.column_name,type:c.data_type})),datasets:Object.keys(datasets)};}
 async options(){return {groups:(await this.pool.query('SELECT group_id AS id,group_name AS name FROM monitoring.group_facts ORDER BY group_number')).rows,families:(await this.pool.query('SELECT family_id AS id,family_code AS name FROM monitoring.family_facts ORDER BY family_code')).rows,people:(await this.pool.query("SELECT id,first_name||' '||last_name AS name FROM identity.people ORDER BY last_name")).rows,supportTypes:(await this.pool.query('SELECT DISTINCT category AS name FROM monitoring.support_records ORDER BY category')).rows,plans:(await this.pool.query('SELECT id,title AS name FROM monitoring.distribution_plans ORDER BY planned_on DESC')).rows,roles:(await this.pool.query('SELECT code AS id,label_fa AS name FROM identity.roles ORDER BY label_fa')).rows};}
 async query(dataset:string,filters:Record<string,unknown>){
 const allowed=new Set(['group','family','level','urgency','research','support','supportType','plan','planType','person','state','q','role','minScore','maxScore','review','alert','domain','from','to','lastResearch','sort','direction']);for(const [key,v] of Object.entries(filters))if(!allowed.has(key)||!['string','number','boolean'].includes(typeof v))throw new AppError(400,'FILTER','فیلتر گزارش معتبر نیست.');const catalog=await this.catalog(dataset),keys=new Set(catalog.fields.map(f=>f.key)),values:unknown[]=[],where:string[]=[];const add=(sql:string,value:unknown)=>{values.push(value);where.push(sql.replace('@',`$${values.length}`));};
 const maps:Record<string,string>={group:'group_id',family:'family_id',level:'need_level',urgency:'urgency',research:'research_status',support:'support_status',supportType:'support_type',plan:'plan_id',planType:'plan_type',person:'person_id',state:keys.has('case_status')?'case_status':'status'};
 for(const [key,col] of Object.entries(maps))if(filters[key]){if(!keys.has(col)){if(key==='supportType'&&keys.has('family_id')){add('EXISTS(SELECT 1 FROM monitoring.support_records s WHERE s.family_id=v.family_id AND s.category=@)',str(filters[key]));continue;}if(key==='plan'&&keys.has('family_id')){add('EXISTS(SELECT 1 FROM monitoring.distribution_recipients d WHERE d.family_id=v.family_id AND d.plan_id::text=@)',str(filters[key]));continue;}if(key==='group'&&dataset==='performance'){add("EXISTS(SELECT 1 FROM identity.role_assignments r WHERE r.account_id=v.account_id AND r.scope_id::text=@ AND r.valid_from<=now() AND (r.valid_to IS NULL OR r.valid_to>now()))",str(filters[key]));continue;}throw new AppError(400,'FILTER','این فیلتر در حوزه انتخاب‌شده کاربرد ندارد.');}add(`v."${col}"::text=@`,str(filters[key]));}
 if(filters.q)add("to_jsonb(v)::text ILIKE '%'||@||'%'",str(filters.q));if(filters.role){if(!keys.has('role_codes'))throw new AppError(400,'FILTER','فیلتر نقش مربوط به عملکرد است.');add("@=ANY(string_to_array(v.role_codes,','))",str(filters.role));}
 for(const [key,op,col] of [['minScore','>=','score'],['maxScore','<=','score']])if(filters[key]!==undefined&&filters[key]!==''){if(!keys.has(col)||!Number.isFinite(Number(filters[key])))throw new AppError(400,'FILTER','امتیاز معتبر نیست.');add(`v.${col}${op}@`,Number(filters[key]));}
 for(const [key,col] of [['review','review_required'],['alert','open_alerts']])if(filters[key]===true||filters[key]==='true'){if(!keys.has(col))throw new AppError(400,'FILTER','فیلتر معتبر نیست.');where.push(key==='review'?'v.review_required':'v.open_alerts>0');}
 if(filters.domain){if(!keys.has('domains'))throw new AppError(400,'FILTER','حوزه نیاز مربوط به خانواده است.');add('v.domains ? @',str(filters.domain));}
 for(const [key,op,col] of [['from','>=','created_at'],['to','<=','created_at'],['lastResearch','<=','last_research_at']])if(filters[key]){const d=str(filters[key],10);if(!keys.has(col)||!/^\d{4}-\d{2}-\d{2}$/.test(d)||!Number.isFinite(Date.parse(d))||new Date(d).toISOString().slice(0,10)!==d)throw new AppError(400,'DATE','تاریخ معتبر نیست.');add(`v.${col}::date${op}@::date`,d);}
 if(filters.from&&filters.to&&String(filters.from)>String(filters.to))throw new AppError(400,'DATE','بازه تاریخ معتبر نیست.');
 const sort=filters.sort?str(filters.sort):dataset==='performance'?'performance_pct':catalog.fields[0].key;if(!keys.has(sort))throw new AppError(400,'SORT','ستون مرتب‌سازی معتبر نیست.');if(dataset==='performance'&&['visits','completed_supports','completed_research'].includes(sort))throw new AppError(400,'SORT','رتبه‌بندی عملکرد بر اساس حجم خام مجاز نیست.');
 const direction=filters.direction==='asc'?'ASC':'DESC';const rows=(await this.pool.query(`SELECT v.* FROM monitoring.${datasets[dataset]} v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY v."${sort}" ${direction} NULLS LAST`,values)).rows;
 const aggregate:Record<string,unknown>={count:rows.length};for(const f of catalog.fields){if(['integer','bigint','numeric','double precision'].includes(f.type)&&!f.key.endsWith('_id')&&f.key!=='group_number'){const n=rows.map(r=>r[f.key]).filter(v=>v!==null).map(Number).filter(Number.isFinite);aggregate[f.key]={sum:n.reduce((a,b)=>a+b,0),average:n.length?n.reduce((a,b)=>a+b,0)/n.length:null};}}
 if(dataset==='distribution'){const plans=new Map(rows.map(r=>[r.plan_id,r]));for(const key of ['target_families','eligible','final_recipients','reserve','non_delivery','replacement','capacity','unit_value'])delete aggregate[key];aggregate.plans=plans.size;aggregate.capacity=[...plans.values()].reduce((sum,p)=>sum+p.capacity,0);aggregate.filtered_recipients=rows.filter(r=>r.family_id).length;for(const status of ['TARGET','ELIGIBLE','FINAL','RESERVE','NON_DELIVERY','REPLACEMENT'])aggregate[status]=rows.filter(r=>r.status===status).length;aggregate.total_value=rows.filter(r=>r.status==='FINAL').reduce((sum,p)=>sum+Number(p.unit_value),0);}
 if(dataset==='stipends'){const periods:Record<string,{due:number,paid:number,arrears:number}>={};for(const r of rows)for(const p of r.payments??[]){const month=String(p.due_on).slice(0,7),m=periods[month]??={due:0,paid:0,arrears:0};m.due+=Number(p.amount);if(p.paid_at)m.paid+=Number(p.amount);else if(new Date(p.due_on)<new Date())m.arrears+=Number(p.amount);}aggregate.periods=periods;}
 if(dataset==='stipends')aggregate.monthly_burden=rows.filter(r=>(!r.ends_on||new Date(r.ends_on)>=new Date())&&new Date(r.starts_on)<=new Date()).reduce((sum,r)=>sum+Number(r.monthly_amount),0);
 return {dataset,fields:catalog.fields,rows,aggregate};
 }
 async export(value:unknown,u:AuthUser){const b=input(value),dataset=str(b.dataset),title=str(b.title),format=str(b.format),filters=input(b.filters??{});if(!['preview','pdf','xlsx'].includes(format))throw new AppError(400,'FORMAT','قالب خروجی معتبر نیست.');if(b.orientation!==undefined&&!['portrait','landscape'].includes(String(b.orientation)))throw new AppError(400,'FORMAT','جهت چاپ معتبر نیست.');const data=await this.query(dataset,filters);if(!Array.isArray(b.fields)||!b.fields.length)throw new AppError(400,'FIELDS','فیلدهای خروجی را آگاهانه انتخاب کنید.');const requested=b.fields.map(x=>str(x)),fields=requested.map(key=>data.fields.find(f=>f.key===key));if(fields.some(f=>!f)||new Set(requested).size!==requested.length)throw new AppError(400,'FIELDS','فیلد انتخاب‌شده معتبر نیست.');const selected=fields as typeof data.fields,rows=data.rows.map(r=>Object.fromEntries(requested.map(k=>[k,r[k]]))),landscape=b.orientation==='landscape';
 const html=reportHtml(title,selected,rows,filters,landscape);let buffer:Buffer|undefined;
 if(format==='xlsx')buffer=workbook(title,selected,rows,landscape);if(format==='pdf'){try{buffer=await pdfDocument(html,title,landscape);}catch{throw new AppError(503,'PDF_UNAVAILABLE','مرورگر تولید PDF در دسترس نیست یا مشغول است. دوباره تلاش کنید.');}}
 await this.g.tx(u,async c=>this.g.history(c,u,'REPORT',randomUUID(),'REPORT_EXPORTED',null,{dataset,title,fields:requested,filters,format,count:rows.length}));
 return {format,html,buffer,fields:selected,rows};
 }
}
