import { deflateRawSync } from 'node:zlib';
import { chromium } from 'playwright';
export const escapeHtml=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const stringify=(v:unknown)=>v===null||v===undefined?'':typeof v==='object'?JSON.stringify(v):String(v);
export function reportHtml(title:string,fields:{key:string;label:string}[],rows:Record<string,unknown>[],filters:unknown,landscape:boolean){
 const details=fields.length>8;
 const body=details?rows.map((r,i)=>`<section class="record"><h2>${i+1} · ${escapeHtml(r.family_code??r.person_name??r.group_name??'رکورد')}</h2><table><thead><tr><th>عنوان</th><th>مقدار</th></tr></thead><tbody>${fields.map(f=>{const text=stringify(r[f.key]),parts=text.match(/[\s\S]{1,400}/g)??[''];return parts.map((part,j)=>`<tr><th>${escapeHtml(f.label)}${j?' (ادامه)':''}</th><td>${escapeHtml(part)}</td></tr>`).join('');}).join('')}</tbody></table></section>`).join(''):`<table><thead><tr>${fields.map(f=>`<th>${escapeHtml(f.label)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${fields.map(f=>`<td>${escapeHtml(stringify(r[f.key]))}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>@page{size:A4 ${landscape?'landscape':'portrait'};margin:20mm 12mm 20mm;@bottom-center{content:counter(page) ' / ' counter(pages);font:9pt Arial}}*{box-sizing:border-box}body{font:11pt Tahoma,Arial,sans-serif;color:#231b33;line-height:1.8;margin:20px auto;max-width:${landscape?'273':'186'}mm}header{border-bottom:2px solid #624087;margin-bottom:14px}h1{font-size:19pt}h2{font-size:13pt}table{border-collapse:collapse;width:100%;table-layout:fixed;margin:12px 0}th,td{border:1px solid #aaa;padding:6px;text-align:right;overflow-wrap:anywhere;white-space:pre-wrap;vertical-align:top}th{background:#f0eaf7}thead{display:table-header-group}tr{break-inside:avoid;page-break-inside:avoid}.record h2{break-after:avoid}.record{break-before:auto}.meta{font-size:9pt;color:#555}.toolbar{display:flex;gap:20px;margin-bottom:20px}button{padding:10px;border:1px solid #624087;background:white;cursor:pointer}@media print{body{max-width:none;margin:0}.toolbar{display:none}header{break-inside:avoid}a{color:inherit;text-decoration:none}}</style></head><body><div class="toolbar"><button onclick="window.print()">چاپ A4</button><span>پیش‌نمایش چاپ · ${landscape?'افقی':'عمودی'}</span></div><header><h1>${escapeHtml(title)}</h1><p>کانون مهربانی همیاران لاهوت</p><p class="meta">تاریخ تولید: ${escapeHtml(new Date().toLocaleString('fa-IR'))} · تعداد رکورد: ${rows.length}</p><p class="meta">فیلترها: ${escapeHtml(JSON.stringify(filters))}</p></header>${body}</body></html>`;
}
function crc32(buffer:Buffer){let crc=0xffffffff;for(const byte of buffer){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
function zip(files:Record<string,string>){const local:Buffer[]=[],central:Buffer[]=[];let offset=0;for(const [name,text] of Object.entries(files)){const n=Buffer.from(name),raw=Buffer.from(text),compressed=deflateRawSync(raw),crc=crc32(raw),h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(8,8);h.writeUInt32LE(crc,14);h.writeUInt32LE(compressed.length,18);h.writeUInt32LE(raw.length,22);h.writeUInt16LE(n.length,26);local.push(h,n,compressed);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(8,10);c.writeUInt32LE(crc,16);c.writeUInt32LE(compressed.length,20);c.writeUInt32LE(raw.length,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(offset,42);central.push(c,n);offset+=h.length+n.length+compressed.length;}const directory=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(Object.keys(files).length,8);end.writeUInt16LE(Object.keys(files).length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,directory,end]);}
function column(i:number){let s='';for(i++;i;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s;}
export function workbook(title:string,fields:{key:string;label:string}[],rows:Record<string,unknown>[],landscape:boolean){const all:unknown[][]=[[title],fields.map(f=>f.label),...rows.map(r=>fields.map(f=>r[f.key]))];const content=all.map((r,i)=>`<row r="${i+1}">${r.map((v,j)=>`<c r="${column(j)}${i+1}" s="${i<2?1:0}" t="inlineStr"><is><t xml:space="preserve">${escapeHtml(stringify(v)).replace(/&#39;/g,'&apos;')}</t></is></c>`).join('')}</row>`).join('');return zip({
 '[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>',
 '_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
 'xl/workbook.xml':'<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="گزارش" sheetId="1" r:id="rId1"/></sheets></workbook>',
 'xl/_rels/workbook.xml.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
 'xl/styles.xml':'<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Arial"/></font><font><b/><sz val="11"/><name val="Arial"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="2"><xf fontId="0" xfId="0" applyAlignment="1"><alignment wrapText="1" vertical="top" readingOrder="2"/></xf><xf fontId="1" xfId="0" applyAlignment="1"><alignment wrapText="1" readingOrder="2"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>',
 'xl/worksheets/sheet1.xml':`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr><sheetViews><sheetView workbookViewId="0" rightToLeft="1"/></sheetViews><cols>${fields.map((_,i)=>`<col min="${i+1}" max="${i+1}" width="25" customWidth="1"/>`).join('')}</cols><sheetData>${content}</sheetData><pageMargins left="0.4" right="0.4" top="0.6" bottom="0.6" header="0.2" footer="0.2"/><pageSetup paperSize="9" orientation="${landscape?'landscape':'portrait'}" fitToWidth="1" fitToHeight="0"/><headerFooter><oddFooter>&amp;C&amp;P / &amp;N</oddFooter></headerFooter></worksheet>`
 });}
let activePdfs=0;
export async function pdfDocument(html:string,title:string,landscape:boolean){if(activePdfs>=2)throw new Error('PDF_BUSY');activePdfs++;let browser;try{browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});const page=await browser.newPage();await page.route('**/*',r=>r.abort());await page.setContent(html,{waitUntil:'load'});await page.emulateMedia({media:'print'});return await page.pdf({format:'A4',landscape,printBackground:true,preferCSSPageSize:true,displayHeaderFooter:true,headerTemplate:`<div style="font:8px Arial;width:100%;text-align:center">${escapeHtml(title)}</div>`,footerTemplate:'<div style="font:9px Arial;width:100%;text-align:center"><span class="pageNumber"></span> / <span class="totalPages"></span></div>',margin:{top:'20mm',bottom:'20mm',left:'12mm',right:'12mm'}});}finally{if(browser)await browser.close();activePdfs--;}}
