import {recheckContext} from '../auth/role-context';
import { Inject, Injectable } from '@nestjs/common';
import { Pool, PoolClient } from 'pg';
import { randomUUID } from 'node:crypto';
import { PG_POOL } from '../database/database.constants';
import { GuidanceService, input, str, id } from '../guidance/guidance.service';
import { AppError } from '../common/app-error';
import type { AuthUser } from '../auth/auth.types';
const active="r.valid_from<=now() AND (r.valid_to IS NULL OR r.valid_to>now())";
export const role=(u:AuthUser,code:string)=>u.roles.some(r=>r.roleCode===code&&r.scopeType==='ORGANIZATION');
const permissionSQL=`SELECT v.*,p.first_name||' '||p.last_name AS person_name,a.username AS requester,
 CASE WHEN v.decision IS NOT NULL THEN v.decision WHEN v.seen_at IS NOT NULL THEN 'SEEN' ELSE 'NEW' END AS status FROM guidance.permission_checks v JOIN identity.people p ON p.id=v.person_id JOIN identity.accounts a ON a.id=v.requested_by`;
@Injectable()
export class ReviewService {
 constructor(@Inject(PG_POOL) readonly pool:Pool,readonly g:GuidanceService){}
 private executive(u:AuthUser){if(!role(u,'EXECUTIVE_MANAGER'))throw new AppError(403,'FORBIDDEN','این اقدام فقط برای مدیر اجرایی مجاز است.');}
 private async executives(c:PoolClient){return(await c.query(`SELECT DISTINCT r.account_id FROM identity.role_assignments r JOIN identity.accounts a ON a.id=r.account_id WHERE r.role_code='EXECUTIVE_MANAGER' AND r.scope_type='ORGANIZATION' AND a.status='ACTIVE' AND ${active}`)).rows.map(r=>r.account_id);}
 private async currentContext(c:PoolClient,u:AuthUser,person:string|null,family:string|null,group:string|null){
 const roles=(await recheckContext(c,u)).map(r=>({role_code:r.roleCode,scope_type:r.scopeType,scope_id:r.scopeId}));
 const guide=roles.some(r=>r.role_code==='SUPREME_GUIDE'&&r.scope_type==='ORGANIZATION');if(guide)return;
 if(person)throw new AppError(403,'FORBIDDEN','دسترسی مجاز نیست.');
 if(family){const f=(await c.query('SELECT current_group_id AS group_id FROM family.families WHERE id=$1 FOR SHARE',[family])).rows[0];if(!f)throw new AppError(404,'NOT_FOUND','پرونده پیدا نشد.');group=f.group_id;}
 if(roles.some(r=>r.role_code==='EXECUTIVE_MANAGER'&&r.scope_type==='ORGANIZATION'))return;
 if(!group||!roles.some(r=>r.scope_type==='GROUP'&&r.scope_id===group&&['HELPER','GROUP_LEADER'].includes(r.role_code)))throw new AppError(403,'FORBIDDEN','این مورد در محدوده دسترسی شما نیست.');
 }
 async linkedNotify(c:PoolClient,recipients:string[],text:string,category:string,type:string,entity:string){for(const recipient of new Set(recipients))await c.query(`INSERT INTO guidance.notifications(recipient_id,category,message,visibility,dedupe_key,link_type,link_id) VALUES($1,$2,$3,'PRIVATE',$4,$5,$6)`,[recipient,category,text,randomUUID(),type,entity]);}
 async dashboard(){await this.g.automation();return(await this.pool.query(`SELECT (SELECT count(*)::int FROM identity.access_requests WHERE status='PENDING_GUIDE_APPROVAL') AS access,
 (SELECT count(*)::int FROM guidance.permission_checks WHERE decision IS NULL) AS permissions,
 (SELECT count(*)::int FROM guidance.alerts WHERE closed_at IS NULL AND severity IN ('RED','AMBER')) AS alerts,
 (SELECT count(*)::int FROM guidance.items WHERE kind='COUNCIL' AND review_state IN ('PENDING','RECONSIDER') AND lifecycle='ACTIVE') AS council`)).rows[0];}
 async people(q:Record<string,string>){const data=await this.g.people(q);const total=data.people.length;const page=Math.max(1,Number(q.page)||1),size=25;if(q.page)data.people=data.people.slice((page-1)*size,page*size);for(const p of data.people){const stats=(await this.pool.query(`SELECT
 (SELECT count(*)::int FROM guidance.alerts a JOIN guidance.items i ON i.id=a.item_id WHERE i.person_id=$1 AND a.closed_at IS NULL AND a.severity='RED') AS red,
 (SELECT count(*)::int FROM guidance.alerts a JOIN guidance.items i ON i.id=a.item_id WHERE i.person_id=$1 AND a.closed_at IS NULL AND a.severity='AMBER') AS amber,
 (SELECT count(*)::int FROM guidance.permission_checks WHERE person_id=$1 AND decision IS NULL)+(SELECT count(*)::int FROM guidance.items i WHERE i.person_id=$1 AND i.note_type='MESSAGE' AND EXISTS(SELECT 1 FROM guidance.recipients r JOIN identity.role_assignments ra ON ra.account_id=r.account_id WHERE r.item_id=i.id AND r.seen_at IS NULL AND ra.role_code='SUPREME_GUIDE' AND ra.valid_to IS NULL)) AS info`,[p.id])).rows[0];p.badges=stats;}return {...data,total,page,pageSize:size};}
 async person(personId:string,u:AuthUser){const data=await this.g.person(id(personId));return {...data,alerts:(await this.alerts({person:personId},u)).alerts,notes:(await this.pool.query(`SELECT i.*,EXISTS(SELECT 1 FROM guidance.recipients r WHERE r.item_id=i.id AND r.account_id=$2 AND r.seen_at IS NULL) AS unread FROM guidance.items i JOIN identity.accounts a ON a.id=i.created_by WHERE i.person_id=$1 OR (i.kind='COORDINATION' AND a.person_id=$1) ORDER BY i.created_at DESC`,[personId,u.accountId])).rows,permissions:(await this.pool.query(permissionSQL+' WHERE v.person_id=$1 ORDER BY v.created_at DESC',[personId])).rows};}
 async permissionPeople(u:AuthUser){this.executive(u);return {people:(await this.pool.query("SELECT p.id,p.first_name,p.last_name FROM identity.people p JOIN identity.accounts a ON a.person_id=p.id WHERE a.status='ACTIVE' ORDER BY p.last_name,p.id")).rows};}
 async permissions(u:AuthUser){if(!this.g.isGuide(u))this.executive(u);return {requests:(await this.pool.query(permissionSQL+' WHERE ($1 OR v.requested_by=$2) ORDER BY v.created_at DESC,v.id',[this.g.isGuide(u),u.accountId])).rows};}
 async permissionDetail(vId:string,u:AuthUser){id(vId);if(!this.g.isGuide(u))this.executive(u);const v=(await this.pool.query(permissionSQL+' WHERE v.id=$1 AND ($2 OR v.requested_by=$3)',[vId,this.g.isGuide(u),u.accountId])).rows[0];if(!v)throw new AppError(404,'NOT_FOUND','مورد پیدا نشد.');return {request:v,history:(await this.pool.query("SELECT * FROM guidance.history WHERE entity_type='PERMISSION_CHECK' AND entity_id=$1 ORDER BY occurred_at,id",[vId])).rows};}
 async submitPermission(value:unknown,u:AuthUser){throw new AppError(410,'RETIRED','گردش‌کار مجوز موردی غیرفعال شده است.');}
 private async retiredSubmitPermission(value:unknown,u:AuthUser){this.executive(u);const b=input(value),person=id(b.personId),subject=str(b.subject),explanation=str(b.explanation,4000);return this.g.tx(u,async c=>{if(!(await this.executives(c)).includes(u.accountId))throw new AppError(403,'FORBIDDEN','نقش مدیر اجرایی فعال نیست.');const v=(await c.query('INSERT INTO guidance.permission_checks(person_id,subject,explanation,requested_by) VALUES($1,$2,$3,$4) RETURNING *',[person,subject,explanation,u.accountId])).rows[0];await this.g.history(c,u,'PERMISSION_CHECK',v.id,'PERMISSION_REQUESTED',null,v);await this.linkedNotify(c,await this.g.guides(c),'مجوز موردی منتظر تصمیم: '+subject,'PERMISSION','PERMISSION',v.id);return v;},false);}
 async permissionSeen(vId:string,u:AuthUser){id(vId);return this.g.tx(u,async c=>{const old=(await c.query('SELECT * FROM guidance.permission_checks WHERE id=$1 FOR UPDATE',[vId])).rows[0];if(!old)throw new AppError(404,'NOT_FOUND','مورد پیدا نشد.');if(!old.seen_at&&!old.decision){await c.query('UPDATE guidance.permission_checks SET seen_at=now() WHERE id=$1',[vId]);await this.g.history(c,u,'PERMISSION_CHECK',vId,'PERMISSION_SEEN',null,{seen:true});}return {ok:true};});}
 async decidePermission(vId:string,value:unknown,u:AuthUser){throw new AppError(410,'RETIRED','گردش‌کار مجوز موردی غیرفعال شده است.');}
 private async retiredDecidePermission(vId:string,value:unknown,u:AuthUser){id(vId);const b=input(value),decision=str(b.decision);if(!['APPROVED','NOT_APPROVED'].includes(decision))throw new AppError(400,'INVALID','تصمیم معتبر نیست.');return this.g.tx(u,async c=>{const old=(await c.query('SELECT * FROM guidance.permission_checks WHERE id=$1 FOR UPDATE',[vId])).rows[0];if(!old)throw new AppError(404,'NOT_FOUND','مورد پیدا نشد.');if(old.decision)throw new AppError(409,'FINAL','تصمیم قبلاً ثبت شده است.');const next=(await c.query('UPDATE guidance.permission_checks SET decision=$2,decided_by=$3,decided_at=now(),seen_at=COALESCE(seen_at,now()) WHERE id=$1 RETURNING *',[vId,decision,u.accountId])).rows[0];await this.g.history(c,u,'PERMISSION_CHECK',vId,'PERMISSION_DECIDED',old,next);await this.linkedNotify(c,[old.requested_by],'نتیجه مجوز موردی: '+old.subject,'PERMISSION_RESULT','PERMISSION',vId);return next;});}
 async council(q:Record<string,string>){const params:unknown[]=[q.q??'',q.state??''];let where="i.kind='COUNCIL' AND ($1='' OR concat_ws(' ',i.subject,i.body,a.username) ILIKE '%'||$1||'%') AND ($2='' OR i.review_state=$2)";for(const [key,op] of [['from','>='],['to','<=']])if(q[key]){if(!/^\d{4}-\d{2}-\d{2}$/.test(q[key])||!Number.isFinite(Date.parse(q[key])))throw new AppError(400,'DATE','تاریخ معتبر نیست.');params.push(q[key]);where+=` AND i.created_at::date ${op} $${params.length}::date`;}if(q.creator){params.push(id(q.creator));where+=` AND i.created_by=$${params.length}`;}const sort=q.sort==='oldest'?'ASC':'DESC';return {items:(await this.pool.query(`SELECT i.*,a.username AS creator FROM guidance.items i JOIN identity.accounts a ON a.id=i.created_by WHERE ${where} ORDER BY i.created_at ${sort},i.id`,params)).rows};}
 async councilDetail(itemId:string,u:AuthUser){const data=await this.g.detail(id(itemId),u);if(data.item.kind!=='COUNCIL')throw new AppError(404,'NOT_FOUND','مصوبه پیدا نشد.');return {...data,attachments:(await this.pool.query('SELECT id,name,media_type FROM guidance.attachments WHERE item_id=$1',[itemId])).rows};}
 async councilIntervene(itemId:string,value:unknown,u:AuthUser){throw new AppError(410,'READ_ONLY','آرشیو مصوبات فقط خواندنی است.');}
 private async retiredCouncilIntervene(itemId:string,value:unknown,u:AuthUser){id(itemId);const b=input(value),action=str(b.action),reason=str(b.reason,2000,true);if(!['STOP','REVIEW'].includes(action))throw new AppError(400,'INVALID','فقط توقف اجرا یا درخواست بازنگری مجاز است.');return this.g.tx(u,async c=>{const old=(await c.query("SELECT * FROM guidance.items WHERE id=$1 AND kind='COUNCIL' FOR UPDATE",[itemId])).rows[0];if(!old)throw new AppError(404,'NOT_FOUND','مصوبه پیدا نشد.');if(b.version!==old.version)throw new AppError(409,'STALE','مصوبه تغییر کرده است؛ صفحه را تازه کنید.');const next=(await c.query(`UPDATE guidance.items SET review_state=$2,execution_status=CASE WHEN $2='STOPPED' THEN 'STOPPED' ELSE execution_status END,version=version+1 WHERE id=$1 RETURNING *`,[itemId,action==='STOP'?'STOPPED':'RECONSIDER'])).rows[0];await this.g.history(c,u,'ITEM',itemId,'COUNCIL_'+action,old,next,reason);await this.linkedNotify(c,await this.executives(c),'اقدام راهبر درباره مصوبه: '+old.subject,'COUNCIL','COUNCIL',itemId);return next;});}
 async attachment(itemId:string,attachmentId:string){id(itemId);id(attachmentId);const a=(await this.pool.query("SELECT d.* FROM guidance.attachments d JOIN guidance.items i ON i.id=d.item_id WHERE d.id=$1 AND d.item_id=$2 AND i.kind='COUNCIL'",[attachmentId,itemId])).rows[0];if(!a)throw new AppError(404,'NOT_FOUND','مدرک پیدا نشد.');return a;}
 async scope(u:AuthUser,groupId:string){id(groupId);if(this.g.isGuide(u)||role(u,'EXECUTIVE_MANAGER'))return;if(!u.roles.some(r=>r.scopeType==='GROUP'&&r.scopeId===groupId&&['GROUP_LEADER','HELPER'].includes(r.roleCode)))throw new AppError(403,'FORBIDDEN','این گروه در محدوده دسترسی شما نیست.');}
 async groups(q:Record<string,string>,u:AuthUser){let rows=(await this.pool.query(`SELECT g.*,l.person_id AS leader_person_id,l.name AS leader_name,
 (SELECT count(DISTINCT r.account_id)::int FROM identity.role_assignments r WHERE r.scope_id=g.group_id AND r.role_code='HELPER' AND ${active}) AS helper_count,
 (SELECT count(*)::int FROM guidance.alerts a JOIN guidance.items i ON i.id=a.item_id WHERE i.group_id=g.group_id AND a.closed_at IS NULL) AS group_alerts
 FROM monitoring.group_facts g LEFT JOIN LATERAL(SELECT p.id AS person_id,p.first_name||' '||p.last_name AS name FROM identity.role_assignments r JOIN identity.accounts a ON a.id=r.account_id JOIN identity.people p ON p.id=a.person_id WHERE r.scope_id=g.group_id AND r.role_code='GROUP_LEADER' AND ${active} LIMIT 1) l ON true ORDER BY g.group_number`)).rows;
 if(!this.g.isGuide(u)&&!role(u,'EXECUTIVE_MANAGER'))rows=rows.filter(g=>u.roles.some(r=>r.scopeId===g.group_id));
 if(q.group)rows=rows.filter(g=>g.group_id===q.group);if(q.leader)rows=rows.filter(g=>g.leader_person_id===q.leader);if(q.state)rows=rows.filter(g=>g.status===q.state);for(const [key,col] of [['minFamilies','family_count'],['minScore','avg_need_score'],['minAlerts','open_alerts']])if(q[key]){const n=Number(q[key]);if(!Number.isFinite(n))throw new AppError(400,'INVALID','فیلتر عددی معتبر نیست.');rows=rows.filter(g=>Number(g[col])>=n);}
 if(q.level)rows=rows.filter(g=>Number(g['level_'+q.level.toLowerCase()])>0);if(q.overdue==='true')rows=rows.filter(g=>g.overdue_research>0);if(q.review==='true')rows=rows.filter(g=>g.review_required>0);
 if(q.urgency) {const ids=(await this.pool.query('SELECT DISTINCT group_id FROM monitoring.family_facts WHERE urgency=$1',[q.urgency])).rows.map(r=>r.group_id);rows=rows.filter(g=>ids.includes(g.group_id));}
 const sorts:Record<string,string>={families:'family_count',levelA:'level_a',alerts:'open_alerts',overdue:'overdue_research',score:'avg_need_score'};if(sorts[q.sort])rows.sort((a,b)=>Number(b[sorts[q.sort]])-Number(a[sorts[q.sort]]));return {groups:rows,actions:this.g.isGuide(u)?['CREATE','TRANSFER_DEACTIVATE','REACTIVATE']:[]};}
 async group(groupId:string,q:Record<string,string>,u:AuthUser){await this.scope(u,groupId);const data=(await this.groups({},u)).groups.find(g=>g.group_id===groupId);if(!data)throw new AppError(404,'NOT_FOUND','گروه پیدا نشد.');return {group:data,members:(await this.g.people({group:groupId})).people,families:await this.familyRows({...q,group:groupId}),alerts:(await this.alerts({group:groupId,scope:'GROUP'},u)).alerts,actions:this.g.isGuide(u)?['VIEW','TRANSFER']:['VIEW']};}
 async familyRows(q:Record<string,string>){const clauses:string[]=[],values:unknown[]=[];const add=(sql:string,v:unknown)=>{values.push(v);clauses.push(sql.replace('?',`$${values.length}`));};
 for(const [key,col] of [['group','group_id'],['family','family_id']])if(q[key])add(`${col}=?`,id(q[key]));if(q.q)add("concat_ws(' ',family_code,head_name) ILIKE '%'||?||'%'",str(q.q));for(const [key,col] of [['level','need_level'],['urgency','urgency'],['research','research_status'],['support','support_status']])if(q[key])add(`${col}=?`,str(q[key]));for(const [key,op] of [['minScore','>='],['maxScore','<=']])if(q[key]){const n=Number(q[key]);if(!Number.isFinite(n))throw new AppError(400,'INVALID','امتیاز معتبر نیست.');add('score'+op+'?',n);}if(q.review==='true')clauses.push('review_required');if(q.alert==='true')clauses.push('open_alerts>0');if(q.lastResearch){if(!/^\d{4}-\d{2}-\d{2}$/.test(q.lastResearch)||!Number.isFinite(Date.parse(q.lastResearch)))throw new AppError(400,'INVALID','تاریخ معتبر نیست.');add('last_research_at::date<=?::date',q.lastResearch);}if(q.domain)add('domains ? ?',str(q.domain));
 // JSON existence has its own operator; avoid treating that operator as a placeholder.
 if(q.domain)clauses[clauses.length-1]=`domains ? $${values.length}`;
 return(await this.pool.query('SELECT * FROM monitoring.family_facts'+(clauses.length?' WHERE '+clauses.join(' AND '):'')+' ORDER BY family_code',values)).rows;
 }
 async family(familyId:string,u:AuthUser){id(familyId);const f=(await this.familyRows({family:familyId}))[0];if(!f)throw new AppError(404,'NOT_FOUND','پرونده پیدا نشد.');await this.scope(u,f.group_id);return {family:f,members:(await this.pool.query('SELECT p.*,m.relationship_code FROM family.family_memberships m JOIN identity.people p ON p.id=m.person_id WHERE m.family_id=$1 AND m.valid_to IS NULL',[familyId])).rows,research:(await this.pool.query('SELECT * FROM family.research_records WHERE family_id=$1 ORDER BY recorded_at DESC',[familyId])).rows,documents:(await this.pool.query('SELECT id,name,media_type FROM family.documents WHERE family_id=$1',[familyId])).rows,supports:(await this.pool.query('SELECT * FROM monitoring.support_records WHERE family_id=$1 ORDER BY occurred_at DESC',[familyId])).rows,alerts:(await this.alerts({family:familyId},u)).alerts,history:(await this.pool.query("SELECT h.*,a.username AS actor_name FROM guidance.history h LEFT JOIN identity.accounts a ON a.id=h.actor_id WHERE (entity_type='FAMILY' AND entity_id=$1) OR (entity_type='ITEM' AND entity_id IN(SELECT id FROM guidance.items WHERE family_id=$1)) ORDER BY occurred_at DESC",[familyId])).rows};}
 async document(familyId:string,docId:string,u:AuthUser){await this.family(familyId,u);const d=(await this.pool.query('SELECT * FROM family.documents WHERE id=$1 AND family_id=$2',[id(docId),familyId])).rows[0];if(!d)throw new AppError(404,'NOT_FOUND','مدرک پیدا نشد.');return d;}
 private async move(c:PoolClient,familyId:string,target:string,source:string,u:AuthUser){const old=(await c.query('SELECT * FROM family.families WHERE id=$1 FOR UPDATE',[familyId])).rows[0];if(!old||old.current_group_id!==source)throw new AppError(409,'STALE','گروه خانواده تغییر کرده است؛ دوباره بررسی کنید.');if(target===source||!(await c.query("SELECT 1 FROM organization.groups WHERE id=$1 AND status='ACTIVE' FOR UPDATE",[target])).rowCount)throw new AppError(409,'DESTINATION','گروه مقصد باید فعال و متفاوت باشد.');const next=(await c.query('UPDATE family.families SET current_group_id=$2,version=version+1,updated_at=now() WHERE id=$1 RETURNING *',[familyId,target])).rows[0];await this.g.history(c,u,'FAMILY',familyId,'FAMILY_TRANSFERRED',old,{...next,from_group_id:source,to_group_id:target});const leader=(await c.query("SELECT account_id FROM identity.role_assignments r WHERE scope_id=$1 AND role_code='GROUP_LEADER' AND "+active,[target])).rows[0]?.account_id;const alerts=(await c.query("UPDATE oversight.alerts SET owner_id=$2,escalated=($2::uuid IS NULL),updated_at=now() WHERE family_id=$1 AND state<>'RESOLVED' RETURNING id",[familyId,leader??null])).rows;for(const a of alerts)await this.g.history(c,u,'ALERT',a.id,'ALERT_OWNER_CHANGED',null,{owner_id:leader??null});await this.g.history(c,u,'GROUP',source,'FAMILY_TRANSFER_OUT',null,{familyId,target});await this.g.history(c,u,'GROUP',target,'FAMILY_TRANSFER_IN',null,{familyId,source});}
 async transfer(familyId:string,value:unknown,u:AuthUser){const b=input(value),source=id(b.sourceGroupId),target=id(b.targetGroupId);id(familyId);return this.g.tx(u,async c=>{await this.move(c,familyId,target,source,u);await this.linkedNotify(c,await this.executives(c),'انتقال خانواده ثبت شد.','FAMILY_TRANSFER','FAMILY',familyId);return {ok:true};});}
 async deactivate(groupId:string,value:unknown,u:AuthUser){id(groupId);const b=input(value);if(!Array.isArray(b.moves))throw new AppError(400,'INVALID','مقصد خانواده‌ها مشخص نشده است.');const moves=b.moves.map(x=>{const m=input(x);return {familyId:id(m.familyId),target:id(m.targetGroupId)};});return this.g.tx(u,async c=>{const old=(await c.query("SELECT * FROM organization.groups WHERE id=$1 AND status='ACTIVE' FOR UPDATE",[groupId])).rows[0];if(!old)throw new AppError(409,'STALE','گروه فعال پیدا نشد.');const families=(await c.query('SELECT id FROM family.families WHERE current_group_id=$1 FOR UPDATE',[groupId])).rows.map(f=>f.id);if(new Set(moves.map(m=>m.familyId)).size!==moves.length||moves.length!==families.length||!families.every(f=>moves.some(m=>m.familyId===f)))throw new AppError(409,'INCOMPLETE','برای تمام خانواده‌های فعلی یک مقصد تعیین کنید.');for(const m of moves)await this.move(c,m.familyId,m.target,groupId,u);const assignments=(await c.query(`SELECT r.*,a.person_id FROM identity.role_assignments r JOIN identity.accounts a ON a.id=r.account_id WHERE r.scope_id=$1 AND ${active}`,[groupId])).rows;for(const r of assignments){await c.query('UPDATE identity.role_assignments SET valid_to=now() WHERE id=$1',[r.id]);await this.g.history(c,u,'PERSON',r.person_id,'ROLE_ENDED',r,null,'غیرفعال‌سازی گروه');}await c.query("UPDATE organization.groups SET status='INACTIVE' WHERE id=$1",[groupId]);await this.g.history(c,u,'GROUP',groupId,'GROUP_DEACTIVATED',old,{...old,status:'INACTIVE',moves});await this.linkedNotify(c,await this.executives(c),'انتقال خانواده‌ها و غیرفعال‌سازی گروه ثبت شد.','GROUP','GROUP',groupId);return {ok:true};});}
 async reactivate(groupId:string,value:unknown,u:AuthUser){id(groupId);const b=input(value),account=id(b.accountId);return this.g.tx(u,async c=>{const old=(await c.query("SELECT * FROM organization.groups WHERE id=$1 AND status IN ('INACTIVE','DISSOLVED') FOR UPDATE",[groupId])).rows[0];if(!old)throw new AppError(409,'STALE','گروه غیرفعال پیدا نشد.');await c.query("UPDATE organization.groups SET status='ACTIVE' WHERE id=$1",[groupId]);await this.g.assignment(c,u,account,'GROUP_LEADER',groupId,'فعال‌سازی مجدد');await this.g.history(c,u,'GROUP',groupId,'GROUP_REACTIVATED',old,{...old,status:'ACTIVE'});return {ok:true};});}
 async alerts(q:Record<string,string>,u:AuthUser){let rows=(await this.pool.query(`SELECT a.*,i.subject,i.body,i.person_id,i.group_id,i.family_id,i.note_type,i.created_by,f.current_group_id AS family_group_id FROM guidance.alerts a JOIN guidance.items i ON i.id=a.item_id LEFT JOIN family.families f ON f.id=i.family_id ORDER BY a.created_at DESC,a.id`)).rows;
 if(!this.g.isGuide(u)&&!role(u,'EXECUTIVE_MANAGER'))rows=rows.filter(a=>a.family_group_id&&u.roles.some(r=>r.scopeId===a.family_group_id)||a.group_id&&u.roles.some(r=>r.scopeId===a.group_id));
 for(const [key,col] of [['severity','severity'],['person','person_id'],['family','family_id'],['type','note_type']])if(q[key])rows=rows.filter(a=>a[col]===q[key]);if(q.group)rows=rows.filter(a=>a.group_id===q.group||(q.scope!=='GROUP'&&a.family_group_id===q.group));if(q.state==='OPEN')rows=rows.filter(a=>!a.closed_at);if(q.state==='RESOLVED')rows=rows.filter(a=>!!a.closed_at);for(const [k,op] of [['from',1],['to',-1]] as const)if(q[k]){const t=Date.parse(q[k]+(k==='to'?'T23:59:59.999Z':'T00:00:00Z'));if(!Number.isFinite(t))throw new AppError(400,'DATE','تاریخ معتبر نیست.');rows=rows.filter(a=>op===1?new Date(a.created_at).getTime()>=t:new Date(a.created_at).getTime()<=t);}return {alerts:rows};}
 async note(value:unknown,u:AuthUser){const b=input(value),type=str(b.type),subject=str(b.subject),body=str(b.body,4000);if(!['WARNING','REMINDER','MESSAGE','COORDINATION'].includes(type))throw new AppError(400,'INVALID','نوع یادداشت معتبر نیست.');const person=b.personId?id(b.personId):null,family=b.familyId?id(b.familyId):null,group=b.groupId?id(b.groupId):null;if([person,family,group].filter(Boolean).length!==1)throw new AppError(400,'CONTEXT','یک زمینه مشخص لازم است.');if(person&&!this.g.isGuide(u))throw new AppError(403,'FORBIDDEN','دسترسی مجاز نیست.');if(family)await this.family(family,u);if(group)await this.scope(u,group);return this.g.tx(u,async c=>{await this.currentContext(c,u,person,family,group);const item=(await c.query("INSERT INTO guidance.items(kind,subject,body,created_by,audience_type,confidential,person_id,family_id,group_id,note_type) VALUES('NOTE',$1,$2,$3,'GUIDE',true,$4,$5,$6,$7) RETURNING *",[subject,body,u.accountId,person,family,group,type])).rows[0];for(const guide of await this.g.guides(c))await c.query('INSERT INTO guidance.recipients(item_id,account_id) VALUES($1,$2)',[item.id,guide]);if(type==='REMINDER')await c.query('INSERT INTO oversight.reminders(legacy_item_id,person_id,family_id,group_id,subject,created_by) VALUES($1,$2,$3,$4,$5,$6)',[item.id,person,family,group,subject,u.accountId]);await this.g.history(c,u,'ITEM',item.id,'CONTEXT_NOTE',null,item);await this.linkedNotify(c,await this.g.guides(c),subject,'CONTEXT',family?'FAMILY':person?'PERSON':'GROUP',family??person??group!);return item;},false);}
 async resolve(alertId:string,value:unknown,u:AuthUser){throw new AppError(410,'ALERT_OWNER','رسیدگی از مسیر مسئول هشدار انجام می‌شود.');}
 private async retiredResolve(alertId:string,value:unknown,u:AuthUser){id(alertId);const b=input(value),result=str(b.result,4000);if(b.actionCompleted!==true)throw new AppError(400,'RESULT','انجام اقدام و ثبت نتیجه الزامی است.');const alert=(await this.alerts({},u)).alerts.find(a=>a.id===alertId);if(!alert)throw new AppError(404,'NOT_FOUND','هشدار پیدا نشد.');return this.g.tx(u,async c=>{await this.currentContext(c,u,alert.person_id,alert.family_id,alert.group_id);const old=(await c.query('SELECT * FROM guidance.alerts WHERE id=$1 FOR UPDATE',[alertId])).rows[0];if(old.closed_at)throw new AppError(409,'FINAL','هشدار قبلاً رسیدگی شده است.');await c.query('UPDATE guidance.alerts SET closed_at=now() WHERE id=$1',[alertId]);await c.query('UPDATE guidance.items SET completed_at=now(),result=$2,version=version+1 WHERE id=$1',[old.item_id,result]);await this.g.history(c,u,'ITEM',old.item_id,'ALERT_RESOLVED',old,{actionCompleted:true,result});await this.linkedNotify(c,await this.g.guides(c),'نتیجه رسیدگی به هشدار ثبت شد.','ALERT_RESULT',alert.family_id?'FAMILY':alert.person_id?'PERSON':alert.group_id?'GROUP':'ITEM',alert.family_id??alert.person_id??alert.group_id??alert.item_id);return {ok:true};},false);}
}
