import { PeoplePage, PersonPage, AppointmentsPage, GroupsPage, GroupPage, ItemsPage, ItemPage, AlertsPage, ReportsPage, NotificationsPage, FamilyReadPage } from './pages/GuideWorkspace';
import { Navigate, Route, Routes } from 'react-router-dom';
import { useAuth } from './auth/AuthProvider';
import { LoginPage } from './pages/LoginPage';
import { GuidePage } from './pages/GuidePage';
import { AccessRequestsPage } from './pages/AccessRequestsPage';
import { AccessRequestDetailPage } from './pages/AccessRequestDetailPage';
import './style.css';
export default function App() {
 const { user, loading } = useAuth();
 if (loading) return <main className="loading" role="status">در حال بررسی نشست…</main>;
 const guide = user?.roles.some(r => r.roleCode === 'SUPREME_GUIDE' && r.scopeType === 'ORGANIZATION' && r.scopeId === null);
 return <Routes><Route path="/login" element={user ? <Navigate to={guide ? '/guide' : '/workspace'} replace /> : <LoginPage />} /><Route path="/guide" element={guide ? <GuidePage /> : <Navigate to="/login" replace />} /><Route path="/guide/access-requests" element={guide ? <AccessRequestsPage /> : <Navigate to="/login" replace />} /><Route path="/guide/access-requests/:id" element={guide ? <AccessRequestDetailPage /> : <Navigate to="/login" replace />} /><Route path="/guide/people" element={guide ? <PeoplePage/> : <Navigate to="/login" replace/>}/><Route path="/guide/people/:id" element={guide ? <PersonPage/> : <Navigate to="/login" replace/>}/><Route path="/guide/appointments" element={guide ? <AppointmentsPage/> : <Navigate to="/login" replace/>}/><Route path="/guide/groups" element={guide ? <GroupsPage/> : <Navigate to="/login" replace/>}/><Route path="/guide/groups/:id" element={guide ? <GroupPage/> : <Navigate to="/login" replace/>}/><Route path="/guide/leadership" element={guide ? <ItemsPage/> : <Navigate to="/login" replace/>}/><Route path="/guide/council-decisions" element={guide ? <ItemsPage kind="COUNCIL" title="مصوبات و بازنگری"/> : <Navigate to="/login" replace/>}/><Route path="/guide/urgent" element={guide ? <ItemsPage kind="URGENT" title="موارد فوری"/> : <Navigate to="/login" replace/>}/><Route path="/guide/alerts" element={guide ? <AlertsPage/> : <Navigate to="/login" replace/>}/><Route path="/guide/reports" element={guide ? <ReportsPage/> : <Navigate to="/login" replace/>}/><Route path="/guide/families/:id" element={guide ? <FamilyReadPage/> : <Navigate to="/login" replace/>}/><Route path="/guide/coordination" element={user ? <ItemsPage kind="COORDINATION" title="هماهنگی با راهبر" recipient/> : <Navigate to="/login" replace/>}/><Route path="/workspace" element={user ? <ItemsPage title="پیام‌ها و پیگیری‌های من" recipient/> : <Navigate to="/login" replace/>}/><Route path="/workspace/items/:id" element={user ? <ItemPage/> : <Navigate to="/login" replace/>}/><Route path="/workspace/notifications" element={user ? <NotificationsPage/> : <Navigate to="/login" replace/>}/><Route path="*" element={<Navigate to={guide ? '/guide' : user ? '/workspace' : '/login'} replace />} /></Routes>;
}
