import {assertLegacyWritable} from '../oversight/legacy-assessment';
import {recheckContext} from '../auth/role-context';
import {Inject,Injectable} from '@nestjs/common';
import {Pool,PoolClient} from 'pg';
import {PG_POOL} from '../database/database.constants';
import {GuidanceService,input,str,id} from '../guidance/guidance.service';
import {ReviewService} from '../review/review.service';
import {AppError} from '../common/app-error';
import type {AuthUser} from '../auth/auth.types';
import {evaluate,validateModel,type Model,type DomainInput} from './scoring';
const current="r.valid_from<=now() AND (r.valid_to IS NULL OR r.valid_to>now())";
@Injectable()
export class AssessmentService {
 constructor(@Inject(PG_POOL) private pool:Pool,private g:GuidanceService,private review:ReviewService){}
 async models(){return {models:(await this.pool.query('SELECT id,version,title,state,definition,created_at FROM assessment.models ORDER BY created_at DESC')).rows};}
 async transition(modelId:string,value:unknown,u:AuthUser){const b=input(value),state=str(b.state);return this.g.tx(u,async c=>{
 if(u.effectiveRole!=='TECH_ADMIN'||u.simulation)throw new AppError(403,'FORBIDDEN','نقش فنی فعال لازم است.');const auth=await c.query(`SELECT 1 FROM identity.role_assignments r WHERE r.account_id=$1 AND r.role_code='TECH_ADMIN' AND r.scope_type='ORGANIZATION' AND ${current}`,[u.accountId]);if(!auth.rowCount)throw new AppError(403,'FORBIDDEN','مدیریت نسخه مدل فقط در اختیار مدیر فنی است.');
 await c.query("SELECT pg_advisory_xact_lock(hashtext('assessment:model'))");
 const m=(await c.query('SELECT * FROM assessment.models WHERE id=$1 FOR UPDATE',[id(modelId)])).rows[0];if(!m)throw new AppError(404,'NOT_FOUND','مدل پیدا نشد.');
 if(!({DRAFT:'APPROVED',APPROVED:'ACTIVE',ACTIVE:'RETIRED'} as Record<string,string>)[m.state]||({DRAFT:'APPROVED',APPROVED:'ACTIVE',ACTIVE:'RETIRED'} as Record<string,string>)[m.state]!==state)throw new AppError(409,'STATE','ترتیب انتشار مدل معتبر نیست.');
 try{if(m.definition.engine==='comprehensive-v2'){
 const reference=(await c.query("SELECT definition,form_schema FROM assessment.models WHERE version='2.0'")).rows[0];
 if(JSON.stringify(m.definition)!==JSON.stringify(reference.definition)||JSON.stringify(m.form_schema)!==JSON.stringify(reference.form_schema))throw new Error('Unsupported assessment model: scoring changes need an implemented engine.');
 }else{if(state==='ACTIVE')throw new Error('Legacy assessment models are read-only.');validateModel(m.definition);}}catch(e){throw new AppError(422,'MODEL_INCOMPLETE',(e as Error).message);}
 if(state==='ACTIVE'){const old=(await c.query("UPDATE assessment.models SET state='RETIRED' WHERE state='ACTIVE' RETURNING *")).rows;for(const x of old)await this.g.history(c,u,'SCORING_MODEL',x.id,'MODEL_RETIRED',x,{state:'RETIRED'});}
 const next=(await c.query("UPDATE assessment.models SET state=$2,activated_at=CASE WHEN $2='ACTIVE' THEN now() ELSE activated_at END WHERE id=$1 RETURNING *",[modelId,state])).rows[0];await this.g.history(c,u,'SCORING_MODEL',modelId,'MODEL_'+state,m,next);return next;
 },false);}
 private async leader(c:PoolClient,familyId:string,u:AuthUser){const f=(await c.query('SELECT * FROM family.families WHERE id=$1 FOR UPDATE',[id(familyId)])).rows[0];if(!f)throw new AppError(404,'NOT_FOUND','خانواده پیدا نشد.');if(this.g.isGuide(u)||!(await recheckContext(c,u)).some(r=>r.roleCode==='GROUP_LEADER'&&r.scopeType==='GROUP'&&r.scopeId===f.current_group_id))throw new AppError(403,'FORBIDDEN','این فرم فقط برای سرگروه مسئول قابل ویرایش است.');return f;}
 async workspace(familyId:string,u:AuthUser){const family=await this.review.family(id(familyId),u);const snapshots=(await this.pool.query('SELECT s.*,m.version AS model_version,m.definition,m.form_schema,(SELECT p.first_name||\' \'||p.last_name FROM identity.accounts a JOIN identity.people p ON p.id=a.person_id WHERE a.id=s.actor_id) AS actor_name FROM assessment.snapshots s JOIN assessment.models m ON m.id=s.model_id WHERE s.family_id=$1 AND COALESCE(m.definition->>\'engine\',\'\')<>\'comprehensive-v2\' ORDER BY revision DESC',[familyId])).rows;const model=(await this.pool.query("SELECT * FROM assessment.models WHERE state='ACTIVE'")).rows[0];const canEdit=false;const draft=canEdit?(await this.pool.query('SELECT d.*,m.definition,m.form_schema,m.version AS model_version FROM assessment.drafts d JOIN assessment.models m ON m.id=d.model_id WHERE d.family_id=$1 AND d.submitted_snapshot_id IS NULL',[familyId])).rows[0]:null;return {family:family.family,members:family.members,documents:family.documents,snapshots,model,canEdit,draft};}
 async evidence(familyId:string,value:unknown,u:AuthUser){const b=input(value),name=str(b.name,150),media=str(b.mediaType,80),encoded=str(b.content,350000);if(!['application/pdf','image/png','image/jpeg','text/plain'].includes(media)||/[\\/]/.test(name)||!/^[A-Za-z0-9+/]*={0,2}$/.test(encoded))throw new AppError(400,'DOCUMENT','فایل معتبر نیست.');const content=Buffer.from(encoded,'base64');if(!content.length||content.length>256*1024)throw new AppError(400,'DOCUMENT','حداکثر اندازه مدرک ۲۵۶ کیلوبایت است.');return this.g.tx(u,async c=>{await this.leader(c,familyId,u);const row=(await c.query('INSERT INTO family.documents(family_id,name,media_type,content) VALUES($1,$2,$3,$4) RETURNING id,name,media_type',[familyId,name,media,content])).rows[0];await this.g.history(c,u,'FAMILY',familyId,'EVIDENCE_ATTACHED',null,{name,document_id:row.id});return row;},false);}
 private validatePayload(value:unknown){const b=input(value);for(const key of Object.keys(b))if(!['answers','urgency','evidence'].includes(key))throw new AppError(400,'MANUAL_SCORE','فقط پاسخ، شواهد و فوریت قابل ثبت‌اند؛ امتیاز توسط سامانه محاسبه می‌شود.');const answers=input(b.answers);for(const domain of Object.values(answers)){const a=input(domain);if(Object.keys(a).some(k=>!['applicable','summaries','facts','evidence','critical','members','sections','notes'].includes(k)))throw new AppError(400,'MANUAL_SCORE','عدد امتیاز قابل ورود نیست.');}return b;}
 async saveDraft(familyId:string,value:unknown,u:AuthUser){await assertLegacyWritable(this.pool,familyId);const b=input(value),payload=this.validatePayload(b.payload);return this.g.tx(u,async c=>{await this.leader(c,familyId,u);const old=(await c.query('SELECT * FROM assessment.drafts WHERE family_id=$1 AND submitted_snapshot_id IS NULL FOR UPDATE',[familyId])).rows[0];let saved;if(old){if(b.version!==old.version)throw new AppError(409,'STALE','پیش‌نویس تغییر کرده است؛ صفحه را تازه کنید.');saved=(await c.query('UPDATE assessment.drafts SET payload=$2,version=version+1,updated_at=now() WHERE id=$1 RETURNING *',[old.id,JSON.stringify(payload)])).rows[0];}else{const model=(await c.query("SELECT id FROM assessment.models WHERE state='ACTIVE'")).rows[0];if(!model)throw new AppError(422,'MODEL','مدل فعال موجود نیست.');saved=(await c.query('INSERT INTO assessment.drafts(family_id,model_id,created_by,payload) VALUES($1,$2,$3,$4) RETURNING *',[familyId,model.id,u.accountId,JSON.stringify(payload)])).rows[0];}await this.g.history(c,u,'FAMILY',familyId,old?'ASSESSMENT_DRAFT_UPDATED':'ASSESSMENT_CREATED',null,{draft_id:saved.id,version:saved.version});return saved;},false);}
 async submit(familyId:string,value:unknown,u:AuthUser){await assertLegacyWritable(this.pool,familyId);const b=input(value);let payload=this.validatePayload(b.payload??Object.fromEntries(Object.entries(b).filter(([k])=>!['draftId','version'].includes(k))));let answers=input(payload.answers) as Record<string,DomainInput>,urgency=str(payload.urgency);if(!['IMMEDIATE','NECESSARY','IMPORTANT','NON_URGENT'].includes(urgency))throw new AppError(400,'INVALID','فوریت معتبر نیست.');if(payload.evidence!==undefined&&!Array.isArray(payload.evidence))throw new AppError(400,'INVALID','فهرست مدارک معتبر نیست.');
 return this.g.tx(u,async c=>{
 const f=(await c.query('SELECT * FROM family.families WHERE id=$1 FOR UPDATE',[id(familyId)])).rows[0];if(!f)throw new AppError(404,'NOT_FOUND','خانواده پیدا نشد.');
 if(this.g.isGuide(u)||!(await recheckContext(c,u)).some(r=>r.roleCode==='GROUP_LEADER'&&r.scopeType==='GROUP'&&r.scopeId===f.current_group_id))throw new AppError(403,'FORBIDDEN','ثبت ارزیابی در اختیار سرگروه مسئول است.');
 const draft=b.draftId?(await c.query('SELECT * FROM assessment.drafts WHERE id=$1 AND family_id=$2 AND submitted_snapshot_id IS NULL FOR UPDATE',[id(b.draftId),familyId])).rows[0]:null;
 if(b.draftId&&(!draft||draft.version!==b.version))throw new AppError(409,'STALE','پیش‌نویس تغییر کرده یا ثبت شده است.');if(draft){payload=this.validatePayload(draft.payload);answers=input(payload.answers) as Record<string,DomainInput>;urgency=str(payload.urgency);}
 const m=draft?(await c.query('SELECT * FROM assessment.models WHERE id=$1',[draft.model_id])).rows[0]:(await c.query("SELECT * FROM assessment.models WHERE state='ACTIVE'")).rows[0];if(!m)throw new AppError(422,'MODEL_REQUIRED','مدل امتیازدهی مصوب و فعال هنوز آماده نیست.');
 const members=(await c.query('SELECT p.*,fm.relationship_code FROM family.family_memberships fm JOIN identity.people p ON p.id=fm.person_id WHERE fm.family_id=$1 AND fm.valid_to IS NULL ORDER BY p.id',[familyId])).rows;
 let result;try{result=evaluate(m.definition as Model,answers,members.map(p=>p.id));}catch(e){throw new AppError(400,'ASSESSMENT_INPUT',(e as Error).message);}
 const revision=(await c.query('SELECT COALESCE(max(revision),0)+1 n FROM assessment.snapshots WHERE family_id=$1',[familyId])).rows[0].n;
 const selectedEvidence=Array.isArray(payload.evidence)?payload.evidence:[];if(selectedEvidence.some(x=>typeof x!=='string'))throw new AppError(400,'EVIDENCE','فهرست مدارک معتبر نیست.');const evidence=(await c.query('SELECT id,name,media_type FROM family.documents WHERE family_id=$1 AND id=ANY($2::uuid[])',[familyId,selectedEvidence.map(x=>id(x))])).rows;if(evidence.length!==new Set(selectedEvidence).size)throw new AppError(400,'EVIDENCE','مدرک باید متعلق به همین خانواده باشد.');
 const snapshot=(await c.query('INSERT INTO assessment.snapshots(family_id,model_id,revision,actor_id,answers,members,evidence,result,state,score,level,urgency) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *',[familyId,m.id,revision,u.accountId,JSON.stringify(answers),JSON.stringify(members),JSON.stringify(evidence),JSON.stringify(result),result.state,result.score,result.level,urgency])).rows[0];
 if(draft)await c.query('UPDATE assessment.drafts SET submitted_snapshot_id=$2 WHERE id=$1',[draft.id,snapshot.id]);
 await this.g.history(c,u,'FAMILY',familyId,'ASSESSMENT_SUBMITTED',null,{revision,score:result.score,level:result.level,state:result.state,model_version:m.version});
 if(revision>1)await this.g.history(c,u,'FAMILY',familyId,'ASSESSMENT_SUPERSEDED',null,{previous_revision:revision-1,revision});await this.g.history(c,u,'FAMILY',familyId,'SCORE_COMPUTED',null,{revision,score:result.score,level:result.level,state:result.state});
 await this.syncAlerts(c,familyId,f.current_group_id,u,result.criticalFlags,m.definition.criticalRules.filter((r:any)=>typeof answers[r.domain]?.critical?.[r.code]==='boolean').map((r:any)=>r.code));return snapshot;
 },false);}
 async syncAlerts(c:PoolClient,familyId:string,groupId:string,u:AuthUser,flags:{code:string;label:string;severity:string;memberId?:string}[],evaluatedCodes:string[]){
 const owner=(await c.query(`SELECT r.account_id FROM identity.role_assignments r WHERE r.scope_id=$1 AND r.role_code='GROUP_LEADER' AND ${current} LIMIT 1`,[groupId])).rows[0]?.account_id;if(!owner&&flags.length)throw new AppError(409,'OWNER_REQUIRED','برای هشدار عملیاتی باید سرگروه مسئول مشخص باشد.');
 const detected=new Set(flags.map(x=>x.code+':'+(x.memberId??'')));
 for(const flag of flags){const old=(await c.query('SELECT * FROM oversight.alerts WHERE family_id=$1 AND member_id IS NOT DISTINCT FROM $2::uuid AND rule_code=$3 FOR UPDATE',[familyId,flag.memberId??null,flag.code])).rows[0];let alert;
 if(old){alert=(await c.query("UPDATE oversight.alerts SET trigger_detected=true,last_detected_at=now(),updated_at=now(),owner_id=$2,severity=$3,state=CASE WHEN state='RESOLVED' THEN 'OPEN' ELSE state END,resolved_at=NULL,resolved_by=NULL,action_taken=NULL,result=NULL WHERE id=$1 RETURNING *",[old.id,owner,flag.severity])).rows[0];}
 else alert=(await c.query('INSERT INTO oversight.alerts(family_id,member_id,rule_code,subject,severity,owner_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[familyId,flag.memberId??null,flag.code,flag.label,flag.severity,owner])).rows[0];
 await this.g.history(c,u,'FAMILY',familyId,old?'ALERT_TRIGGER_UPDATED':'ALERT_TRIGGERED',old,alert);
 if(!old||!old.trigger_detected||old.state==='RESOLVED'){await this.review.linkedNotify(c,[owner,...await this.g.guides(c)],flag.label,'ALERT','FAMILY',familyId);}
 }
 const existing=(await c.query('SELECT * FROM oversight.alerts WHERE family_id=$1 AND rule_code=ANY($2::text[]) AND trigger_detected FOR UPDATE',[familyId,evaluatedCodes])).rows;
 for(const old of existing)if(!detected.has(old.rule_code+':'+(old.member_id??''))){await c.query('UPDATE oversight.alerts SET trigger_detected=false,updated_at=now() WHERE id=$1',[old.id]);await this.g.history(c,u,'FAMILY',familyId,'TRIGGER_NO_LONGER_DETECTED',old,{...old,trigger_detected:false});}
 }
 async alerts(q:Record<string,string>,u:AuthUser){const rows=(await this.pool.query(`SELECT a.*,f.current_group_id AS family_group_id,f.family_code,COALESCE(NULLIF(g.name,''),'گروه '||g.group_number) AS group_name,p.first_name||' '||p.last_name AS owner_name FROM oversight.alerts a LEFT JOIN family.families f ON f.id=a.family_id LEFT JOIN organization.groups g ON g.id=COALESCE(a.group_id,f.current_group_id) LEFT JOIN identity.accounts ac ON ac.id=a.owner_id LEFT JOIN identity.people p ON p.id=ac.person_id ORDER BY a.created_at DESC`)).rows;
 const guide=this.g.isGuide(u),executive=u.roles.some(r=>r.roleCode==='EXECUTIVE_MANAGER'&&r.scopeType==='ORGANIZATION');let filtered=rows.filter(a=>guide||executive||a.owner_id===u.accountId||u.roles.some(r=>r.scopeType==='GROUP'&&r.scopeId===(a.group_id??a.family_group_id)));
 for(const [k,col] of [['severity','severity'],['state','state'],['family','family_id'],['person','person_id']])if(q[k])filtered=filtered.filter(a=>a[col]===q[k]);if(q.group)filtered=filtered.filter(a=>a.group_id===q.group||a.family_group_id===q.group);if(q.escalated==='true')filtered=filtered.filter(a=>a.escalated);if(q.open==='true')filtered=filtered.filter(a=>a.state!=='RESOLVED');
 for(const [k,sign] of [['from',1],['to',-1]] as const)if(q[k]){const timestamp=Date.parse(q[k]+(k==='to'?'T23:59:59.999Z':'T00:00:00Z'));if(!Number.isFinite(timestamp))throw new AppError(400,'DATE','تاریخ معتبر نیست.');filtered=filtered.filter(a=>sign===1?new Date(a.created_at).getTime()>=timestamp:new Date(a.created_at).getTime()<=timestamp);}
 return {alerts:filtered.map(a=>({...a,canResolve:!guide&&a.owner_id===u.accountId,canProgress:!guide&&a.owner_id===u.accountId}))};}
 async progress(alertId:string,value:unknown,u:AuthUser){const b=input(value),state=str(b.state);return this.g.tx(u,async c=>{
 const a=(await c.query('SELECT * FROM oversight.alerts WHERE id=$1 FOR UPDATE',[id(alertId)])).rows[0];if(!a)throw new AppError(404,'NOT_FOUND','هشدار پیدا نشد.');
 if(this.g.isGuide(u)||a.owner_id!==u.accountId)throw new AppError(403,'OWNER','رسیدگی فقط در اختیار مسئول هشدار است.');
 if(a.family_id){const f=(await c.query('SELECT current_group_id FROM family.families WHERE id=$1',[a.family_id])).rows[0];if(!(await c.query(`SELECT 1 FROM identity.role_assignments r WHERE r.account_id=$1 AND r.scope_id=$2 AND r.role_code='GROUP_LEADER' AND ${current}`,[u.accountId,f.current_group_id])).rowCount)throw new AppError(403,'SCOPE','مسئولیت جاری این پرونده را ندارید.');}
 const next:Record<string,string[]>={OPEN:['ACKNOWLEDGED'],ACKNOWLEDGED:['IN_PROGRESS'],IN_PROGRESS:['RESOLVED']};if(!next[a.state]?.includes(state))throw new AppError(409,'STATE','ترتیب رسیدگی معتبر نیست.');
 const action=state==='RESOLVED'?str(b.action,4000):null,result=state==='RESOLVED'?str(b.result,4000):null;
 if(state==='RESOLVED'&&b.actionCompleted!==true)throw new AppError(400,'RESULT','انجام اقدام باید تأیید شود.');
 if(b.evidence!==undefined&&!Array.isArray(b.evidence))throw new AppError(400,'EVIDENCE','مدارک معتبر نیستند.');
 const updated=(await c.query("UPDATE oversight.alerts SET state=$2,updated_at=now(),action_taken=$3,result=$4,evidence=$5,resolved_at=CASE WHEN $2='RESOLVED' THEN now() END,resolved_by=CASE WHEN $2='RESOLVED' THEN $6::uuid END WHERE id=$1 RETURNING *",[alertId,state,action,result,JSON.stringify(b.evidence??[]),u.accountId])).rows[0];
 await this.g.history(c,u,a.family_id?'FAMILY':'ALERT',a.family_id??a.id,'ALERT_'+state,a,updated);return updated;
 },false);}
}
