export type FormField={key:string;label:string;type:'text'|'number'|'choice'|'multiple'|'boolean'|'date';options?:string[]};
export type FormSection={key:string;title:string;repeat?:'MEMBERS'|'ROWS';fields:FormField[];screen?:'HEALTH'|'VULNERABILITY'|'EDUCATION'};
const field=(key:string,label:string,type:FormField['type']='text',options?:string[]):FormField=>({key,label,type,...(options?{options}:{})});
const fields=(names:string[])=>names.map(label=>field(label,label));
export const formSchema:Record<string,FormSection[]>={
 livelihood:[
 {key:'income',title:'درآمد و منابع خانواده',repeat:'ROWS',fields:[field('source','منبع درآمد','choice',['حقوق ثابت','درآمد روزمزد','درآمد آزاد','مستمری / بازنشستگی','یارانه / کمک مستمر','حمایت خانوادگی','سایر']),field('amount','مبلغ تقریبی','number'),field('period','دوره دریافت','choice',['ماهانه','هفتگی','روزانه','نامنظم','فصلی','سایر']),field('continuity','استمرار منبع','choice',['پایدار','نسبتاً پایدار','ناپایدار','موقت']),field('adequate','کفایت برای نیازهای پایه','choice',['کافی','ناکافی','نامشخص']),field('description','توضیح درآمد و شرایط خاص')]},
 {key:'employment',title:'اشتغال و توان اقتصادی اعضای خانواده',repeat:'MEMBERS',fields:[field('status','وضعیت اشتغال','choice',['شاغل','بیکار','خانه‌دار','دانش‌آموز / دانشجو','بازنشسته','فاقد توان کار','دارای توان کار ولی فاقد شغل','سایر']),...fields(['نوع اشتغال','ثبات شغل','توضیح']),field('dependent','وابستگی اقتصادی','boolean'),field('canWork','توان کار','boolean'),field('barrier','مانع اشتغال')]},
 {key:'financialPressure',title:'فشار مالی و تعهدات',fields:[field('expenses','هزینه‌های ضروری سنگین','multiple',['درمان','اجاره','تحصیل','مراقبت','بدهی','اقساط','هزینه خوراک','سایر']),field('hasDebt','وجود بدهی','boolean'),field('debtType','نوع بدهی'),field('debtAmount','مبلغ تقریبی بدهی','number'),field('instalments','اقساط ماهانه','number'),field('arrears','معوقات','number'),...fields(['اثر بدهی بر تأمین نیازهای پایه','اثر هزینه‌های ضروری بر بودجه خانواده','توضیح تکمیلی'])]}
 ],
 health:[{key:'healthMembers',title:'غربالگری و وضعیت سلامت همه اعضا',repeat:'MEMBERS',screen:'HEALTH',fields:[...fields(['نوع مشکل سلامت','نوع بیماری یا محدودیت']),field('duration','وضعیت بیماری','choice',['حاد','مزمن']),field('started','شروع تقریبی'),...fields(['اثر بر فعالیت روزانه','اثر بر کار','اثر بر تحصیل']),field('treatment','نیاز به درمان','boolean'),field('medicine','نیاز به دارو','boolean'),field('available','درمان یا دارو در دسترس است','boolean'),field('supply','میزان تأمین درمان'),field('cost','هزینه تقریبی درمان و دارو','number'),field('insurance','بیمه دارد','boolean'),...fields(['نوع بیمه','میزان پوشش','نیاز به مراقبت توسط عضو دیگر','میزان وابستگی مراقبتی','فوریت وضعیت','توضیحات و مدارک'])]}],
 housing:[
 {key:'residence',title:'نوع و وضعیت سکونت',fields:[field('tenure','نوع سکونت','choice',['ملکی','اجاره‌ای','رهن / ودیعه','با بستگان','رایگان','موقت','فاقد محل سکونت پایدار','سایر']),...fields(['مدت سکونت در محل فعلی','احتمال ادامه سکونت','نگرانی درباره جابه‌جایی','خطر تخلیه','توضیح'])]},
 {key:'quality',title:'کیفیت و امکانات محل',fields:[...fields(['وضعیت کلی بنا','ایمنی ساختمان','آب','برق','گرمایش','سرویس بهداشتی','فضای آشپزی']),field('memberCount','تعداد اعضا','number'),field('rooms','اتاق قابل استفاده','number'),field('crowding','تراکم یا ازدحام'),field('suitability','تناسب محل برای','multiple',['سالمند','بیمار','فرد دارای محدودیت جسمی','فرد وابسته']),field('description','توضیح شرایط نامناسب و مدارک')]},
 {key:'housingCosts',title:'فشار مالی مسکن',fields:[field('rent','مبلغ اجاره','number'),field('deposit','مبلغ ودیعه','number'),field('debt','قسط یا بدهی مسکن','number'),field('rentArrears','معوق اجاره','number'),field('debtArrears','معوق اقساط','number'),field('support','کمک مسکن دریافت می‌شود','boolean'),field('impact','اثر هزینه مسکن بر سایر نیازهای ضروری'),field('description','توضیح')]}
 ],
 vulnerability:[
 {key:'specialMembers',title:'غربالگری وضعیت ویژه اعضا',repeat:'MEMBERS',screen:'VULNERABILITY',fields:[field('types','نوع وضعیت ویژه','multiple',['سالمندی','معلولیت','وابستگی شدید','سرپرست تنها','کودک نیازمند مراقبت','فرد نیازمند مراقبت دائمی','سایر']),...fields(['میزان وابستگی','نوع کمک مورد نیاز','اثر بر کار اعضا','اثر بر تحصیل','اثر بر اداره خانواده']),field('caregiver','وجود مراقب','boolean'),field('description','توضیحات و شواهد؛ اثر بر ظرفیت خانواده، نه تکرار اثر درمانی')]},
 {key:'network',title:'شبکه حمایت خانوادگی و اجتماعی',fields:[field('available','شبکه قابل اتکا بیرون از خانواده هسته‌ای','boolean'),field('sources','منبع حمایت','multiple',['بستگان','دوستان','همسایه','نهاد','خیر','سایر']),...fields(['نوع حمایت','استمرار حمایت','قابلیت اتکا در بحران','توضیح'])]},
 {key:'crisis',title:'بحران‌ها و شرایط تشدیدکننده',fields:[field('kind','نوع بحران'),field('started','تاریخ شروع','date'),field('active','بحران همچنان فعال است','boolean'),...fields(['شدت فعلی','اثر بر خانواده']),field('multiple','چند بحران هم‌زمان','boolean'),field('description','توضیح و مدرک')]}
 ],
 education:[{key:'educationMembers',title:'اعضای مشمول، وضعیت و موانع تحصیل',repeat:'MEMBERS',screen:'EDUCATION',fields:[field('grade','پایه یا مقطع'),field('school','مدرسه یا دانشگاه'),field('studyStatus','وضعیت تحصیل','choice',['در حال تحصیل','وقفه','ترک تحصیل','در معرض ترک تحصیل','فارغ‌التحصیل','زیر سن تحصیل','نامشخص']),field('attendance','حضور','choice',['منظم','غیبت محدود','غیبت مکرر','عملاً خارج از تحصیل']),...fields(['افت تحصیلی','تغییرات اخیر','توضیح']),field('barriers','موانع و نیازهای آموزشی','multiple',['لوازم‌التحریر','کیف / کفش / پوشاک','شهریه / هزینه','رفت‌وآمد','کتاب / منابع','ابزار دیجیتال','اینترنت','کلاس تقویتی','دسترسی به مدرسه','مشکل جسمی','مشکل خانوادگی','نیاز به کار','سایر']),field('barrierDetails','شدت هر مانع و توضیح'),field('futureRisk','خطر آینده ترک تحصیل','choice',['خطر وجود ندارد','خطر محدود','خطر محسوس','خطر جدی و نزدیک','ترک تحصیل فعلی']),...fields(['علت خطر','قابل پیشگیری بودن','نوع حمایت پیشنهادی','فوریت مداخله','توضیحات و شواهد'])]}]
};
