import {Inject,Injectable} from '@nestjs/common';
import {Pool} from 'pg';
import {PG_POOL} from '../database/database.constants';
import {GuidanceService,input,str,id} from '../guidance/guidance.service';
import {ReviewService} from '../review/review.service';
import {AssessmentService} from './assessment.service';
import type {AuthUser} from '../auth/auth.types';
import {AppError} from '../common/app-error';
import {reportHtml,workbook} from '../review/report-export';
const number=(v:any)=>Number(v??0);
const fa:Record<string,string>={ACTIVE:'فعال',INACTIVE:'غیرفعال',DISSOLVED:'غیرفعال',IMMEDIATE:'فوری',NECESSARY:'ضروری',IMPORTANT:'مهم',NON_URGENT:'غیرفوری',CRITICAL:'فوری',HIGH:'ضروری',NORMAL:'غیرفوری',PROVISIONAL:'نیازمند تکمیل اطلاعات',FINAL:'نهایی',COMPLETED:'انجام‌شده',PENDING:'در انتظار',DRAFT:'پیش‌نویس',STIPEND:'مقرری',INVOICE:'واقعی / فاکتور',ESTIMATED:'برآوردی'};
const text=(v:any)=>fa[String(v)]??(/[A-Za-z_]{3,}/.test(String(v))?'ثبت نشده':String(v??'ثبت نشده'));
@Injectable()
export class OversightService {
 constructor(@Inject(PG_POOL) private pool:Pool,private g:GuidanceService,private review:ReviewService,private assessment:AssessmentService){}
 async families(q:Record<string,string>={}){
 let rows=(await this.pool.query(`SELECT f.*,s.id AS assessment_id,s.revision,s.state AS assessment_state,s.result AS assessment_result,s.created_at AS assessed_at,
 CASE WHEN s.id IS NULL THEN f.score ELSE s.score END AS current_score,CASE WHEN s.id IS NULL THEN f.need_level ELSE s.level END AS current_level,COALESCE(s.urgency,CASE f.urgency WHEN 'CRITICAL' THEN 'IMMEDIATE' WHEN 'HIGH' THEN 'NECESSARY' ELSE 'NON_URGENT' END) AS current_urgency,
 (SELECT count(*)::int FROM oversight.alerts a WHERE a.family_id=f.family_id AND a.state<>'RESOLVED') AS alert_count,
 (SELECT count(*)::int FROM oversight.alerts a WHERE a.family_id=f.family_id AND a.state<>'RESOLVED' AND a.severity IN ('IMPORTANT','VERY_IMPORTANT','CRITICAL')) AS important_alerts,
 (SELECT count(*)::int FROM oversight.alerts a WHERE a.family_id=f.family_id AND a.state<>'RESOLVED' AND a.severity='CRITICAL') AS critical_alerts
 FROM monitoring.family_facts f LEFT JOIN LATERAL(SELECT * FROM assessment.snapshots a WHERE a.family_id=f.family_id ORDER BY revision DESC LIMIT 1) s ON true ORDER BY f.family_code`)).rows;
 if(q.group)rows=rows.filter(f=>f.group_id===q.group);if(q.level)rows=rows.filter(f=>f.current_level===q.level);if(q.urgency)rows=rows.filter(f=>f.current_urgency===q.urgency);if(q.q)rows=rows.filter(f=>(f.head_name+' '+f.family_code).includes(q.q));
 return rows.map(f=>({...f,domains:f.assessment_result?Object.fromEntries(Object.entries(f.assessment_result.domains).map(([key,d]:any)=>[key,{title:d.label,score:d.score,answers:(d.breakdown??[]).map((b:any)=>({question:b.label,response:b.selection,score:b.points,max_score:b.max})),research_data:'نتیجه نسخه ارزیابی '+f.revision}])):f.domains,score:f.current_score,need_level:f.current_level,urgency:f.current_urgency,open_alerts:f.alert_count,case_condition:f.assessment_state==='PROVISIONAL'||!f.assessment_id?'INCOMPLETE':f.research_status==='OVERDUE'?'OVERDUE':f.review_required?'REVIEW_REQUIRED':'CURRENT'}));
 }
 async familyReadContext(familyId:string,u:AuthUser){
 const data=await this.family(familyId,u);
 const contexts=(await this.pool.query(`SELECT c.*,i.subject AS council_subject FROM family.investigation_context c JOIN family.research_records r ON r.id=c.research_id LEFT JOIN guidance.items i ON i.id=c.council_item_id AND i.kind='COUNCIL' AND i.archive_final WHERE r.family_id=$1`,[familyId])).rows;
 const visits=(await this.pool.query(`SELECT v.* FROM family.investigation_visits v JOIN family.research_records r ON r.id=v.research_id WHERE r.family_id=$1 ORDER BY visited_at`,[familyId])).rows;
 const notes=(await this.pool.query(`SELECT n.*,p.first_name||' '||p.last_name AS actor_name FROM family.case_notes n JOIN identity.accounts a ON a.id=n.actor_id JOIN identity.people p ON p.id=a.person_id WHERE n.family_id=$1 ORDER BY n.recorded_at DESC`,[familyId])).rows;
 const documents=(await this.pool.query(`SELECT d.id,d.name,d.media_type,c.person_id,c.research_id,c.support_id,c.category,c.valid_until,c.recorded_at,p.first_name||' '||p.last_name AS actor_name FROM family.documents d LEFT JOIN family.document_context c ON c.document_id=d.id LEFT JOIN identity.accounts a ON a.id=c.actor_id LEFT JOIN identity.people p ON p.id=a.person_id WHERE d.family_id=$1 AND d.id=ANY($2::uuid[])`,[familyId,data.documents.map((d:any)=>d.id)])).rows;
 const supportContexts=(await this.pool.query('SELECT c.* FROM family.support_context c JOIN monitoring.support_records s ON s.id=c.support_id WHERE s.family_id=$1',[familyId])).rows;
 const continuous=(await this.pool.query('SELECT * FROM monitoring.stipend_facts WHERE family_id=$1',[familyId])).rows;
 return {...data,family:{...data.family,assessment_status:data.snapshots[0]?.state==='PROVISIONAL'?'INCOMPLETE':!data.snapshots.some(s=>s.state==='FINAL')?'NO_VALID':data.family?.review_required?'REVIEW_REQUIRED':'CURRENT'},documents,notes,research:data.research.map((r:any)=>({...r,context:contexts.find(c=>c.research_id===r.id),visits:visits.filter(v=>v.research_id===r.id)})),supports:[...data.supports.map((r:any)=>({...r,...supportContexts.find(c=>c.support_id===r.id),support_kind:'OCCASIONAL'})),...continuous.map(r=>({...r,category:'حمایت مستمر',support_kind:'CONTINUOUS',amount:r.monthly_amount,status:r.ends_on&&new Date(r.ends_on)<new Date()?'COMPLETED':'ACTIVE',occurred_at:r.starts_on}))]};
 }
 async monitoringFamilies(){
 const rows=await this.families();
 const snapshots=(await this.pool.query("SELECT DISTINCT ON (family_id) family_id,id,score,level,urgency,result,created_at FROM assessment.snapshots WHERE state='FINAL' ORDER BY family_id,revision DESC")).rows;
 const reminders=(await this.pool.query("SELECT family_id,count(*)::int AS count FROM oversight.reminders WHERE state='OPEN' AND due_at<now() GROUP BY family_id")).rows;
 return {families:rows.filter(f=>f.case_status==='ACTIVE').map(f=>{
 const valid=snapshots.find(s=>s.family_id===f.family_id);
 return {...f,score:valid?.score??null,need_level:valid?.level??null,assessed_at:valid?.created_at??null,
 domain_results:valid?.result?.domains??{},assessment_status:f.assessment_state==='PROVISIONAL'?'INCOMPLETE':!valid?'NO_VALID':f.review_required?'REVIEW_REQUIRED':'CURRENT',
 overdue_reminders:reminders.find(r=>r.family_id===f.family_id)?.count??0};
 })};
 }
 async dashboard(u:AuthUser){const families=await this.families(),active=families.filter(f=>f.case_status==='ACTIVE'),alerts=(await this.assessment.alerts({},u)).alerts.filter(a=>a.state!=='RESOLVED'),groups=(await this.groups({},u)).groups;
 return {families:{active:active.length,levels:Object.fromEntries(['A','B','C','D'].map(l=>[l,active.filter(f=>f.need_level===l).length])),immediate:active.filter(f=>f.urgency==='IMMEDIATE').length,incomplete:active.filter(f=>f.case_condition==='INCOMPLETE').length},alerts:{critical:alerts.filter(a=>a.severity==='CRITICAL').length,veryImportant:alerts.filter(a=>a.severity==='VERY_IMPORTANT').length,escalated:alerts.filter(a=>a.escalated).length,open:alerts.length},groups:{active:groups.filter(g=>g.status==='ACTIVE').length,critical:groups.filter(g=>g.critical_families>0).length,overdue:groups.filter(g=>g.overdue_count>0).length}};
 }
 async groups(q:Record<string,string>,u:AuthUser){const base=(await this.review.groups({},u)).groups,families=await this.families(),alerts=(await this.assessment.alerts({},u)).alerts;
 const reminders=(await this.pool.query("SELECT r.*,f.current_group_id FROM oversight.reminders r LEFT JOIN family.families f ON f.id=r.family_id WHERE r.state='OPEN' AND r.due_at<now()")).rows;
 let groups=base.map(g=>{const fs=families.filter(f=>f.group_id===g.group_id),as=alerts.filter(a=>a.state!=='RESOLVED'&&(a.group_id===g.group_id||a.family_group_id===g.group_id)&&['IMPORTANT','VERY_IMPORTANT','CRITICAL'].includes(a.severity)),overdue=fs.filter(f=>f.research_status==='OVERDUE'||f.research_due_at&&new Date(f.research_due_at)<new Date()&&f.review_required),rs=reminders.filter(r=>r.group_id===g.group_id||r.current_group_id===g.group_id);return {...g,family_count:fs.length,levels:Object.fromEntries(['A','B','C','D'].map(l=>[l,fs.filter(f=>f.need_level===l).length])),critical_families:fs.filter(f=>f.critical_alerts>0).length,immediate:fs.filter(f=>f.urgency==='IMMEDIATE').length,overdue_count:overdue.length,attention_count:as.length+overdue.length+rs.length,attention:{alerts:as,overdue:overdue.map(f=>({id:f.family_id,name:f.head_name,code:f.family_code})),reminders:rs},ratio:g.helper_count?fs.length/g.helper_count:null};});
 if(q.group)groups=groups.filter(g=>g.group_id===q.group);if(q.state)groups=groups.filter(g=>g.status===q.state);if(q.leader)groups=groups.filter(g=>g.leader_person_id===q.leader);if(q.attention==='true')groups=groups.filter(g=>g.attention_count>0);return {groups};
 }
 async group(groupId:string,q:Record<string,string>,u:AuthUser){const old=await this.review.group(groupId,{},u),g=(await this.groups({},u)).groups.find(g=>g.group_id===groupId);return {...old,group:g,families:await this.families({...q,group:groupId}),alerts:(await this.assessment.alerts({group:groupId},u)).alerts.filter(a=>a.group_id===groupId)};}
 async family(familyId:string,u:AuthUser){const old=await this.review.family(familyId,u),snapshots=(await this.pool.query('SELECT s.*,m.version AS model_version,p.first_name||\' \'||p.last_name AS actor_name FROM assessment.snapshots s JOIN assessment.models m ON m.id=s.model_id JOIN identity.accounts a ON a.id=s.actor_id JOIN identity.people p ON p.id=a.person_id WHERE family_id=$1 ORDER BY revision DESC',[familyId])).rows;
 return {...old,family:(await this.families()).find(f=>f.family_id===familyId),snapshots,alerts:(await this.assessment.alerts({family:familyId},u)).alerts,history:await this.history('FAMILY',familyId)};}
 async history(type:string,entity:string){const rows=(await this.pool.query("SELECT h.*,CASE WHEN h.action LIKE 'HEALTH_%' THEN NULL ELSE h.previous_state END AS previous_state,CASE WHEN h.action LIKE 'HEALTH_%' THEN NULL ELSE h.new_state END AS new_state,CASE WHEN h.action LIKE 'HEALTH_%' THEN NULL ELSE h.reason END AS reason,p.first_name||' '||p.last_name AS actor_name FROM guidance.history h LEFT JOIN identity.accounts a ON a.id=h.actor_id LEFT JOIN identity.people p ON p.id=a.person_id WHERE h.entity_type=$1 AND h.entity_id=$2 ORDER BY occurred_at DESC",[type,entity])).rows;
 const groups=(await this.pool.query('SELECT id,group_number,name FROM organization.groups')).rows;for(const h of rows)if(h.action==='FAMILY_TRANSFERRED'){const source=h.previous_state?.current_group_id??h.new_state?.from_group_id,target=h.new_state?.current_group_id??h.new_state?.to_group_id;const a=groups.find(g=>g.id===source),b=groups.find(g=>g.id===target);h.description=`خانواده از گروه ${a?Number(a.group_number).toLocaleString('fa-IR'):'پیشین'} به گروه ${b?Number(b.group_number).toLocaleString('fa-IR'):'مقصد'} منتقل شد.`;}return rows;}
 async council(q:Record<string,string>){let where="i.kind='COUNCIL' AND i.archive_final",values:unknown[]=[];const add=(sql:string,v:unknown)=>{values.push(v);where+=' AND '+sql.replace(/(?<!@)@(?!@)/g,`$${values.length}`);};
 if(q.q)add("(to_tsvector('simple',i.subject||' '||i.body) @@ plainto_tsquery('simple',@) OR concat_ws(' ',i.subject,i.body,p.first_name,p.last_name,ep.first_name,ep.last_name,i.related_people::text) ILIKE '%'||@||'%')",str(q.q));
 // The same search parameter is intentionally reused in both predicates.

 if(q.category)add('i.category=@',str(q.category));if(q.state)add('i.execution_status=@',str(q.state));if(q.executor)add('i.executor_id=@',id(q.executor));
 for(const [key,op] of [['from','>='],['to','<=']])if(q[key]){if(!/^\d{4}-\d{2}-\d{2}$/.test(q[key])||!Number.isFinite(Date.parse(q[key])))throw new AppError(400,'DATE','تاریخ معتبر نیست.');add(`i.created_at::date${op}@::date`,q[key]);}
 return {items:(await this.pool.query(`SELECT i.id,i.archive_number,i.subject,i.body,i.created_at,i.category,i.related_people,i.execution_status,p.first_name||' '||p.last_name AS creator,ep.first_name||' '||ep.last_name AS executor FROM guidance.items i JOIN identity.accounts a ON a.id=i.created_by JOIN identity.people p ON p.id=a.person_id LEFT JOIN identity.accounts ea ON ea.id=i.executor_id LEFT JOIN identity.people ep ON ep.id=ea.person_id WHERE ${where} ORDER BY i.created_at ${q.sort==='oldest'?'ASC':'DESC'}`,values)).rows};}
 async councilDetail(itemId:string,u:AuthUser){const data=await this.review.councilDetail(itemId,u);if(!data.item.archive_final)throw new AppError(404,'NOT_FOUND','مصوبه نهایی پیدا نشد.');const executor=data.item.executor_id?(await this.pool.query("SELECT p.first_name||' '||p.last_name AS name FROM identity.accounts a JOIN identity.people p ON p.id=a.person_id WHERE a.id=$1",[data.item.executor_id])).rows[0]?.name:null;return {...data,executor,history:await this.history('ITEM',itemId)};}
 async report(section:string,q:Record<string,string>,u:AuthUser){const families=await this.families(q);let domainSummary:any[]=[],title='',question='',rows:any[]=[],columns:{key:string;label:string}[]=[],summary:Record<string,number>={},chart:any[]=[];
 const col=(key:string,label:string)=>({key,label});
 if(section==='families'){
 title='خانواده‌ها و نیازها';question='نیازها و موارد نیازمند توجه در کدام خانواده‌ها متمرکز است؟';const active=families.filter(f=>f.case_status==='ACTIVE');summary={'خانواده فعال':active.length,'سطح A':active.filter(f=>f.need_level==='A').length,'سطح B':active.filter(f=>f.need_level==='B').length,'فوریت فوری':active.filter(f=>f.urgency==='IMMEDIATE').length,'نیازمند بازبینی':active.filter(f=>f.review_required).length,'دارای هشدار مهم یا بحرانی':active.filter(f=>f.important_alerts>0).length};
 domainSummary=Object.entries({livelihood:'معیشت',health:'سلامت',housing:'مسکن',vulnerability:'آسیب‌پذیری',education:'آموزش'}).map(([key,label])=>({label,need:active.filter(f=>number(f.assessment_result?.domains?.[key]?.score)>0).length,maximumIndicator:active.filter(f=>f.assessment_result?.domains?.[key]?.breakdown?.some((b:any)=>b.points===b.max)).length}));
 chart=['A','B','C','D'].map(level=>({label:'سطح '+level,count:active.filter(f=>f.need_level===level).length,percent:active.length?100*active.filter(f=>f.need_level===level).length/active.length:0}));
 const assessments=(await this.pool.query("SELECT family_id,score,model_id,row_number() OVER(PARTITION BY family_id ORDER BY revision DESC) AS position FROM assessment.snapshots WHERE state='FINAL'")).rows;rows=families.map(f=>{const latest=assessments.find(a=>a.family_id===f.family_id&&number(a.position)===1),previous=assessments.find(a=>a.family_id===f.family_id&&number(a.position)===2);const change=!latest||!previous?'دو ارزیابی معتبر موجود نیست':latest.model_id!==previous.model_id?'مدل متفاوت؛ نیازمند بررسی':number(latest.score)<number(previous.score)?'کاهش امتیاز نیاز':number(latest.score)>number(previous.score)?'افزایش امتیاز نیاز':'بدون تغییر امتیاز';return {change,link:'/guide/families/'+f.family_id,family:f.head_name??f.family_code,group:f.group_name,level:f.need_level??'نامشخص',urgency:text(f.urgency),domains:Object.values(f.assessment_result?.domains??f.domains??{}).filter((d:any)=>number(d.score)>0).map((d:any)=>d.label??d.title).join('، ')||'نیاز ثبت‌شده ندارد',condition:({INCOMPLETE:'داده ناقص',OVERDUE:'بازبینی معوق',REVIEW_REQUIRED:'نیازمند بازبینی',CURRENT:'به‌روز'} as any)[f.case_condition],alerts:f.important_alerts};});columns=[col('family','خانواده'),col('group','گروه'),col('level','سطح نیاز'),col('urgency','فوریت'),col('domains','حوزه‌های نیاز'),col('condition','وضعیت پرونده'),col('alerts','هشدار مهم'),col('change','دو ارزیابی معتبر آخر')];
 }else if(section==='supports'){
 title='حمایت‌های موردی';question='حمایت‌ها به چه خانواده‌هایی و با چه ارزشی رسیده‌اند؟';const selected=new Set(families.map(f=>f.family_id));let source=(await this.pool.query('SELECT s.*,r.value_basis,f.head_name,f.group_name,f.need_level FROM monitoring.support_facts s JOIN monitoring.support_records r ON r.id=s.id JOIN monitoring.family_facts f ON f.family_id=s.family_id WHERE s.status=\'COMPLETED\'')).rows.filter(s=>selected.has(s.family_id));source=this.filterDates(source,q);if(q.type)source=source.filter(s=>s.support_type===q.type);const counts=new Map<string,number>();for(const s of source)counts.set(s.family_id,(counts.get(s.family_id)??0)+1);const total=source.reduce((n,s)=>n+number(s.amount),0);summary={'خانواده برخوردار':counts.size,'تعداد حمایت':source.length,'مجموع ارزش':total,'میانگین ارزش':source.length?total/source.length:0,'بیش از یک حمایت':Array.from(counts.values()).filter(n=>n>1).length};rows=source.map(s=>({link:'/guide/families/'+s.family_id,family:s.head_name,group:s.group_name,type:s.support_type,value:number(s.amount),basis:text(s.value_basis),date:new Date(s.created_at).toLocaleDateString('fa-IR'),level:s.need_level??'نامشخص',source:s.source??'ثبت نشده'}));columns=[col('family','خانواده'),col('group','گروه'),col('type','نوع حمایت'),col('value','ارزش ریالی'),col('date','تاریخ'),col('level','سطح نیاز'),col('source','منبع'),col('basis','مبنای ارزش')];
 }else if(section==='continuous'){
 title='حمایت‌های مستمر';question='تعهد مستمر کانون و وضعیت پرداخت آن چگونه است؟';const ids=new Set(families.map(f=>f.family_id));const source=(await this.pool.query('SELECT * FROM monitoring.stipend_facts')).rows.filter(s=>ids.has(s.family_id));const now=new Date();const active=source.filter(s=>new Date(s.starts_on)<=now&&(!s.ends_on||new Date(s.ends_on)>=now));const payments=source.flatMap(s=>(s.payments??[]).map((p:any)=>({...p,created_at:p.paid_at??p.due_on})));const paid=this.filterDates(payments,q).filter(p=>p.paid_at);summary={'خانواده دارای حمایت فعال':new Set(active.map(s=>s.family_id)).size,'تعهد ماهانه':active.reduce((n,s)=>n+number(s.monthly_amount),0),'پرداخت در بازه':paid.reduce((n,s)=>n+number(s.amount),0),'معوقات':source.reduce((n,s)=>n+number(s.overdue_amount),0),'پرونده دارای معوق':source.filter(s=>number(s.overdue_amount)>0).length};chart=[{label:'تعهد ماهانه',count:summary['تعهد ماهانه']},{label:'پرداخت در بازه',count:summary['پرداخت در بازه']}];rows=source.map(s=>({link:'/guide/families/'+s.family_id,family:s.head_name,group:s.group_name,monthly:number(s.monthly_amount),paid:number(s.paid_total),arrears:number(s.overdue_amount)}));columns=[col('family','خانواده'),col('group','گروه'),col('monthly','تعهد ماهانه'),col('paid','مجموع پرداخت'),col('arrears','معوق')];
 }else if(section==='groups'){
 title='گروه‌ها و ظرفیت اجرایی';question='مسئولیت‌ها کجا متمرکزند و چه گروه‌هایی نیاز به تقویت دارند؟';const groups=(await this.groups(q,u)).groups;summary={'گروه فعال':groups.filter(g=>g.status==='ACTIVE').length,'خانواده تحت پوشش':groups.reduce((n,g)=>n+g.family_count,0),'دارای بازبینی معوق':groups.filter(g=>g.overdue_count>0).length,'بدون همیار':groups.filter(g=>g.status==='ACTIVE'&&g.helper_count===0&&g.family_count>0).length};rows=groups.map(g=>({link:'/guide/groups/'+g.group_id,group:g.group_name,leader:g.leader_name??'مسئول جاری ندارد',helpers:g.helper_count,families:g.family_count,highNeed:g.levels.A+g.levels.B,immediate:g.immediate,overdue:g.overdue_count,capacity:g.helper_count===0&&g.family_count>0?'نیازمند تقویت':g.attention_count>0?'نیازمند توجه':'مورد نیازمند توجه ثبت نشده',reason:g.helper_count===0&&g.family_count>0?'خانواده تحت پوشش بدون همیار':g.attention_count>0?'هشدار یا پیگیری معوق ثبت شده':'نسبت خانواده به همیار: '+(g.ratio===null?'قابل محاسبه نیست':g.ratio.toLocaleString('fa-IR',{maximumFractionDigits:1}))}));columns=[col('group','گروه'),col('leader','سرگروه'),col('helpers','همیار'),col('families','خانواده'),col('highNeed','سطح A/B'),col('immediate','فوری'),col('overdue','بازبینی معوق'),col('capacity','ظرفیت'),col('reason','دلیل')];
 }else if(section==='plans'){
 title='طرح‌های جمعی';question='طرح‌های نهایی چه پوشش و دستاوردی داشته‌اند؟';let source=(await this.pool.query(`SELECT p.*,p.planned_on AS created_at,(SELECT count(*)::int FROM monitoring.distribution_recipients r WHERE r.plan_id=p.id AND r.status='FINAL') AS beneficiaries,(SELECT string_agg(DISTINCT f.group_name,'، ') FROM monitoring.distribution_recipients r JOIN monitoring.family_facts f ON f.family_id=r.family_id WHERE r.plan_id=p.id AND r.status='FINAL') AS coverage FROM monitoring.distribution_plans p WHERE p.status='FINAL' ORDER BY p.planned_on DESC`)).rows;source=this.filterDates(source,q);if(q.plan)source=source.filter(p=>p.id===q.plan);summary={'طرح نهایی':source.length,'خانواده بهره‌مند':source.reduce((n,p)=>n+p.beneficiaries,0),'ارزش کل':source.reduce((n,p)=>n+p.beneficiaries*number(p.unit_value),0)};rows=source.map(p=>({planKey:p.id,title:p.title,occasion:p.occasion??p.category,date:new Date(p.planned_on).toLocaleDateString('fa-IR'),families:p.beneficiaries,packages:p.beneficiaries,value:p.beneficiaries*number(p.unit_value),source:p.source??'ثبت نشده',coverage:p.coverage??'ثبت نشده',result:p.result_summary??'نتیجه تکمیلی ثبت نشده'}));columns=[col('title','عنوان طرح'),col('occasion','مناسبت / هدف'),col('date','تاریخ'),col('families','خانواده'),col('packages','بسته / خدمت'),col('value','ارزش کل'),col('source','منابع'),col('coverage','پوشش'),col('result','نتیجه')];
 }else throw new AppError(400,'REPORT','گزارش معتبر نیست.');
 return {section,title,question,summary,chart,domainSummary,columns,rows};
 }
 private filterDates(rows:any[],q:Record<string,string>){for(const key of ['from','to'])if(q[key]&&(!/^\d{4}-\d{2}-\d{2}$/.test(q[key])||!Number.isFinite(Date.parse(q[key]))))throw new AppError(400,'DATE','تاریخ معتبر نیست.');if(q.from)rows=rows.filter(r=>new Date(r.created_at)>=new Date(q.from));if(q.to)rows=rows.filter(r=>new Date(r.created_at)<=new Date(q.to+'T23:59:59.999Z'));return rows;}
 async export(value:unknown,u:AuthUser){const b=input(value),section=str(b.section),format=str(b.format);if(!['preview','xlsx'].includes(format))throw new AppError(400,'FORMAT','این قالب خروجی در این نسخه فعال نیست.');const filters=input(b.filters??{}) as Record<string,string>,data=await this.report(section,filters,u);let fields=data.columns;
 if(b.fields!==undefined){if(!Array.isArray(b.fields)||!b.fields.length||b.fields.some(x=>typeof x!=='string'||!fields.some(f=>f.key===x)))throw new AppError(400,'FIELDS','ستون انتخابی معتبر نیست.');fields=fields.filter(f=>(b.fields as string[]).includes(f.key));}
 const filterText=Object.entries(filters).filter(([,v])=>v).map(([k,v])=>k==='group'?'گروه انتخاب‌شده':k==='plan'?'طرح انتخاب‌شده':k==='from'||k==='to'?(k==='from'?'از ':'تا ')+new Date(v).toLocaleDateString('fa-IR'):k==='level'?'سطح '+v:k==='q'?'جستجو: '+v:'فیلتر تخصصی اعمال شده').join('، ')||'همه موارد';
 const html=reportHtml(data.title,fields,data.rows,filterText,fields.length>5);const rows=data.rows.map(r=>Object.fromEntries(fields.map(f=>[f.key,r[f.key]])));
 await this.g.tx(u,c=>this.g.history(c,u,'REPORT',crypto.randomUUID(),'MANAGEMENT_REPORT_EXPORTED',null,{section,format,fields:fields.map(f=>f.key),count:rows.length}));
 return {format,html,buffer:format==='xlsx'?workbook(data.title+' · '+new Date().toLocaleDateString('fa-IR')+' · '+filterText,fields,rows,fields.length>5):undefined};
 }
}
